using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace FarmEngine.Rendering;

/// <summary>One sprite of the built-in pack: a grid of <see cref="Frames"/> × <see cref="Rows"/> cells on a sheet.</summary>
public sealed record BuiltinArtEntry
{
    public string Name { get; init; } = "";

    /// <summary>Sheet file name inside the pack (e.g. <c>objects.png</c>).</summary>
    public string File { get; init; } = "";

    public int X { get; init; }

    public int Y { get; init; }

    /// <summary>Cell width in sheet pixels.</summary>
    public int W { get; init; }

    /// <summary>Cell height in sheet pixels.</summary>
    public int H { get; init; }

    /// <summary>Columns: animation frames when <see cref="TicksPerFrame"/> is set, else look-alike variants picked by tile coordinate.</summary>
    public int Frames { get; init; } = 1;

    /// <summary>Rows: the four facing directions (down, left, right, up) when <see cref="Directional"/>.</summary>
    public int Rows { get; init; } = 1;

    /// <summary><c>bottom</c> (objects: the cell's bottom-centre sits on the tile's bottom edge) or <c>top</c> (ground tiles).</summary>
    public string Anchor { get; init; } = "bottom";

    /// <summary>Tiles covered, [width, height].</summary>
    public int[] Footprint { get; init; } = [1, 1];

    public bool Directional { get; init; }

    public int? TicksPerFrame { get; init; }

    /// <summary>Column shown while a directional sprite stands still.</summary>
    public int? IdleFrame { get; init; }

    /// <summary>Crop sheets: number of growth-stage columns.</summary>
    public int? Stages { get; init; }

    /// <summary>Machine sheets: the state each column shows (<c>idle</c>, <c>working</c>).</summary>
    public List<string>? States { get; init; }

    public bool Animated => TicksPerFrame is > 0 && Frames > 1;
}

public sealed record BuiltinArtSheet
{
    public string File { get; init; } = "";

    public int W { get; init; }

    public int H { get; init; }
}

/// <summary>The manifest written by <c>tools/art/build_art.py</c>.</summary>
public sealed record BuiltinArtManifest
{
    public int Version { get; init; }

    public int TileSize { get; init; } = 32;

    public List<string> Palette { get; init; } = [];

    public List<BuiltinArtSheet> Sheets { get; init; } = [];

    public List<BuiltinArtEntry> Entries { get; init; } = [];
}

/// <summary>
/// The built-in pixel-art pack: sprite sheets + manifest embedded in this assembly
/// (generated by <c>tools/art</c>). The renderer asks it for a sprite by content id
/// whenever a project binds no art of its own; creator art always wins. Unknown ids fall
/// back to generic sprites (a plant, a rock, a villager) so mod content still looks like
/// something. Sheets are exposed as <c>builtin://&lt;file&gt;</c> image sources that
/// <see cref="ImageStore"/> decodes once.
/// </summary>
public sealed class BuiltinArt
{
    /// <summary>Scheme of sheet image sources understood by <see cref="ImageStore"/>.</summary>
    public const string UrlScheme = "builtin://";

    private const string ResourcePrefix = "builtin/";

    private static readonly Lazy<BuiltinArt> Embedded = new(LoadEmbedded);

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    };

    private static readonly string[] DirectionRows = ["down", "left", "right", "up"];

    private readonly Dictionary<string, BuiltinArtEntry> _entries;
    private readonly Func<string, byte[]?> _sheets;

    private BuiltinArt(BuiltinArtManifest manifest, Func<string, byte[]?> sheets)
    {
        Manifest = manifest;
        _sheets = sheets;
        _entries = new Dictionary<string, BuiltinArtEntry>(StringComparer.Ordinal);
        foreach (var entry in manifest.Entries)
        {
            _entries[entry.Name] = entry;
        }
    }

    /// <summary>The pack embedded in this assembly (loaded on first use).</summary>
    public static BuiltinArt Default => Embedded.Value;

    public BuiltinArtManifest Manifest { get; }

    /// <summary>Native tile size of the pack in sheet pixels (32).</summary>
    public int TileSize => Manifest.TileSize > 0 ? Manifest.TileSize : 32;

    public IReadOnlyDictionary<string, BuiltinArtEntry> Entries => _entries;

    /// <summary>Loads a pack from a manifest stream and a sheet-bytes resolver (tests, future external packs).</summary>
    public static BuiltinArt Load(Stream manifest, Func<string, byte[]?> sheets)
    {
        ArgumentNullException.ThrowIfNull(manifest);
        ArgumentNullException.ThrowIfNull(sheets);
        var parsed = JsonSerializer.Deserialize<BuiltinArtManifest>(manifest, JsonOptions) ?? throw new InvalidDataException("Empty built-in art manifest.");
        return new BuiltinArt(parsed, sheets);
    }

    /// <summary>Image source for a sheet file (<c>builtin://objects.png</c>).</summary>
    public static string SheetUrl(string file) => UrlScheme + file;

    /// <summary>Raw PNG bytes of a <c>builtin://</c> source from the embedded pack, or null.</summary>
    public static byte[]? ResolveSheet(string source)
    {
        if (!source.StartsWith(UrlScheme, StringComparison.Ordinal))
        {
            return null;
        }

        return Default.SheetBytes(source[UrlScheme.Length..]);
    }

    /// <summary>Raw PNG bytes of a sheet file of this pack, or null when it has none.</summary>
    public byte[]? SheetBytes(string file) => _sheets(file);

    public BuiltinArtEntry? Find(string name) => _entries.GetValueOrDefault(name);

    /// <summary>Deterministic 32-bit mix of tile coordinates (variant selection; no <see cref="Random"/>).</summary>
    public static uint Hash(int x, int y)
    {
        var h = unchecked((uint)x * 0x9E3779B1u) ^ unchecked((uint)y * 0x85EBCA77u);
        h ^= h >> 15;
        h *= 0x2C1B3C6Du;
        h ^= h >> 12;
        h *= 0x297A2D39u;
        h ^= h >> 15;
        return h;
    }

    /// <summary>A sprite for column <paramref name="frame"/>, row <paramref name="row"/> of an entry.</summary>
    public SnapshotSprite Sprite(BuiltinArtEntry entry, int frame = 0, int row = 0)
    {
        ArgumentNullException.ThrowIfNull(entry);
        var column = entry.Frames > 0 ? Math.Clamp(frame, 0, entry.Frames - 1) : 0;
        var line = entry.Rows > 0 ? Math.Clamp(row, 0, entry.Rows - 1) : 0;
        return new SnapshotSprite
        {
            ImageUrl = SheetUrl(entry.File),
            FrameWidth = entry.W,
            FrameHeight = entry.H,
            SourceX = entry.X + (column * entry.W),
            SourceY = entry.Y + (line * entry.H),
            Frame = column,
            Row = line,
        };
    }

    /// <summary>Variant column for a tile coordinate (animation frame when the entry is animated).</summary>
    public static int Column(BuiltinArtEntry entry, int x, int y, double tick)
    {
        ArgumentNullException.ThrowIfNull(entry);
        if (entry.Frames <= 1)
        {
            return 0;
        }

        if (entry.Animated)
        {
            return (int)(Math.Floor(Math.Max(0, tick) / entry.TicksPerFrame!.Value) % entry.Frames);
        }

        return (int)(Hash(x, y) % (uint)entry.Frames);
    }

    /// <summary>Ground tile for a tile type (<c>grass</c>, <c>soil</c>, <c>water</c>, …), seasonal when the pack has it.</summary>
    public SnapshotSprite? Tile(string? type, string? season, int x, int y, double tick)
    {
        if (string.IsNullOrEmpty(type))
        {
            return null;
        }

        var entry = (season is not null ? Find($"tile-{type}-{season}") : null) ?? Find($"tile-{type}");
        return entry is null ? null : Sprite(entry, Column(entry, x, y, tick));
    }

    /// <summary>Tilled soil, wet or dry.</summary>
    public SnapshotSprite? Soil(bool watered, int x, int y)
    {
        var entry = (watered ? Find("tile-soil-watered") : null) ?? Find("tile-soil");
        return entry is null ? null : Sprite(entry, Column(entry, x, y, 0));
    }

    /// <summary>Fertilizer speckles drawn over soil.</summary>
    public SnapshotSprite? FertilizedMarker() => Find("tile-soil-fertilized") is { } entry ? Sprite(entry) : null;

    public SnapshotSprite? Ladder() => Find("tile-ladder") is { } entry ? Sprite(entry) : null;

    /// <summary>"Output ready" bubble shown above machines.</summary>
    public SnapshotSprite? ReadyMarker() => Find("fx-ready") is { } entry ? Sprite(entry) : null;

    /// <summary>
    /// Crop art by content id and growth stage. <paramref name="stage"/> is the engine's stage
    /// (0 … <paramref name="stages"/> − 1); it is mapped onto the sheet's stage columns so
    /// 4-, 5- and 6-stage crops all grow through the whole sheet.
    /// </summary>
    public SnapshotSprite? Crop(string? cropId, int stage, int stages, bool withered, bool mature = false)
    {
        if (withered && Find("crop-withered") is { } dead)
        {
            return Sprite(dead);
        }

        var entry = (cropId is not null ? Find($"crop-{cropId}") : null) ?? Find("crop-generic");
        if (entry is null)
        {
            return null;
        }

        var columns = entry.Stages ?? entry.Frames;
        if (mature)
        {
            return Sprite(entry, columns - 1);
        }

        var lastEngineStage = Math.Max(1, stages - 1);
        var column = (int)Math.Round(Math.Clamp(stage, 0, lastEngineStage) / (double)lastEngineStage * (columns - 1));
        return Sprite(entry, column);
    }

    /// <summary>Gathering node art by node type id (generic rock when unknown).</summary>
    public SnapshotSprite? Node(string? typeId, int x, int y)
    {
        var entry = NodeEntry(typeId);
        return entry is null ? null : Sprite(entry, Column(entry, x, y, 0));
    }

    /// <summary>Machine art by machine type id; column 1 while working when the sheet has one.</summary>
    public SnapshotSprite? Machine(string? typeId, bool working)
    {
        var entry = MachineEntry(typeId);
        if (entry is null)
        {
            return null;
        }

        var column = working && entry.States is { } states ? Math.Max(0, states.IndexOf("working")) : 0;
        return Sprite(entry, column);
    }

    /// <summary>Dropped item art by item type (<c>seed</c>, <c>material</c>, …).</summary>
    public SnapshotSprite? Item(string? itemType)
    {
        var entry = itemType switch
        {
            "seed" => Find("item-seed"),
            "material" or "tool" or "fertilizer" => Find("item-material"),
            _ => null,
        } ?? Find("item-generic");
        return entry is null ? null : Sprite(entry);
    }

    /// <summary>Animal art by species id (chicken when unknown).</summary>
    public SnapshotSprite? Animal(string? speciesId, string? direction, double tick, bool moving) =>
        Actor(AnimalEntry(speciesId), direction, tick, moving);

    /// <summary>NPC art by <c>Npc.Appearance</c> (a generic villager when unknown).</summary>
    public SnapshotSprite? Npc(string? appearance, string? direction, double tick, bool moving) =>
        Actor(NpcEntry(appearance), direction, tick, moving);

    public SnapshotSprite? Player(string? direction, double tick, bool moving) =>
        Actor(Find("char-player") ?? Find("npc-villager"), direction, tick, moving);

    /// <summary>The entry a gathering node id resolves to (also used by tests).</summary>
    public BuiltinArtEntry? NodeEntry(string? typeId)
    {
        if (typeId is not null && Find(typeId) is { } exact)
        {
            return exact;
        }

        var id = typeId?.ToLowerInvariant() ?? "";
        return Find(Guess(id,
            ("tree", "node-tree"), ("stump", "node-stump"), ("log", "node-stump"),
            ("weed", "node-weeds"), ("grass", "node-weeds"), ("bush", "node-weeds"), ("fiber", "node-weeds"),
            ("boulder", "node-boulder"), ("copper", "node-copper-ore"), ("iron", "node-iron-ore"),
            ("quartz", "node-quartz"), ("crystal", "node-quartz"), ("gem", "node-quartz"),
            ("ore", "node-copper-ore"), ("mine", "node-mine-rock"))
            ?? "node-rock") ?? Find("node-rock");
    }

    public BuiltinArtEntry? MachineEntry(string? typeId)
    {
        if (typeId is not null && Find(typeId) is { } exact)
        {
            return exact;
        }

        var id = typeId?.ToLowerInvariant() ?? "";
        return Find(Guess(id,
            ("furnace", "machine-furnace"), ("forge", "machine-furnace"), ("kiln", "machine-furnace"), ("smelt", "machine-furnace"),
            ("preserve", "machine-preserves"), ("jar", "machine-preserves"), ("keg", "machine-preserves"),
            ("kitchen", "machine-kitchen"), ("stove", "machine-kitchen"), ("oven", "machine-kitchen"), ("cook", "machine-kitchen"),
            ("bench", "machine-workbench"), ("work", "machine-workbench"), ("carpen", "machine-workbench"),
            ("altar", "machine-altar"), ("magic", "machine-altar"), ("enchant", "machine-altar"))
            ?? "machine-generic") ?? Find("machine-generic");
    }

    public BuiltinArtEntry? AnimalEntry(string? speciesId)
    {
        if (speciesId is not null && Find(speciesId) is { } exact)
        {
            return exact;
        }

        var id = speciesId?.ToLowerInvariant() ?? "";
        return Find(Guess(id,
            ("chicken", "animal-chicken"), ("hen", "animal-chicken"), ("duck", "animal-chicken"), ("bird", "animal-chicken"),
            ("cow", "animal-cow"), ("sheep", "animal-cow"), ("goat", "animal-cow"), ("pig", "animal-cow"), ("horse", "animal-cow"))
            ?? "animal-chicken") ?? Find("animal-chicken");
    }

    public BuiltinArtEntry? NpcEntry(string? appearance)
    {
        if (!string.IsNullOrEmpty(appearance) && (Find($"npc-{appearance}") ?? Find(appearance)) is { } exact)
        {
            return exact;
        }

        var id = appearance?.ToLowerInvariant() ?? "";
        return Find(Guess(id, ("farm", "npc-farmer"), ("elder", "npc-farmer"), ("merchant", "npc-merchant"), ("shop", "npc-merchant"), ("vendor", "npc-merchant"))
            ?? "npc-villager") ?? Find("npc-villager");
    }

    private static string? Guess(string id, params (string Keyword, string Entry)[] rules)
    {
        foreach (var (keyword, entry) in rules)
        {
            if (id.Contains(keyword, StringComparison.Ordinal))
            {
                return entry;
            }
        }

        return null;
    }

    private SnapshotSprite? Actor(BuiltinArtEntry? entry, string? direction, double tick, bool moving)
    {
        if (entry is null)
        {
            return null;
        }

        var row = entry.Directional ? Math.Max(0, Array.IndexOf(DirectionRows, direction ?? "down")) : 0;
        int column;
        if (entry.Animated && (moving || entry.IdleFrame is null))
        {
            column = (int)(Math.Floor(Math.Max(0, tick) / entry.TicksPerFrame!.Value) % entry.Frames);
        }
        else
        {
            column = entry.IdleFrame ?? 0;
        }

        return Sprite(entry, column, row);
    }

    private static BuiltinArt LoadEmbedded()
    {
        var assembly = typeof(BuiltinArt).Assembly;
        using var manifest = assembly.GetManifestResourceStream(ResourcePrefix + "manifest.json")
            ?? throw new InvalidOperationException("The built-in art manifest is missing from FarmEngine.Rendering.");
        return Load(manifest, file => ReadResource(assembly, ResourcePrefix + file));
    }

    private static byte[]? ReadResource(Assembly assembly, string name)
    {
        using var stream = assembly.GetManifestResourceStream(name);
        if (stream is null)
        {
            return null;
        }

        using var copy = new MemoryStream();
        stream.CopyTo(copy);
        return copy.ToArray();
    }
}
