namespace FarmEngine.Authoring.Net

// Generated by tools/codegen/record-with.fsx from the schema records in Schema.fs. Do not edit.

open System
open System.Collections.Generic
open System.Runtime.CompilerServices
open FarmEngine.Authoring
open FarmEngine.Schemas

/// `{ record with Field = value }` for C#, one `WithField` per record field: options take
/// the value or null (value types: a `Nullable`), lists any sequence, ordered maps any
/// key/value pairs. `Record.Default.WithA(a).WithB(b)` builds a record.
[<Extension; AbstractClass; Sealed>]
type RecordWith =
    [<Extension>]
    static member WithId(record: ActionDef, value: string) : ActionDef = { record with Id = value }
    [<Extension>]
    static member WithName(record: ActionDef, value: string) : ActionDef = { record with Name = value }
    [<Extension>]
    static member WithDescription(record: ActionDef, value: string) : ActionDef = { record with Description = value }
    [<Extension>]
    static member WithConditions(record: ActionDef, value: seq<EventCondition>) : ActionDef = { record with Conditions = List.ofSeq value }
    [<Extension>]
    static member WithFailMessage(record: ActionDef, value: string) : ActionDef = { record with FailMessage = value }
    [<Extension>]
    static member WithOutcomes(record: ActionDef, value: seq<EventOutcome>) : ActionDef = { record with Outcomes = List.ofSeq value }
    [<Extension>]
    static member WithEnergyCost(record: ActionDef, value: float) : ActionDef = { record with EnergyCost = value }
    [<Extension>]
    static member WithHotkey(record: ActionDef, value: string | null) : ActionDef = { record with Hotkey = Option.ofObj value }
    [<Extension>]
    static member WithId(record: AnimalSpeciesDefinition, value: string) : AnimalSpeciesDefinition = { record with Id = value }
    [<Extension>]
    static member WithName(record: AnimalSpeciesDefinition, value: string) : AnimalSpeciesDefinition = { record with Name = value }
    [<Extension>]
    static member WithVisual(record: AnimalSpeciesDefinition, value: VisualRef | null) : AnimalSpeciesDefinition = { record with Visual = Option.ofObj value }
    [<Extension>]
    static member WithPurchaseCost(record: AnimalSpeciesDefinition, value: float) : AnimalSpeciesDefinition = { record with PurchaseCost = value }
    [<Extension>]
    static member WithFeedItemId(record: AnimalSpeciesDefinition, value: string | null) : AnimalSpeciesDefinition = { record with FeedItemId = Option.ofObj value }
    [<Extension>]
    static member WithProductItemId(record: AnimalSpeciesDefinition, value: string) : AnimalSpeciesDefinition = { record with ProductItemId = value }
    [<Extension>]
    static member WithProductIntervalDays(record: AnimalSpeciesDefinition, value: float) : AnimalSpeciesDefinition = { record with ProductIntervalDays = value }
    [<Extension>]
    static member WithDaysToAdult(record: AnimalSpeciesDefinition, value: float) : AnimalSpeciesDefinition = { record with DaysToAdult = value }
    [<Extension>]
    static member WithColor(record: AnimalSpeciesDefinition, value: string) : AnimalSpeciesDefinition = { record with Color = value }
    [<Extension>]
    static member WithId(record: AnimalState, value: string) : AnimalState = { record with Id = value }
    [<Extension>]
    static member WithSpeciesId(record: AnimalState, value: string) : AnimalState = { record with SpeciesId = value }
    [<Extension>]
    static member WithName(record: AnimalState, value: string) : AnimalState = { record with Name = value }
    [<Extension>]
    static member WithSceneId(record: AnimalState, value: string) : AnimalState = { record with SceneId = value }
    [<Extension>]
    static member WithX(record: AnimalState, value: float) : AnimalState = { record with X = value }
    [<Extension>]
    static member WithY(record: AnimalState, value: float) : AnimalState = { record with Y = value }
    [<Extension>]
    static member WithMood(record: AnimalState, value: float) : AnimalState = { record with Mood = value }
    [<Extension>]
    static member WithFedToday(record: AnimalState, value: bool) : AnimalState = { record with FedToday = value }
    [<Extension>]
    static member WithPettedToday(record: AnimalState, value: bool) : AnimalState = { record with PettedToday = value }
    [<Extension>]
    static member WithAgeDays(record: AnimalState, value: float) : AnimalState = { record with AgeDays = value }
    [<Extension>]
    static member WithDaysSinceProduct(record: AnimalState, value: float) : AnimalState = { record with DaysSinceProduct = value }
    [<Extension>]
    static member WithProductReady(record: AnimalState, value: bool) : AnimalState = { record with ProductReady = value }
    [<Extension>]
    static member WithName(record: AnimationClip, value: string) : AnimationClip = { record with Name = value }
    [<Extension>]
    static member WithLoop(record: AnimationClip, value: bool) : AnimationClip = { record with Loop = value }
    [<Extension>]
    static member WithFrames(record: AnimationClip, value: seq<ArtFrame>) : AnimationClip = { record with Frames = List.ofSeq value }
    [<Extension>]
    static member WithAssetId(record: ArtFrame, value: string | null) : ArtFrame = { record with AssetId = Option.ofObj value }
    [<Extension>]
    static member WithX(record: ArtFrame, value: float) : ArtFrame = { record with X = value }
    [<Extension>]
    static member WithY(record: ArtFrame, value: float) : ArtFrame = { record with Y = value }
    [<Extension>]
    static member WithWidth(record: ArtFrame, value: float) : ArtFrame = { record with Width = value }
    [<Extension>]
    static member WithHeight(record: ArtFrame, value: float) : ArtFrame = { record with Height = value }
    [<Extension>]
    static member WithTicks(record: ArtFrame, value: float) : ArtFrame = { record with Ticks = value }
    [<Extension>]
    static member WithSeasons(record: CalendarConfig, value: seq<CalendarSeason>) : CalendarConfig = { record with Seasons = List.ofSeq value }
    [<Extension>]
    static member WithFestivals(record: CalendarConfig, value: seq<CalendarFestival>) : CalendarConfig = { record with Festivals = List.ofSeq value }
    [<Extension>]
    static member WithId(record: CalendarFestival, value: string) : CalendarFestival = { record with Id = value }
    [<Extension>]
    static member WithName(record: CalendarFestival, value: string) : CalendarFestival = { record with Name = value }
    [<Extension>]
    static member WithSeasonId(record: CalendarFestival, value: string) : CalendarFestival = { record with SeasonId = value }
    [<Extension>]
    static member WithDay(record: CalendarFestival, value: float) : CalendarFestival = { record with Day = value }
    [<Extension>]
    static member WithId(record: CalendarSeason, value: string) : CalendarSeason = { record with Id = value }
    [<Extension>]
    static member WithName(record: CalendarSeason, value: string) : CalendarSeason = { record with Name = value }
    [<Extension>]
    static member WithDays(record: CalendarSeason, value: float) : CalendarSeason = { record with Days = value }
    [<Extension>]
    static member WithManifest(record: ContentPack, value: PackManifest) : ContentPack = { record with Manifest = value }
    [<Extension>]
    static member WithContent(record: ContentPack, value: PackContent) : ContentPack = { record with Content = value }
    [<Extension>]
    static member WithPlugins(record: ContentPack, value: seq<PackPlugin>) : ContentPack = { record with Plugins = List.ofSeq value }
    [<Extension>]
    static member WithType(record: Crop, value: string) : Crop = { record with Type = value }
    [<Extension>]
    static member WithPlantedAt(record: Crop, value: float) : Crop = { record with PlantedAt = value }
    [<Extension>]
    static member WithPlantedOnDay(record: Crop, value: Nullable<float>) : Crop = { record with PlantedOnDay = Option.ofNullable value }
    [<Extension>]
    static member WithDaysGrown(record: Crop, value: Nullable<float>) : Crop = { record with DaysGrown = Option.ofNullable value }
    [<Extension>]
    static member WithWithered(record: Crop, value: Nullable<bool>) : Crop = { record with Withered = Option.ofNullable value }
    [<Extension>]
    static member WithStage(record: Crop, value: float) : Crop = { record with Stage = value }
    [<Extension>]
    static member WithWatered(record: Crop, value: bool) : Crop = { record with Watered = value }
    [<Extension>]
    static member WithLastWateredDay(record: Crop, value: Nullable<float>) : Crop = { record with LastWateredDay = Option.ofNullable value }
    [<Extension>]
    static member WithQuality(record: Crop, value: string) : Crop = { record with Quality = value }
    [<Extension>]
    static member WithMutation(record: Crop, value: string | null) : Crop = { record with Mutation = Option.ofObj value }
    [<Extension>]
    static member WithIsMultiTileRoot(record: Crop, value: Nullable<bool>) : Crop = { record with IsMultiTileRoot = Option.ofNullable value }
    [<Extension>]
    static member WithMultiTileId(record: Crop, value: string | null) : Crop = { record with MultiTileId = Option.ofObj value }
    [<Extension>]
    static member WithHarvestCount(record: Crop, value: float) : Crop = { record with HarvestCount = value }
    [<Extension>]
    static member WithDaysWithoutWater(record: Crop, value: float) : Crop = { record with DaysWithoutWater = value }
    [<Extension>]
    static member WithId(record: CropDefinition, value: string) : CropDefinition = { record with Id = value }
    [<Extension>]
    static member WithName(record: CropDefinition, value: string) : CropDefinition = { record with Name = value }
    [<Extension>]
    static member WithVisual(record: CropDefinition, value: VisualRef | null) : CropDefinition = { record with Visual = Option.ofObj value }
    [<Extension>]
    static member WithSeedCost(record: CropDefinition, value: float) : CropDefinition = { record with SeedCost = value }
    [<Extension>]
    static member WithBaseHarvestValue(record: CropDefinition, value: float) : CropDefinition = { record with BaseHarvestValue = value }
    [<Extension>]
    static member WithGrowthTime(record: CropDefinition, value: float) : CropDefinition = { record with GrowthTime = value }
    [<Extension>]
    static member WithGrowthDays(record: CropDefinition, value: Nullable<float>) : CropDefinition = { record with GrowthDays = Option.ofNullable value }
    [<Extension>]
    static member WithStages(record: CropDefinition, value: float) : CropDefinition = { record with Stages = value }
    [<Extension>]
    static member WithSeasons(record: CropDefinition, value: seq<string>) : CropDefinition = { record with Seasons = List.ofSeq value }
    [<Extension>]
    static member WithRegrowthTime(record: CropDefinition, value: Nullable<float>) : CropDefinition = { record with RegrowthTime = Option.ofNullable value }
    [<Extension>]
    static member WithRegrowthDays(record: CropDefinition, value: Nullable<float>) : CropDefinition = { record with RegrowthDays = Option.ofNullable value }
    [<Extension>]
    static member WithCanRegrow(record: CropDefinition, value: bool) : CropDefinition = { record with CanRegrow = value }
    [<Extension>]
    static member WithMultiTile(record: CropDefinition, value: CropMultiTile | null) : CropDefinition = { record with MultiTile = Option.ofObj value }
    [<Extension>]
    static member WithMutationChance(record: CropDefinition, value: Nullable<float>) : CropDefinition = { record with MutationChance = Option.ofNullable value }
    [<Extension>]
    static member WithYieldMin(record: CropDefinition, value: float) : CropDefinition = { record with YieldMin = value }
    [<Extension>]
    static member WithYieldMax(record: CropDefinition, value: float) : CropDefinition = { record with YieldMax = value }
    [<Extension>]
    static member WithWidth(record: CropMultiTile, value: float) : CropMultiTile = { record with Width = value }
    [<Extension>]
    static member WithHeight(record: CropMultiTile, value: float) : CropMultiTile = { record with Height = value }
    [<Extension>]
    static member WithId(record: CustomAsset, value: string) : CustomAsset = { record with Id = value }
    [<Extension>]
    static member WithName(record: CustomAsset, value: string) : CustomAsset = { record with Name = value }
    [<Extension>]
    static member WithType(record: CustomAsset, value: string) : CustomAsset = { record with Type = value }
    [<Extension>]
    static member WithWidth(record: CustomAsset, value: Nullable<float>) : CustomAsset = { record with Width = Option.ofNullable value }
    [<Extension>]
    static member WithHeight(record: CustomAsset, value: Nullable<float>) : CustomAsset = { record with Height = Option.ofNullable value }
    [<Extension>]
    static member WithAnimations(record: CustomAsset, value: seq<AnimationClip> | null) : CustomAsset = { record with Animations = (match value with null -> None | items -> Some(List.ofSeq items)) }
    [<Extension>]
    static member WithDataUrl(record: CustomAsset, value: string) : CustomAsset = { record with DataUrl = value }
    [<Extension>]
    static member WithTileType(record: CustomAsset, value: string | null) : CustomAsset = { record with TileType = Option.ofObj value }
    [<Extension>]
    static member WithSheet(record: CustomAsset, value: SpriteSheet | null) : CustomAsset = { record with Sheet = Option.ofObj value }
    [<Extension>]
    static member WithId(record: CustomCropDefinition, value: string) : CustomCropDefinition = { record with Id = value }
    [<Extension>]
    static member WithName(record: CustomCropDefinition, value: string) : CustomCropDefinition = { record with Name = value }
    [<Extension>]
    static member WithVisual(record: CustomCropDefinition, value: VisualRef | null) : CustomCropDefinition = { record with Visual = Option.ofObj value }
    [<Extension>]
    static member WithSeedCost(record: CustomCropDefinition, value: float) : CustomCropDefinition = { record with SeedCost = value }
    [<Extension>]
    static member WithBaseHarvestValue(record: CustomCropDefinition, value: float) : CustomCropDefinition = { record with BaseHarvestValue = value }
    [<Extension>]
    static member WithGrowthTime(record: CustomCropDefinition, value: float) : CustomCropDefinition = { record with GrowthTime = value }
    [<Extension>]
    static member WithGrowthDays(record: CustomCropDefinition, value: Nullable<float>) : CustomCropDefinition = { record with GrowthDays = Option.ofNullable value }
    [<Extension>]
    static member WithStages(record: CustomCropDefinition, value: float) : CustomCropDefinition = { record with Stages = value }
    [<Extension>]
    static member WithSeasons(record: CustomCropDefinition, value: seq<string>) : CustomCropDefinition = { record with Seasons = List.ofSeq value }
    [<Extension>]
    static member WithRegrowthTime(record: CustomCropDefinition, value: Nullable<float>) : CustomCropDefinition = { record with RegrowthTime = Option.ofNullable value }
    [<Extension>]
    static member WithRegrowthDays(record: CustomCropDefinition, value: Nullable<float>) : CustomCropDefinition = { record with RegrowthDays = Option.ofNullable value }
    [<Extension>]
    static member WithCanRegrow(record: CustomCropDefinition, value: bool) : CustomCropDefinition = { record with CanRegrow = value }
    [<Extension>]
    static member WithMultiTile(record: CustomCropDefinition, value: CropMultiTile | null) : CustomCropDefinition = { record with MultiTile = Option.ofObj value }
    [<Extension>]
    static member WithMutationChance(record: CustomCropDefinition, value: Nullable<float>) : CustomCropDefinition = { record with MutationChance = Option.ofNullable value }
    [<Extension>]
    static member WithYieldMin(record: CustomCropDefinition, value: float) : CustomCropDefinition = { record with YieldMin = value }
    [<Extension>]
    static member WithYieldMax(record: CustomCropDefinition, value: float) : CustomCropDefinition = { record with YieldMax = value }
    [<Extension>]
    static member WithCustomAsset(record: CustomCropDefinition, value: string | null) : CustomCropDefinition = { record with CustomAsset = Option.ofObj value }
    [<Extension>]
    static member WithMinDay(record: DayRangeCondition, value: Nullable<float>) : DayRangeCondition = { record with MinDay = Option.ofNullable value }
    [<Extension>]
    static member WithMaxDay(record: DayRangeCondition, value: Nullable<float>) : DayRangeCondition = { record with MaxDay = Option.ofNullable value }
    [<Extension>]
    static member WithId(record: Dialogue, value: string) : Dialogue = { record with Id = value }
    [<Extension>]
    static member WithNpcId(record: Dialogue, value: string) : Dialogue = { record with NpcId = value }
    [<Extension>]
    static member WithText(record: Dialogue, value: string) : Dialogue = { record with Text = value }
    [<Extension>]
    static member WithOptions(record: Dialogue, value: seq<DialogueOption>) : Dialogue = { record with Options = List.ofSeq value }
    [<Extension>]
    static member WithText(record: DialogueOption, value: string) : DialogueOption = { record with Text = value }
    [<Extension>]
    static member WithNextDialogueId(record: DialogueOption, value: string | null) : DialogueOption = { record with NextDialogueId = Option.ofObj value }
    [<Extension>]
    static member WithGiveItem(record: DialogueOption, value: string | null) : DialogueOption = { record with GiveItem = Option.ofObj value }
    [<Extension>]
    static member WithGiveItemQuantity(record: DialogueOption, value: Nullable<float>) : DialogueOption = { record with GiveItemQuantity = Option.ofNullable value }
    [<Extension>]
    static member WithTakeMoney(record: DialogueOption, value: Nullable<float>) : DialogueOption = { record with TakeMoney = Option.ofNullable value }
    [<Extension>]
    static member WithGiveMoney(record: DialogueOption, value: Nullable<float>) : DialogueOption = { record with GiveMoney = Option.ofNullable value }
    [<Extension>]
    static member WithEventFlag(record: DialogueOption, value: string | null) : DialogueOption = { record with EventFlag = Option.ofObj value }
    [<Extension>]
    static member WithRequiresItem(record: DialogueOption, value: string | null) : DialogueOption = { record with RequiresItem = Option.ofObj value }
    [<Extension>]
    static member WithRequiresFlag(record: DialogueOption, value: string | null) : DialogueOption = { record with RequiresFlag = Option.ofObj value }
    [<Extension>]
    static member WithOpenShopId(record: DialogueOption, value: string | null) : DialogueOption = { record with OpenShopId = Option.ofObj value }
    [<Extension>]
    static member WithOfferQuestId(record: DialogueOption, value: string | null) : DialogueOption = { record with OfferQuestId = Option.ofObj value }
    [<Extension>]
    static member WithRequiresFriendship(record: DialogueOption, value: Nullable<float>) : DialogueOption = { record with RequiresFriendship = Option.ofNullable value }
    [<Extension>]
    static member WithActionId(record: DialogueOption, value: string | null) : DialogueOption = { record with ActionId = Option.ofObj value }
    [<Extension>]
    static member WithX(record: EnterTileCondition, value: float) : EnterTileCondition = { record with X = value }
    [<Extension>]
    static member WithY(record: EnterTileCondition, value: float) : EnterTileCondition = { record with Y = value }
    [<Extension>]
    static member WithX2(record: EnterTileCondition, value: Nullable<float>) : EnterTileCondition = { record with X2 = Option.ofNullable value }
    [<Extension>]
    static member WithY2(record: EnterTileCondition, value: Nullable<float>) : EnterTileCondition = { record with Y2 = Option.ofNullable value }
    [<Extension>]
    static member WithType(record: EventOutcome, value: string) : EventOutcome = { record with Type = value }
    [<Extension>]
    static member WithMessage(record: EventOutcome, value: string | null) : EventOutcome = { record with Message = Option.ofObj value }
    [<Extension>]
    static member WithItemId(record: EventOutcome, value: string | null) : EventOutcome = { record with ItemId = Option.ofObj value }
    [<Extension>]
    static member WithItemQuantity(record: EventOutcome, value: Nullable<float>) : EventOutcome = { record with ItemQuantity = Option.ofNullable value }
    [<Extension>]
    static member WithAmount(record: EventOutcome, value: Nullable<float>) : EventOutcome = { record with Amount = Option.ofNullable value }
    [<Extension>]
    static member WithRadius(record: EventOutcome, value: Nullable<float>) : EventOutcome = { record with Radius = Option.ofNullable value }
    [<Extension>]
    static member WithFlagName(record: EventOutcome, value: string | null) : EventOutcome = { record with FlagName = Option.ofObj value }
    [<Extension>]
    static member WithQuestId(record: EventOutcome, value: string | null) : EventOutcome = { record with QuestId = Option.ofObj value }
    [<Extension>]
    static member WithNpcId(record: EventOutcome, value: string | null) : EventOutcome = { record with NpcId = Option.ofObj value }
    [<Extension>]
    static member WithDialogueId(record: EventOutcome, value: string | null) : EventOutcome = { record with DialogueId = Option.ofObj value }
    [<Extension>]
    static member WithTileX(record: EventOutcome, value: Nullable<float>) : EventOutcome = { record with TileX = Option.ofNullable value }
    [<Extension>]
    static member WithTileY(record: EventOutcome, value: Nullable<float>) : EventOutcome = { record with TileY = Option.ofNullable value }
    [<Extension>]
    static member WithNewTileType(record: EventOutcome, value: string | null) : EventOutcome = { record with NewTileType = Option.ofObj value }
    [<Extension>]
    static member WithSceneId(record: EventOutcome, value: string | null) : EventOutcome = { record with SceneId = Option.ofObj value }
    [<Extension>]
    static member WithX(record: EventOutcome, value: Nullable<float>) : EventOutcome = { record with X = Option.ofNullable value }
    [<Extension>]
    static member WithY(record: EventOutcome, value: Nullable<float>) : EventOutcome = { record with Y = Option.ofNullable value }
    [<Extension>]
    static member WithSoundId(record: EventOutcome, value: string | null) : EventOutcome = { record with SoundId = Option.ofObj value }
    [<Extension>]
    static member WithActionId(record: EventOutcome, value: string | null) : EventOutcome = { record with ActionId = Option.ofObj value }
    [<Extension>]
    static member WithMinigameId(record: EventOutcome, value: string | null) : EventOutcome = { record with MinigameId = Option.ofObj value }
    [<Extension>]
    static member WithTitle(record: ExportSettings, value: string | null) : ExportSettings = { record with Title = Option.ofObj value }
    [<Extension>]
    static member WithExecutableName(record: ExportSettings, value: string | null) : ExportSettings = { record with ExecutableName = Option.ofObj value }
    [<Extension>]
    static member WithVersion(record: ExportSettings, value: string | null) : ExportSettings = { record with Version = Option.ofObj value }
    [<Extension>]
    static member WithGameId(record: ExportSettings, value: string) : ExportSettings = { record with GameId = value }
    [<Extension>]
    static member WithAuthor(record: ExportSettings, value: string | null) : ExportSettings = { record with Author = Option.ofObj value }
    [<Extension>]
    static member WithCompany(record: ExportSettings, value: string | null) : ExportSettings = { record with Company = Option.ofObj value }
    [<Extension>]
    static member WithIconAssetId(record: ExportSettings, value: string | null) : ExportSettings = { record with IconAssetId = Option.ofObj value }
    [<Extension>]
    static member WithWindow(record: ExportSettings, value: ExportWindow) : ExportSettings = { record with Window = value }
    [<Extension>]
    static member WithPixelScale(record: ExportSettings, value: string) : ExportSettings = { record with PixelScale = value }
    [<Extension>]
    static member WithCredits(record: ExportSettings, value: string | null) : ExportSettings = { record with Credits = Option.ofObj value }
    [<Extension>]
    static member WithTargets(record: ExportSettings, value: seq<string>) : ExportSettings = { record with Targets = List.ofSeq value }
    [<Extension>]
    static member WithWidth(record: ExportWindow, value: int) : ExportWindow = { record with Width = value }
    [<Extension>]
    static member WithHeight(record: ExportWindow, value: int) : ExportWindow = { record with Height = value }
    [<Extension>]
    static member WithFullscreen(record: ExportWindow, value: bool) : ExportWindow = { record with Fullscreen = value }
    [<Extension>]
    static member WithSchemaVersion(record: ExportedGame, value: Nullable<float>) : ExportedGame = { record with SchemaVersion = Option.ofNullable value }
    [<Extension>]
    static member WithVersion(record: ExportedGame, value: string) : ExportedGame = { record with Version = value }
    [<Extension>]
    static member WithName(record: ExportedGame, value: string) : ExportedGame = { record with Name = value }
    [<Extension>]
    static member WithScenes(record: ExportedGame, value: seq<Scene>) : ExportedGame = { record with Scenes = List.ofSeq value }
    [<Extension>]
    static member WithNpcs(record: ExportedGame, value: seq<Npc>) : ExportedGame = { record with Npcs = List.ofSeq value }
    [<Extension>]
    static member WithItems(record: ExportedGame, value: seq<Item>) : ExportedGame = { record with Items = List.ofSeq value }
    [<Extension>]
    static member WithEvents(record: ExportedGame, value: seq<GameEvent>) : ExportedGame = { record with Events = List.ofSeq value }
    [<Extension>]
    static member WithDialogues(record: ExportedGame, value: seq<Dialogue>) : ExportedGame = { record with Dialogues = List.ofSeq value }
    [<Extension>]
    static member WithQuests(record: ExportedGame, value: seq<Quest>) : ExportedGame = { record with Quests = List.ofSeq value }
    [<Extension>]
    static member WithStartSceneId(record: ExportedGame, value: string) : ExportedGame = { record with StartSceneId = value }
    [<Extension>]
    static member WithCustomAssets(record: ExportedGame, value: seq<CustomAsset>) : ExportedGame = { record with CustomAssets = List.ofSeq value }
    [<Extension>]
    static member WithCustomCrops(record: ExportedGame, value: seq<CustomCropDefinition> | null) : ExportedGame = { record with CustomCrops = (match value with null -> None | items -> Some(List.ofSeq items)) }
    [<Extension>]
    static member WithPlayerCustomImage(record: ExportedGame, value: string | null) : ExportedGame = { record with PlayerCustomImage = Option.ofObj value }
    [<Extension>]
    static member WithPlayerVisual(record: ExportedGame, value: VisualRef | null) : ExportedGame = { record with PlayerVisual = Option.ofObj value }
    [<Extension>]
    static member WithGraphics(record: ExportedGame, value: GraphicsSettings | null) : ExportedGame = { record with Graphics = Option.ofObj value }
    [<Extension>]
    static member WithGamePanels(record: ExportedGame, value: seq<GamePanel> | null) : ExportedGame = { record with GamePanels = (match value with null -> None | items -> Some(List.ofSeq items)) }
    [<Extension>]
    static member WithCurrentSeason(record: ExportedGame, value: string) : ExportedGame = { record with CurrentSeason = value }
    [<Extension>]
    static member WithCurrentDay(record: ExportedGame, value: float) : ExportedGame = { record with CurrentDay = value }
    [<Extension>]
    static member WithCurrentTimeMinutes(record: ExportedGame, value: float) : ExportedGame = { record with CurrentTimeMinutes = value }
    [<Extension>]
    static member WithCurrentYear(record: ExportedGame, value: float) : ExportedGame = { record with CurrentYear = value }
    [<Extension>]
    static member WithGameStartTime(record: ExportedGame, value: float) : ExportedGame = { record with GameStartTime = value }
    [<Extension>]
    static member WithShops(record: ExportedGame, value: seq<ShopDefinition>) : ExportedGame = { record with Shops = List.ofSeq value }
    [<Extension>]
    static member WithNodeTypes(record: ExportedGame, value: seq<NodeTypeDefinition>) : ExportedGame = { record with NodeTypes = List.ofSeq value }
    [<Extension>]
    static member WithSettings(record: ExportedGame, value: ProjectSettings) : ExportedGame = { record with Settings = value }
    [<Extension>]
    static member WithRecipes(record: ExportedGame, value: seq<RecipeDefinition>) : ExportedGame = { record with Recipes = List.ofSeq value }
    [<Extension>]
    static member WithMachineTypes(record: ExportedGame, value: seq<MachineTypeDefinition>) : ExportedGame = { record with MachineTypes = List.ofSeq value }
    [<Extension>]
    static member WithWeather(record: ExportedGame, value: WeatherConfig) : ExportedGame = { record with Weather = value }
    [<Extension>]
    static member WithAnimalSpecies(record: ExportedGame, value: seq<AnimalSpeciesDefinition>) : ExportedGame = { record with AnimalSpecies = List.ofSeq value }
    [<Extension>]
    static member WithAnimals(record: ExportedGame, value: seq<AnimalState>) : ExportedGame = { record with Animals = List.ofSeq value }
    [<Extension>]
    static member WithFishTables(record: ExportedGame, value: seq<FishTable>) : ExportedGame = { record with FishTables = List.ofSeq value }
    [<Extension>]
    static member WithMine(record: ExportedGame, value: MineConfig) : ExportedGame = { record with Mine = value }
    [<Extension>]
    static member WithActions(record: ExportedGame, value: seq<ActionDef>) : ExportedGame = { record with Actions = List.ofSeq value }
    [<Extension>]
    static member WithMinigames(record: ExportedGame, value: seq<MinigameDef>) : ExportedGame = { record with Minigames = List.ofSeq value }
    [<Extension>]
    static member WithContentPacks(record: ExportedGame, value: seq<PackInstallation>) : ExportedGame = { record with ContentPacks = List.ofSeq value }
    [<Extension>]
    static member WithPlayer(record: ExportedGame, value: Player | null) : ExportedGame = { record with Player = Option.ofObj value }
    [<Extension>]
    static member WithCurrentWeatherId(record: ExportedGame, value: string | null) : ExportedGame = { record with CurrentWeatherId = Option.ofObj value }
    [<Extension>]
    static member WithSocialState(record: ExportedGame, value: seq<(string * NpcSocialState)> | null) : ExportedGame = { record with SocialState = (match value with null -> None | items -> Some(List.ofSeq items)) }
    [<Extension>]
    static member WithMineDeepestFloor(record: ExportedGame, value: Nullable<float>) : ExportedGame = { record with MineDeepestFloor = Option.ofNullable value }
    [<Extension>]
    static member WithQuarantinedItems(record: ExportedGame, value: seq<InventorySlot> | null) : ExportedGame = { record with QuarantinedItems = (match value with null -> None | items -> Some(List.ofSeq items)) }
    [<Extension>]
    static member WithFestivalId(record: FestivalIdCondition, value: string) : FestivalIdCondition = { record with FestivalId = value }
    [<Extension>]
    static member WithId(record: FishTable, value: string) : FishTable = { record with Id = value }
    [<Extension>]
    static member WithName(record: FishTable, value: string) : FishTable = { record with Name = value }
    [<Extension>]
    static member WithSeasons(record: FishTable, value: seq<string> | null) : FishTable = { record with Seasons = (match value with null -> None | items -> Some(List.ofSeq items)) }
    [<Extension>]
    static member WithSceneIds(record: FishTable, value: seq<string> | null) : FishTable = { record with SceneIds = (match value with null -> None | items -> Some(List.ofSeq items)) }
    [<Extension>]
    static member WithEntries(record: FishTable, value: seq<FishTableEntry>) : FishTable = { record with Entries = List.ofSeq value }
    [<Extension>]
    static member WithJunkChance(record: FishTable, value: float) : FishTable = { record with JunkChance = value }
    [<Extension>]
    static member WithJunkItemId(record: FishTable, value: string | null) : FishTable = { record with JunkItemId = Option.ofObj value }
    [<Extension>]
    static member WithItemId(record: FishTableEntry, value: string) : FishTableEntry = { record with ItemId = value }
    [<Extension>]
    static member WithWeight(record: FishTableEntry, value: float) : FishTableEntry = { record with Weight = value }
    [<Extension>]
    static member WithDifficulty(record: FishTableEntry, value: float) : FishTableEntry = { record with Difficulty = value }
    [<Extension>]
    static member WithFlag(record: FlagCondition, value: string) : FlagCondition = { record with Flag = value }
    [<Extension>]
    static member WithValue(record: FlagCondition, value: bool) : FlagCondition = { record with Value = value }
    [<Extension>]
    static member WithNpcId(record: FriendshipCondition, value: string) : FriendshipCondition = { record with NpcId = value }
    [<Extension>]
    static member WithMin(record: FriendshipCondition, value: float) : FriendshipCondition = { record with Min = value }
    [<Extension>]
    static member WithContentVersion(record: GameContent, value: float) : GameContent = { record with ContentVersion = value }
    [<Extension>]
    static member WithCrops(record: GameContent, value: ((string * CropDefinition) list)) : GameContent = { record with Crops = value }
    [<Extension>]
    static member WithCrops(record: GameContent, value: seq<KeyValuePair<string, CropDefinition>>) : GameContent = { record with Crops = [ for pair in value -> pair.Key, pair.Value ] }
    [<Extension>]
    static member WithItems(record: GameContent, value: seq<Item>) : GameContent = { record with Items = List.ofSeq value }
    [<Extension>]
    static member WithNpcs(record: GameContent, value: seq<Npc>) : GameContent = { record with Npcs = List.ofSeq value }
    [<Extension>]
    static member WithDialogues(record: GameContent, value: seq<Dialogue>) : GameContent = { record with Dialogues = List.ofSeq value }
    [<Extension>]
    static member WithQuests(record: GameContent, value: seq<Quest>) : GameContent = { record with Quests = List.ofSeq value }
    [<Extension>]
    static member WithEvents(record: GameContent, value: seq<GameEvent>) : GameContent = { record with Events = List.ofSeq value }
    [<Extension>]
    static member WithShops(record: GameContent, value: seq<ShopDefinition>) : GameContent = { record with Shops = List.ofSeq value }
    [<Extension>]
    static member WithNodeTypes(record: GameContent, value: seq<NodeTypeDefinition>) : GameContent = { record with NodeTypes = List.ofSeq value }
    [<Extension>]
    static member WithSettings(record: GameContent, value: ProjectSettings) : GameContent = { record with Settings = value }
    [<Extension>]
    static member WithRecipes(record: GameContent, value: seq<RecipeDefinition>) : GameContent = { record with Recipes = List.ofSeq value }
    [<Extension>]
    static member WithMachineTypes(record: GameContent, value: seq<MachineTypeDefinition>) : GameContent = { record with MachineTypes = List.ofSeq value }
    [<Extension>]
    static member WithWeather(record: GameContent, value: WeatherConfig) : GameContent = { record with Weather = value }
    [<Extension>]
    static member WithAnimalSpecies(record: GameContent, value: seq<AnimalSpeciesDefinition>) : GameContent = { record with AnimalSpecies = List.ofSeq value }
    [<Extension>]
    static member WithFishTables(record: GameContent, value: seq<FishTable>) : GameContent = { record with FishTables = List.ofSeq value }
    [<Extension>]
    static member WithMine(record: GameContent, value: MineConfig) : GameContent = { record with Mine = value }
    [<Extension>]
    static member WithActions(record: GameContent, value: seq<ActionDef>) : GameContent = { record with Actions = List.ofSeq value }
    [<Extension>]
    static member WithMinigames(record: GameContent, value: seq<MinigameDef>) : GameContent = { record with Minigames = List.ofSeq value }
    [<Extension>]
    static member WithScenes(record: GameContent, value: seq<Scene>) : GameContent = { record with Scenes = List.ofSeq value }
    [<Extension>]
    static member WithStartSceneId(record: GameContent, value: string) : GameContent = { record with StartSceneId = value }
    [<Extension>]
    static member WithId(record: GameEvent, value: string) : GameEvent = { record with Id = value }
    [<Extension>]
    static member WithName(record: GameEvent, value: string) : GameEvent = { record with Name = value }
    [<Extension>]
    static member WithSceneId(record: GameEvent, value: string) : GameEvent = { record with SceneId = value }
    [<Extension>]
    static member WithTrigger(record: GameEvent, value: string) : GameEvent = { record with Trigger = value }
    [<Extension>]
    static member WithConditions(record: GameEvent, value: seq<EventCondition>) : GameEvent = { record with Conditions = List.ofSeq value }
    [<Extension>]
    static member WithOutcomes(record: GameEvent, value: seq<EventOutcome>) : GameEvent = { record with Outcomes = List.ofSeq value }
    [<Extension>]
    static member WithActive(record: GameEvent, value: bool) : GameEvent = { record with Active = value }
    [<Extension>]
    static member WithRepeatable(record: GameEvent, value: bool) : GameEvent = { record with Repeatable = value }
    [<Extension>]
    static member WithId(record: GamePanel, value: string) : GamePanel = { record with Id = value }
    [<Extension>]
    static member WithTitle(record: GamePanel, value: string) : GamePanel = { record with Title = value }
    [<Extension>]
    static member WithVisibleFlag(record: GamePanel, value: string | null) : GamePanel = { record with VisibleFlag = Option.ofObj value }
    [<Extension>]
    static member WithEntries(record: GamePanel, value: seq<GamePanelEntry>) : GamePanel = { record with Entries = List.ofSeq value }
    [<Extension>]
    static member WithLabel(record: GamePanelEntry, value: string) : GamePanelEntry = { record with Label = value }
    [<Extension>]
    static member WithKind(record: GamePanelEntry, value: string) : GamePanelEntry = { record with Kind = value }
    [<Extension>]
    static member WithValue(record: GamePanelEntry, value: string) : GamePanelEntry = { record with Value = value }
    [<Extension>]
    static member WithSchemaVersion(record: GameProject, value: float) : GameProject = { record with SchemaVersion = value }
    [<Extension>]
    static member WithId(record: GameProject, value: string) : GameProject = { record with Id = value }
    [<Extension>]
    static member WithName(record: GameProject, value: string) : GameProject = { record with Name = value }
    [<Extension>]
    static member WithVersion(record: GameProject, value: string) : GameProject = { record with Version = value }
    [<Extension>]
    static member WithScenes(record: GameProject, value: seq<Scene>) : GameProject = { record with Scenes = List.ofSeq value }
    [<Extension>]
    static member WithNpcs(record: GameProject, value: seq<Npc>) : GameProject = { record with Npcs = List.ofSeq value }
    [<Extension>]
    static member WithItems(record: GameProject, value: seq<Item>) : GameProject = { record with Items = List.ofSeq value }
    [<Extension>]
    static member WithEvents(record: GameProject, value: seq<GameEvent>) : GameProject = { record with Events = List.ofSeq value }
    [<Extension>]
    static member WithDialogues(record: GameProject, value: seq<Dialogue>) : GameProject = { record with Dialogues = List.ofSeq value }
    [<Extension>]
    static member WithQuests(record: GameProject, value: seq<Quest>) : GameProject = { record with Quests = List.ofSeq value }
    [<Extension>]
    static member WithPlayer(record: GameProject, value: Player) : GameProject = { record with Player = value }
    [<Extension>]
    static member WithEventFlags(record: GameProject, value: ((string * bool) list)) : GameProject = { record with EventFlags = value }
    [<Extension>]
    static member WithEventFlags(record: GameProject, value: seq<KeyValuePair<string, bool>>) : GameProject = { record with EventFlags = [ for pair in value -> pair.Key, pair.Value ] }
    [<Extension>]
    static member WithStartSceneId(record: GameProject, value: string) : GameProject = { record with StartSceneId = value }
    [<Extension>]
    static member WithMode(record: GameProject, value: string) : GameProject = { record with Mode = value }
    [<Extension>]
    static member WithSelectedTileType(record: GameProject, value: string) : GameProject = { record with SelectedTileType = value }
    [<Extension>]
    static member WithSelectedTileVisual(record: GameProject, value: VisualRef | null) : GameProject = { record with SelectedTileVisual = Option.ofObj value }
    [<Extension>]
    static member WithSelectedNpcId(record: GameProject, value: string | null) : GameProject = { record with SelectedNpcId = Option.ofObj value }
    [<Extension>]
    static member WithSelectedItemId(record: GameProject, value: string | null) : GameProject = { record with SelectedItemId = Option.ofObj value }
    [<Extension>]
    static member WithCurrentTime(record: GameProject, value: float) : GameProject = { record with CurrentTime = value }
    [<Extension>]
    static member WithCustomAssets(record: GameProject, value: seq<CustomAsset>) : GameProject = { record with CustomAssets = List.ofSeq value }
    [<Extension>]
    static member WithCustomCrops(record: GameProject, value: seq<CustomCropDefinition> | null) : GameProject = { record with CustomCrops = (match value with null -> None | items -> Some(List.ofSeq items)) }
    [<Extension>]
    static member WithPlayerCustomImage(record: GameProject, value: string | null) : GameProject = { record with PlayerCustomImage = Option.ofObj value }
    [<Extension>]
    static member WithPlayerVisual(record: GameProject, value: VisualRef | null) : GameProject = { record with PlayerVisual = Option.ofObj value }
    [<Extension>]
    static member WithGraphics(record: GameProject, value: GraphicsSettings | null) : GameProject = { record with Graphics = Option.ofObj value }
    [<Extension>]
    static member WithGamePanels(record: GameProject, value: seq<GamePanel> | null) : GameProject = { record with GamePanels = (match value with null -> None | items -> Some(List.ofSeq items)) }
    [<Extension>]
    static member WithCurrentSeason(record: GameProject, value: string) : GameProject = { record with CurrentSeason = value }
    [<Extension>]
    static member WithCurrentDay(record: GameProject, value: float) : GameProject = { record with CurrentDay = value }
    [<Extension>]
    static member WithCurrentTimeMinutes(record: GameProject, value: float) : GameProject = { record with CurrentTimeMinutes = value }
    [<Extension>]
    static member WithCurrentYear(record: GameProject, value: float) : GameProject = { record with CurrentYear = value }
    [<Extension>]
    static member WithGameStartTime(record: GameProject, value: float) : GameProject = { record with GameStartTime = value }
    [<Extension>]
    static member WithShops(record: GameProject, value: seq<ShopDefinition>) : GameProject = { record with Shops = List.ofSeq value }
    [<Extension>]
    static member WithNodeTypes(record: GameProject, value: seq<NodeTypeDefinition>) : GameProject = { record with NodeTypes = List.ofSeq value }
    [<Extension>]
    static member WithSettings(record: GameProject, value: ProjectSettings) : GameProject = { record with Settings = value }
    [<Extension>]
    static member WithRecipes(record: GameProject, value: seq<RecipeDefinition>) : GameProject = { record with Recipes = List.ofSeq value }
    [<Extension>]
    static member WithMachineTypes(record: GameProject, value: seq<MachineTypeDefinition>) : GameProject = { record with MachineTypes = List.ofSeq value }
    [<Extension>]
    static member WithWeather(record: GameProject, value: WeatherConfig) : GameProject = { record with Weather = value }
    [<Extension>]
    static member WithAnimalSpecies(record: GameProject, value: seq<AnimalSpeciesDefinition>) : GameProject = { record with AnimalSpecies = List.ofSeq value }
    [<Extension>]
    static member WithAnimals(record: GameProject, value: seq<AnimalState>) : GameProject = { record with Animals = List.ofSeq value }
    [<Extension>]
    static member WithFishTables(record: GameProject, value: seq<FishTable>) : GameProject = { record with FishTables = List.ofSeq value }
    [<Extension>]
    static member WithMine(record: GameProject, value: MineConfig) : GameProject = { record with Mine = value }
    [<Extension>]
    static member WithActions(record: GameProject, value: seq<ActionDef>) : GameProject = { record with Actions = List.ofSeq value }
    [<Extension>]
    static member WithMinigames(record: GameProject, value: seq<MinigameDef>) : GameProject = { record with Minigames = List.ofSeq value }
    [<Extension>]
    static member WithContentPacks(record: GameProject, value: seq<PackInstallation>) : GameProject = { record with ContentPacks = List.ofSeq value }
    [<Extension>]
    static member WithExport(record: GameProject, value: ExportSettings | null) : GameProject = { record with Export = Option.ofObj value }
    [<Extension>]
    static member WithRngState(record: GameProject, value: RngState | null) : GameProject = { record with RngState = Option.ofObj value }
    [<Extension>]
    static member WithCurrentWeatherId(record: GameProject, value: string | null) : GameProject = { record with CurrentWeatherId = Option.ofObj value }
    [<Extension>]
    static member WithSocialState(record: GameProject, value: seq<(string * NpcSocialState)> | null) : GameProject = { record with SocialState = (match value with null -> None | items -> Some(List.ofSeq items)) }
    [<Extension>]
    static member WithMineDeepestFloor(record: GameProject, value: Nullable<float>) : GameProject = { record with MineDeepestFloor = Option.ofNullable value }
    [<Extension>]
    static member WithQuarantinedItems(record: GameProject, value: seq<InventorySlot> | null) : GameProject = { record with QuarantinedItems = (match value with null -> None | items -> Some(List.ofSeq items)) }
    [<Extension>]
    static member WithLoved(record: GiftTastes, value: seq<string>) : GiftTastes = { record with Loved = List.ofSeq value }
    [<Extension>]
    static member WithLiked(record: GiftTastes, value: seq<string>) : GiftTastes = { record with Liked = List.ofSeq value }
    [<Extension>]
    static member WithDisliked(record: GiftTastes, value: seq<string>) : GiftTastes = { record with Disliked = List.ofSeq value }
    [<Extension>]
    static member WithHated(record: GiftTastes, value: seq<string>) : GiftTastes = { record with Hated = List.ofSeq value }
    [<Extension>]
    static member WithPixelArt(record: GraphicsSettings, value: bool) : GraphicsSettings = { record with PixelArt = value }
    [<Extension>]
    static member WithX(record: GridPoint, value: float) : GridPoint = { record with X = value }
    [<Extension>]
    static member WithY(record: GridPoint, value: float) : GridPoint = { record with Y = value }
    [<Extension>]
    static member WithItemId(record: HasItemCondition, value: string) : HasItemCondition = { record with ItemId = value }
    [<Extension>]
    static member WithQuantity(record: HasItemCondition, value: float) : HasItemCondition = { record with Quantity = value }
    [<Extension>]
    static member WithX(record: InteractTileCondition, value: float) : InteractTileCondition = { record with X = value }
    [<Extension>]
    static member WithY(record: InteractTileCondition, value: float) : InteractTileCondition = { record with Y = value }
    [<Extension>]
    static member WithX2(record: InteractTileCondition, value: Nullable<float>) : InteractTileCondition = { record with X2 = Option.ofNullable value }
    [<Extension>]
    static member WithY2(record: InteractTileCondition, value: Nullable<float>) : InteractTileCondition = { record with Y2 = Option.ofNullable value }
    [<Extension>]
    static member WithItem(record: InventorySlot, value: Item) : InventorySlot = { record with Item = value }
    [<Extension>]
    static member WithQuantity(record: InventorySlot, value: float) : InventorySlot = { record with Quantity = value }
    [<Extension>]
    static member WithItemId(record: InventorySpaceCondition, value: string) : InventorySpaceCondition = { record with ItemId = value }
    [<Extension>]
    static member WithQuantity(record: InventorySpaceCondition, value: float) : InventorySpaceCondition = { record with Quantity = value }
    [<Extension>]
    static member WithId(record: Item, value: string) : Item = { record with Id = value }
    [<Extension>]
    static member WithName(record: Item, value: string) : Item = { record with Name = value }
    [<Extension>]
    static member WithVisual(record: Item, value: VisualRef | null) : Item = { record with Visual = Option.ofObj value }
    [<Extension>]
    static member WithDescription(record: Item, value: string) : Item = { record with Description = value }
    [<Extension>]
    static member WithType(record: Item, value: string) : Item = { record with Type = value }
    [<Extension>]
    static member WithStackable(record: Item, value: bool) : Item = { record with Stackable = value }
    [<Extension>]
    static member WithMaxStack(record: Item, value: float) : Item = { record with MaxStack = value }
    [<Extension>]
    static member WithValue(record: Item, value: float) : Item = { record with Value = value }
    [<Extension>]
    static member WithCropType(record: Item, value: string | null) : Item = { record with CropType = Option.ofObj value }
    [<Extension>]
    static member WithCustomImage(record: Item, value: string | null) : Item = { record with CustomImage = Option.ofObj value }
    [<Extension>]
    static member WithToolType(record: Item, value: string | null) : Item = { record with ToolType = Option.ofObj value }
    [<Extension>]
    static member WithToolPower(record: Item, value: Nullable<float>) : Item = { record with ToolPower = Option.ofNullable value }
    [<Extension>]
    static member WithToolTier(record: Item, value: Nullable<float>) : Item = { record with ToolTier = Option.ofNullable value }
    [<Extension>]
    static member WithDurability(record: Item, value: Nullable<float>) : Item = { record with Durability = Option.ofNullable value }
    [<Extension>]
    static member WithMaxDurability(record: Item, value: Nullable<float>) : Item = { record with MaxDurability = Option.ofNullable value }
    [<Extension>]
    static member WithUseActionId(record: Item, value: string | null) : Item = { record with UseActionId = Option.ofObj value }
    [<Extension>]
    static member WithConsumeOnUse(record: Item, value: Nullable<bool>) : Item = { record with ConsumeOnUse = Option.ofNullable value }
    [<Extension>]
    static member WithRecipeId(record: MachineProcessing, value: string) : MachineProcessing = { record with RecipeId = value }
    [<Extension>]
    static member WithCompletesAtMinute(record: MachineProcessing, value: float) : MachineProcessing = { record with CompletesAtMinute = value }
    [<Extension>]
    static member WithId(record: MachineTypeDefinition, value: string) : MachineTypeDefinition = { record with Id = value }
    [<Extension>]
    static member WithName(record: MachineTypeDefinition, value: string) : MachineTypeDefinition = { record with Name = value }
    [<Extension>]
    static member WithVisual(record: MachineTypeDefinition, value: VisualRef | null) : MachineTypeDefinition = { record with Visual = Option.ofObj value }
    [<Extension>]
    static member WithDescription(record: MachineTypeDefinition, value: string) : MachineTypeDefinition = { record with Description = value }
    [<Extension>]
    static member WithColor(record: MachineTypeDefinition, value: string) : MachineTypeDefinition = { record with Color = value }
    [<Extension>]
    static member WithItemId(record: MachineTypeDefinition, value: string | null) : MachineTypeDefinition = { record with ItemId = Option.ofObj value }
    [<Extension>]
    static member WithBlocksMovement(record: MachineTypeDefinition, value: bool) : MachineTypeDefinition = { record with BlocksMovement = value }
    [<Extension>]
    static member WithStationCategories(record: MachineTypeDefinition, value: seq<string>) : MachineTypeDefinition = { record with StationCategories = List.ofSeq value }
    [<Extension>]
    static member WithFromFloor(record: MineBand, value: float) : MineBand = { record with FromFloor = value }
    [<Extension>]
    static member WithToFloor(record: MineBand, value: float) : MineBand = { record with ToFloor = value }
    [<Extension>]
    static member WithRocks(record: MineBand, value: seq<MineRockWeight>) : MineBand = { record with Rocks = List.ofSeq value }
    [<Extension>]
    static member WithDensity(record: MineBand, value: float) : MineBand = { record with Density = value }
    [<Extension>]
    static member WithEnabled(record: MineConfig, value: bool) : MineConfig = { record with Enabled = value }
    [<Extension>]
    static member WithEntranceSceneId(record: MineConfig, value: string | null) : MineConfig = { record with EntranceSceneId = Option.ofObj value }
    [<Extension>]
    static member WithEntranceX(record: MineConfig, value: Nullable<float>) : MineConfig = { record with EntranceX = Option.ofNullable value }
    [<Extension>]
    static member WithEntranceY(record: MineConfig, value: Nullable<float>) : MineConfig = { record with EntranceY = Option.ofNullable value }
    [<Extension>]
    static member WithFloors(record: MineConfig, value: float) : MineConfig = { record with Floors = value }
    [<Extension>]
    static member WithFloorWidth(record: MineConfig, value: float) : MineConfig = { record with FloorWidth = value }
    [<Extension>]
    static member WithFloorHeight(record: MineConfig, value: float) : MineConfig = { record with FloorHeight = value }
    [<Extension>]
    static member WithBands(record: MineConfig, value: seq<MineBand>) : MineConfig = { record with Bands = List.ofSeq value }
    [<Extension>]
    static member WithLadderChance(record: MineConfig, value: float) : MineConfig = { record with LadderChance = value }
    [<Extension>]
    static member WithElevatorEvery(record: MineConfig, value: float) : MineConfig = { record with ElevatorEvery = value }
    [<Extension>]
    static member WithNodeTypeId(record: MineRockWeight, value: string) : MineRockWeight = { record with NodeTypeId = value }
    [<Extension>]
    static member WithWeight(record: MineRockWeight, value: float) : MineRockWeight = { record with Weight = value }
    [<Extension>]
    static member WithId(record: MinigameDef, value: string) : MinigameDef = { record with Id = value }
    [<Extension>]
    static member WithName(record: MinigameDef, value: string) : MinigameDef = { record with Name = value }
    [<Extension>]
    static member WithKind(record: MinigameDef, value: string) : MinigameDef = { record with Kind = value }
    [<Extension>]
    static member WithConfig(record: MinigameDef, value: ((string * Json) list)) : MinigameDef = { record with Config = value }
    [<Extension>]
    static member WithConfig(record: MinigameDef, value: seq<KeyValuePair<string, Json>>) : MinigameDef = { record with Config = [ for pair in value -> pair.Key, pair.Value ] }
    [<Extension>]
    static member WithResultTiers(record: MinigameDef, value: seq<MinigameResultTier>) : MinigameDef = { record with ResultTiers = List.ofSeq value }
    [<Extension>]
    static member WithMinScore(record: MinigameResultTier, value: float) : MinigameResultTier = { record with MinScore = value }
    [<Extension>]
    static member WithOutcomes(record: MinigameResultTier, value: seq<EventOutcome>) : MinigameResultTier = { record with Outcomes = List.ofSeq value }
    [<Extension>]
    static member WithPlayerSpeed(record: MovementConfig, value: float) : MovementConfig = { record with PlayerSpeed = value }
    [<Extension>]
    static member WithItemId(record: NodeDrop, value: string) : NodeDrop = { record with ItemId = value }
    [<Extension>]
    static member WithMin(record: NodeDrop, value: float) : NodeDrop = { record with Min = value }
    [<Extension>]
    static member WithMax(record: NodeDrop, value: float) : NodeDrop = { record with Max = value }
    [<Extension>]
    static member WithWeight(record: NodeDrop, value: float) : NodeDrop = { record with Weight = value }
    [<Extension>]
    static member WithId(record: NodeTypeDefinition, value: string) : NodeTypeDefinition = { record with Id = value }
    [<Extension>]
    static member WithName(record: NodeTypeDefinition, value: string) : NodeTypeDefinition = { record with Name = value }
    [<Extension>]
    static member WithVisual(record: NodeTypeDefinition, value: VisualRef | null) : NodeTypeDefinition = { record with Visual = Option.ofObj value }
    [<Extension>]
    static member WithHealth(record: NodeTypeDefinition, value: float) : NodeTypeDefinition = { record with Health = value }
    [<Extension>]
    static member WithRequiredTool(record: NodeTypeDefinition, value: string) : NodeTypeDefinition = { record with RequiredTool = value }
    [<Extension>]
    static member WithRequiredToolTier(record: NodeTypeDefinition, value: float) : NodeTypeDefinition = { record with RequiredToolTier = value }
    [<Extension>]
    static member WithDrops(record: NodeTypeDefinition, value: seq<NodeDrop>) : NodeTypeDefinition = { record with Drops = List.ofSeq value }
    [<Extension>]
    static member WithRespawnDays(record: NodeTypeDefinition, value: ((float option) option)) : NodeTypeDefinition = { record with RespawnDays = value }
    [<Extension>]
    static member WithColor(record: NodeTypeDefinition, value: string) : NodeTypeDefinition = { record with Color = value }
    [<Extension>]
    static member WithBlocksMovement(record: NodeTypeDefinition, value: bool) : NodeTypeDefinition = { record with BlocksMovement = value }
    [<Extension>]
    static member WithId(record: Npc, value: string) : Npc = { record with Id = value }
    [<Extension>]
    static member WithName(record: Npc, value: string) : Npc = { record with Name = value }
    [<Extension>]
    static member WithVisual(record: Npc, value: VisualRef | null) : Npc = { record with Visual = Option.ofObj value }
    [<Extension>]
    static member WithX(record: Npc, value: float) : Npc = { record with X = value }
    [<Extension>]
    static member WithY(record: Npc, value: float) : Npc = { record with Y = value }
    [<Extension>]
    static member WithSceneId(record: Npc, value: string) : Npc = { record with SceneId = value }
    [<Extension>]
    static member WithDialogue(record: Npc, value: seq<Dialogue>) : Npc = { record with Dialogue = List.ofSeq value }
    [<Extension>]
    static member WithCanMove(record: Npc, value: bool) : Npc = { record with CanMove = value }
    [<Extension>]
    static member WithMovePattern(record: Npc, value: string | null) : Npc = { record with MovePattern = Option.ofObj value }
    [<Extension>]
    static member WithWanderRadius(record: Npc, value: Nullable<float>) : Npc = { record with WanderRadius = Option.ofNullable value }
    [<Extension>]
    static member WithPatrolPoints(record: Npc, value: seq<GridPoint> | null) : Npc = { record with PatrolPoints = (match value with null -> None | items -> Some(List.ofSeq items)) }
    [<Extension>]
    static member WithSchedule(record: Npc, value: seq<NpcScheduleEntry> | null) : Npc = { record with Schedule = (match value with null -> None | items -> Some(List.ofSeq items)) }
    [<Extension>]
    static member WithGiftTastes(record: Npc, value: GiftTastes | null) : Npc = { record with GiftTastes = Option.ofObj value }
    [<Extension>]
    static member WithBirthday(record: Npc, value: NpcBirthday | null) : Npc = { record with Birthday = Option.ofObj value }
    [<Extension>]
    static member WithAppearance(record: Npc, value: string) : Npc = { record with Appearance = value }
    [<Extension>]
    static member WithCustomImage(record: Npc, value: string | null) : Npc = { record with CustomImage = Option.ofObj value }
    [<Extension>]
    static member WithSeason(record: NpcBirthday, value: string) : NpcBirthday = { record with Season = value }
    [<Extension>]
    static member WithDay(record: NpcBirthday, value: float) : NpcBirthday = { record with Day = value }
    [<Extension>]
    static member WithMinute(record: NpcScheduleEntry, value: float) : NpcScheduleEntry = { record with Minute = value }
    [<Extension>]
    static member WithSceneId(record: NpcScheduleEntry, value: string) : NpcScheduleEntry = { record with SceneId = value }
    [<Extension>]
    static member WithX(record: NpcScheduleEntry, value: float) : NpcScheduleEntry = { record with X = value }
    [<Extension>]
    static member WithY(record: NpcScheduleEntry, value: float) : NpcScheduleEntry = { record with Y = value }
    [<Extension>]
    static member WithFriendship(record: NpcSocialState, value: float) : NpcSocialState = { record with Friendship = value }
    [<Extension>]
    static member WithGiftsToday(record: NpcSocialState, value: float) : NpcSocialState = { record with GiftsToday = value }
    [<Extension>]
    static member WithLastGiftDay(record: NpcSocialState, value: Nullable<float>) : NpcSocialState = { record with LastGiftDay = Option.ofNullable value }
    [<Extension>]
    static member WithCrops(record: PackContent, value: seq<CropDefinition>) : PackContent = { record with Crops = List.ofSeq value }
    [<Extension>]
    static member WithItems(record: PackContent, value: seq<Item>) : PackContent = { record with Items = List.ofSeq value }
    [<Extension>]
    static member WithRecipes(record: PackContent, value: seq<RecipeDefinition>) : PackContent = { record with Recipes = List.ofSeq value }
    [<Extension>]
    static member WithMachineTypes(record: PackContent, value: seq<MachineTypeDefinition>) : PackContent = { record with MachineTypes = List.ofSeq value }
    [<Extension>]
    static member WithNodeTypes(record: PackContent, value: seq<NodeTypeDefinition>) : PackContent = { record with NodeTypes = List.ofSeq value }
    [<Extension>]
    static member WithAnimalSpecies(record: PackContent, value: seq<AnimalSpeciesDefinition>) : PackContent = { record with AnimalSpecies = List.ofSeq value }
    [<Extension>]
    static member WithFishTables(record: PackContent, value: seq<FishTable>) : PackContent = { record with FishTables = List.ofSeq value }
    [<Extension>]
    static member WithWeatherTypes(record: PackContent, value: seq<WeatherTypeDefinition>) : PackContent = { record with WeatherTypes = List.ofSeq value }
    [<Extension>]
    static member WithNpcs(record: PackContent, value: seq<Npc>) : PackContent = { record with Npcs = List.ofSeq value }
    [<Extension>]
    static member WithDialogues(record: PackContent, value: seq<Dialogue>) : PackContent = { record with Dialogues = List.ofSeq value }
    [<Extension>]
    static member WithScenes(record: PackContent, value: seq<Scene>) : PackContent = { record with Scenes = List.ofSeq value }
    [<Extension>]
    static member WithEvents(record: PackContent, value: seq<GameEvent>) : PackContent = { record with Events = List.ofSeq value }
    [<Extension>]
    static member WithQuests(record: PackContent, value: seq<Quest>) : PackContent = { record with Quests = List.ofSeq value }
    [<Extension>]
    static member WithShops(record: PackContent, value: seq<ShopDefinition>) : PackContent = { record with Shops = List.ofSeq value }
    [<Extension>]
    static member WithActions(record: PackContent, value: seq<ActionDef>) : PackContent = { record with Actions = List.ofSeq value }
    [<Extension>]
    static member WithMinigames(record: PackContent, value: seq<MinigameDef>) : PackContent = { record with Minigames = List.ofSeq value }
    [<Extension>]
    static member WithPlayerStart(record: PackContent, value: PackPlayerStart | null) : PackContent = { record with PlayerStart = Option.ofObj value }
    [<Extension>]
    static member WithStrings(record: PackContent, value: ((string * ((string * string) list)) list)) : PackContent = { record with Strings = value }
    [<Extension>]
    static member WithStrings(record: PackContent, value: seq<KeyValuePair<string, ((string * string) list)>>) : PackContent = { record with Strings = [ for pair in value -> pair.Key, pair.Value ] }
    [<Extension>]
    static member WithPackId(record: PackDependency, value: string) : PackDependency = { record with PackId = value }
    [<Extension>]
    static member WithVersion(record: PackDependency, value: string | null) : PackDependency = { record with Version = Option.ofObj value }
    [<Extension>]
    static member WithPack(record: PackInstallation, value: ContentPack) : PackInstallation = { record with Pack = value }
    [<Extension>]
    static member WithEnabled(record: PackInstallation, value: bool) : PackInstallation = { record with Enabled = value }
    [<Extension>]
    static member WithId(record: PackManifest, value: string) : PackManifest = { record with Id = value }
    [<Extension>]
    static member WithName(record: PackManifest, value: string) : PackManifest = { record with Name = value }
    [<Extension>]
    static member WithVersion(record: PackManifest, value: string) : PackManifest = { record with Version = value }
    [<Extension>]
    static member WithDescription(record: PackManifest, value: string | null) : PackManifest = { record with Description = Option.ofObj value }
    [<Extension>]
    static member WithAuthor(record: PackManifest, value: string | null) : PackManifest = { record with Author = Option.ofObj value }
    [<Extension>]
    static member WithEngineCompatibility(record: PackManifest, value: string) : PackManifest = { record with EngineCompatibility = value }
    [<Extension>]
    static member WithBase(record: PackManifest, value: bool) : PackManifest = { record with Base = value }
    [<Extension>]
    static member WithDependencies(record: PackManifest, value: seq<PackDependency>) : PackManifest = { record with Dependencies = List.ofSeq value }
    [<Extension>]
    static member WithOverrides(record: PackManifest, value: seq<string>) : PackManifest = { record with Overrides = List.ofSeq value }
    [<Extension>]
    static member WithPermissions(record: PackManifest, value: PackPermissions) : PackManifest = { record with Permissions = value }
    [<Extension>]
    static member WithHooks(record: PackPermissions, value: seq<string>) : PackPermissions = { record with Hooks = List.ofSeq value }
    [<Extension>]
    static member WithContentInject(record: PackPermissions, value: bool) : PackPermissions = { record with ContentInject = value }
    [<Extension>]
    static member WithUiPanels(record: PackPermissions, value: bool) : PackPermissions = { record with UiPanels = value }
    [<Extension>]
    static member WithSceneId(record: PackPlayerStart, value: string | null) : PackPlayerStart = { record with SceneId = Option.ofObj value }
    [<Extension>]
    static member WithX(record: PackPlayerStart, value: Nullable<float>) : PackPlayerStart = { record with X = Option.ofNullable value }
    [<Extension>]
    static member WithY(record: PackPlayerStart, value: Nullable<float>) : PackPlayerStart = { record with Y = Option.ofNullable value }
    [<Extension>]
    static member WithMoney(record: PackPlayerStart, value: Nullable<float>) : PackPlayerStart = { record with Money = Option.ofNullable value }
    [<Extension>]
    static member WithInventory(record: PackPlayerStart, value: seq<PackStartItem>) : PackPlayerStart = { record with Inventory = List.ofSeq value }
    [<Extension>]
    static member WithId(record: PackPlugin, value: string) : PackPlugin = { record with Id = value }
    [<Extension>]
    static member WithName(record: PackPlugin, value: string | null) : PackPlugin = { record with Name = Option.ofObj value }
    [<Extension>]
    static member WithHooks(record: PackPlugin, value: seq<string>) : PackPlugin = { record with Hooks = List.ofSeq value }
    [<Extension>]
    static member WithSource(record: PackPlugin, value: string) : PackPlugin = { record with Source = value }
    [<Extension>]
    static member WithItemId(record: PackStartItem, value: string) : PackStartItem = { record with ItemId = value }
    [<Extension>]
    static member WithQuantity(record: PackStartItem, value: float) : PackStartItem = { record with Quantity = value }
    [<Extension>]
    static member WithX(record: Player, value: float) : Player = { record with X = value }
    [<Extension>]
    static member WithY(record: Player, value: float) : Player = { record with Y = value }
    [<Extension>]
    static member WithDirection(record: Player, value: string) : Player = { record with Direction = value }
    [<Extension>]
    static member WithSceneId(record: Player, value: string) : Player = { record with SceneId = value }
    [<Extension>]
    static member WithInventory(record: Player, value: seq<InventorySlot>) : Player = { record with Inventory = List.ofSeq value }
    [<Extension>]
    static member WithMaxInventorySize(record: Player, value: float) : Player = { record with MaxInventorySize = value }
    [<Extension>]
    static member WithMoney(record: Player, value: float) : Player = { record with Money = value }
    [<Extension>]
    static member WithEnergy(record: Player, value: Nullable<float>) : Player = { record with Energy = Option.ofNullable value }
    [<Extension>]
    static member WithMaxEnergy(record: Player, value: Nullable<float>) : Player = { record with MaxEnergy = Option.ofNullable value }
    [<Extension>]
    static member WithSkills(record: Player, value: seq<(string * SkillState)> | null) : Player = { record with Skills = (match value with null -> None | items -> Some(List.ofSeq items)) }
    [<Extension>]
    static member WithActiveQuests(record: Player, value: seq<string>) : Player = { record with ActiveQuests = List.ofSeq value }
    [<Extension>]
    static member WithCompletedQuests(record: Player, value: seq<string>) : Player = { record with CompletedQuests = List.ofSeq value }
    [<Extension>]
    static member WithEquippedTool(record: Player, value: string | null) : Player = { record with EquippedTool = Option.ofObj value }
    [<Extension>]
    static member WithPixelX(record: Player, value: float) : Player = { record with PixelX = value }
    [<Extension>]
    static member WithPixelY(record: Player, value: float) : Player = { record with PixelY = value }
    [<Extension>]
    static member WithTargetX(record: Player, value: float) : Player = { record with TargetX = value }
    [<Extension>]
    static member WithTargetY(record: Player, value: float) : Player = { record with TargetY = value }
    [<Extension>]
    static member WithMovement(record: ProjectSettings, value: MovementConfig) : ProjectSettings = { record with Movement = value }
    [<Extension>]
    static member WithEnergyEnabled(record: ProjectSettings, value: bool) : ProjectSettings = { record with EnergyEnabled = value }
    [<Extension>]
    static member WithMaxEnergy(record: ProjectSettings, value: float) : ProjectSettings = { record with MaxEnergy = value }
    [<Extension>]
    static member WithCollapseEnergyFraction(record: ProjectSettings, value: float) : ProjectSettings = { record with CollapseEnergyFraction = value }
    [<Extension>]
    static member WithCollapseMoneyPenalty(record: ProjectSettings, value: float) : ProjectSettings = { record with CollapseMoneyPenalty = value }
    [<Extension>]
    static member WithTime(record: ProjectSettings, value: TimeConfig) : ProjectSettings = { record with Time = value }
    [<Extension>]
    static member WithCalendar(record: ProjectSettings, value: CalendarConfig) : ProjectSettings = { record with Calendar = value }
    [<Extension>]
    static member WithSkillsEnabled(record: ProjectSettings, value: bool) : ProjectSettings = { record with SkillsEnabled = value }
    [<Extension>]
    static member WithSkillLevelCurve(record: ProjectSettings, value: seq<float>) : ProjectSettings = { record with SkillLevelCurve = List.ofSeq value }
    [<Extension>]
    static member WithLocale(record: ProjectSettings, value: string) : ProjectSettings = { record with Locale = value }
    [<Extension>]
    static member WithShowMadeWithCredit(record: ProjectSettings, value: bool) : ProjectSettings = { record with ShowMadeWithCredit = value }
    [<Extension>]
    static member WithId(record: Quest, value: string) : Quest = { record with Id = value }
    [<Extension>]
    static member WithName(record: Quest, value: string) : Quest = { record with Name = value }
    [<Extension>]
    static member WithDescription(record: Quest, value: string) : Quest = { record with Description = value }
    [<Extension>]
    static member WithGiver(record: Quest, value: string | null) : Quest = { record with Giver = Option.ofObj value }
    [<Extension>]
    static member WithStatus(record: Quest, value: string) : Quest = { record with Status = value }
    [<Extension>]
    static member WithObjectives(record: Quest, value: seq<QuestObjective>) : Quest = { record with Objectives = List.ofSeq value }
    [<Extension>]
    static member WithRewards(record: Quest, value: QuestRewards) : Quest = { record with Rewards = value }
    [<Extension>]
    static member WithPrerequisites(record: Quest, value: seq<string> | null) : Quest = { record with Prerequisites = (match value with null -> None | items -> Some(List.ofSeq items)) }
    [<Extension>]
    static member WithAutoStart(record: Quest, value: Nullable<bool>) : Quest = { record with AutoStart = Option.ofNullable value }
    [<Extension>]
    static member WithRepeatable(record: Quest, value: Nullable<bool>) : Quest = { record with Repeatable = Option.ofNullable value }
    [<Extension>]
    static member WithAvailableSeasons(record: Quest, value: seq<string> | null) : Quest = { record with AvailableSeasons = (match value with null -> None | items -> Some(List.ofSeq items)) }
    [<Extension>]
    static member WithAvailableFromDay(record: Quest, value: Nullable<float>) : Quest = { record with AvailableFromDay = Option.ofNullable value }
    [<Extension>]
    static member WithAvailableToDay(record: Quest, value: Nullable<float>) : Quest = { record with AvailableToDay = Option.ofNullable value }
    [<Extension>]
    static member WithId(record: QuestObjective, value: string) : QuestObjective = { record with Id = value }
    [<Extension>]
    static member WithType(record: QuestObjective, value: string) : QuestObjective = { record with Type = value }
    [<Extension>]
    static member WithDescription(record: QuestObjective, value: string) : QuestObjective = { record with Description = value }
    [<Extension>]
    static member WithTargetItemId(record: QuestObjective, value: string | null) : QuestObjective = { record with TargetItemId = Option.ofObj value }
    [<Extension>]
    static member WithTargetItemQuantity(record: QuestObjective, value: Nullable<float>) : QuestObjective = { record with TargetItemQuantity = Option.ofNullable value }
    [<Extension>]
    static member WithTargetCropType(record: QuestObjective, value: string | null) : QuestObjective = { record with TargetCropType = Option.ofObj value }
    [<Extension>]
    static member WithTargetCropQuantity(record: QuestObjective, value: Nullable<float>) : QuestObjective = { record with TargetCropQuantity = Option.ofNullable value }
    [<Extension>]
    static member WithTargetNpcId(record: QuestObjective, value: string | null) : QuestObjective = { record with TargetNpcId = Option.ofObj value }
    [<Extension>]
    static member WithTargetSceneId(record: QuestObjective, value: string | null) : QuestObjective = { record with TargetSceneId = Option.ofObj value }
    [<Extension>]
    static member WithCompleted(record: QuestObjective, value: bool) : QuestObjective = { record with Completed = value }
    [<Extension>]
    static member WithProgress(record: QuestObjective, value: float) : QuestObjective = { record with Progress = value }
    [<Extension>]
    static member WithItemId(record: QuestRewardItem, value: string) : QuestRewardItem = { record with ItemId = value }
    [<Extension>]
    static member WithQuantity(record: QuestRewardItem, value: float) : QuestRewardItem = { record with Quantity = value }
    [<Extension>]
    static member WithMoney(record: QuestRewards, value: Nullable<float>) : QuestRewards = { record with Money = Option.ofNullable value }
    [<Extension>]
    static member WithItems(record: QuestRewards, value: seq<QuestRewardItem> | null) : QuestRewards = { record with Items = (match value with null -> None | items -> Some(List.ofSeq items)) }
    [<Extension>]
    static member WithExperience(record: QuestRewards, value: Nullable<float>) : QuestRewards = { record with Experience = Option.ofNullable value }
    [<Extension>]
    static member WithQuestId(record: QuestStatusCondition, value: string) : QuestStatusCondition = { record with QuestId = value }
    [<Extension>]
    static member WithStatus(record: QuestStatusCondition, value: string) : QuestStatusCondition = { record with Status = value }
    [<Extension>]
    static member WithId(record: RecipeDefinition, value: string) : RecipeDefinition = { record with Id = value }
    [<Extension>]
    static member WithName(record: RecipeDefinition, value: string) : RecipeDefinition = { record with Name = value }
    [<Extension>]
    static member WithInputs(record: RecipeDefinition, value: seq<RecipeIngredient>) : RecipeDefinition = { record with Inputs = List.ofSeq value }
    [<Extension>]
    static member WithOutputs(record: RecipeDefinition, value: seq<RecipeIngredient>) : RecipeDefinition = { record with Outputs = List.ofSeq value }
    [<Extension>]
    static member WithProcessingMinutes(record: RecipeDefinition, value: float) : RecipeDefinition = { record with ProcessingMinutes = value }
    [<Extension>]
    static member WithMachineTypeId(record: RecipeDefinition, value: string | null) : RecipeDefinition = { record with MachineTypeId = Option.ofObj value }
    [<Extension>]
    static member WithCategory(record: RecipeDefinition, value: string) : RecipeDefinition = { record with Category = value }
    [<Extension>]
    static member WithRequiresStationCategory(record: RecipeDefinition, value: string | null) : RecipeDefinition = { record with RequiresStationCategory = Option.ofObj value }
    [<Extension>]
    static member WithUnlock(record: RecipeDefinition, value: RecipeUnlock | null) : RecipeDefinition = { record with Unlock = Option.ofObj value }
    [<Extension>]
    static member WithItemId(record: RecipeIngredient, value: string) : RecipeIngredient = { record with ItemId = value }
    [<Extension>]
    static member WithQuantity(record: RecipeIngredient, value: float) : RecipeIngredient = { record with Quantity = value }
    [<Extension>]
    static member WithSkill(record: RecipeSkillRequirement, value: string) : RecipeSkillRequirement = { record with Skill = value }
    [<Extension>]
    static member WithLevel(record: RecipeSkillRequirement, value: float) : RecipeSkillRequirement = { record with Level = value }
    [<Extension>]
    static member WithSkill(record: RecipeUnlock, value: RecipeSkillRequirement | null) : RecipeUnlock = { record with Skill = Option.ofObj value }
    [<Extension>]
    static member WithQuestId(record: RecipeUnlock, value: string | null) : RecipeUnlock = { record with QuestId = Option.ofObj value }
    [<Extension>]
    static member WithSeasons(record: RecipeUnlock, value: seq<string> | null) : RecipeUnlock = { record with Seasons = (match value with null -> None | items -> Some(List.ofSeq items)) }
    [<Extension>]
    static member WithAlgorithm(record: RngState, value: string) : RngState = { record with Algorithm = value }
    [<Extension>]
    static member WithS(record: RngState, value: seq<uint32>) : RngState = { record with S = List.ofSeq value }
    [<Extension>]
    static member WithId(record: Scene, value: string) : Scene = { record with Id = value }
    [<Extension>]
    static member WithName(record: Scene, value: string) : Scene = { record with Name = value }
    [<Extension>]
    static member WithWidth(record: Scene, value: float) : Scene = { record with Width = value }
    [<Extension>]
    static member WithHeight(record: Scene, value: float) : Scene = { record with Height = value }
    [<Extension>]
    static member WithTiles(record: Scene, value: seq<(Tile list)>) : Scene = { record with Tiles = List.ofSeq value }
    [<Extension>]
    static member WithTransitions(record: Scene, value: seq<SceneTransition>) : Scene = { record with Transitions = List.ofSeq value }
    [<Extension>]
    static member WithNpcs(record: Scene, value: seq<string>) : Scene = { record with Npcs = List.ofSeq value }
    [<Extension>]
    static member WithEvents(record: Scene, value: seq<string>) : Scene = { record with Events = List.ofSeq value }
    [<Extension>]
    static member WithFromX(record: SceneTransition, value: float) : SceneTransition = { record with FromX = value }
    [<Extension>]
    static member WithFromY(record: SceneTransition, value: float) : SceneTransition = { record with FromY = value }
    [<Extension>]
    static member WithToSceneId(record: SceneTransition, value: string) : SceneTransition = { record with ToSceneId = value }
    [<Extension>]
    static member WithToX(record: SceneTransition, value: float) : SceneTransition = { record with ToX = value }
    [<Extension>]
    static member WithToY(record: SceneTransition, value: float) : SceneTransition = { record with ToY = value }
    [<Extension>]
    static member WithLocked(record: SceneTransition, value: Nullable<bool>) : SceneTransition = { record with Locked = Option.ofNullable value }
    [<Extension>]
    static member WithSeasons(record: SeasonCondition, value: seq<string>) : SeasonCondition = { record with Seasons = List.ofSeq value }
    [<Extension>]
    static member WithId(record: ShopDefinition, value: string) : ShopDefinition = { record with Id = value }
    [<Extension>]
    static member WithName(record: ShopDefinition, value: string) : ShopDefinition = { record with Name = value }
    [<Extension>]
    static member WithStock(record: ShopDefinition, value: seq<ShopStockEntry>) : ShopDefinition = { record with Stock = List.ofSeq value }
    [<Extension>]
    static member WithSellPriceMultiplier(record: ShopDefinition, value: float) : ShopDefinition = { record with SellPriceMultiplier = value }
    [<Extension>]
    static member WithBuysItems(record: ShopDefinition, value: bool) : ShopDefinition = { record with BuysItems = value }
    [<Extension>]
    static member WithRepairsTools(record: ShopDefinition, value: bool) : ShopDefinition = { record with RepairsTools = value }
    [<Extension>]
    static member WithRepairCostPerPoint(record: ShopDefinition, value: float) : ShopDefinition = { record with RepairCostPerPoint = value }
    [<Extension>]
    static member WithItemId(record: ShopStockEntry, value: string) : ShopStockEntry = { record with ItemId = value }
    [<Extension>]
    static member WithPrice(record: ShopStockEntry, value: Nullable<float>) : ShopStockEntry = { record with Price = Option.ofNullable value }
    [<Extension>]
    static member WithSeasons(record: ShopStockEntry, value: seq<string> | null) : ShopStockEntry = { record with Seasons = (match value with null -> None | items -> Some(List.ofSeq items)) }
    [<Extension>]
    static member WithDailyLimit(record: ShopStockEntry, value: Nullable<float>) : ShopStockEntry = { record with DailyLimit = Option.ofNullable value }
    [<Extension>]
    static member WithXp(record: SkillState, value: float) : SkillState = { record with Xp = value }
    [<Extension>]
    static member WithLevel(record: SkillState, value: float) : SkillState = { record with Level = value }
    [<Extension>]
    static member WithFrameWidth(record: SpriteSheet, value: float) : SpriteSheet = { record with FrameWidth = value }
    [<Extension>]
    static member WithFrameHeight(record: SpriteSheet, value: float) : SpriteSheet = { record with FrameHeight = value }
    [<Extension>]
    static member WithFrames(record: SpriteSheet, value: float) : SpriteSheet = { record with Frames = value }
    [<Extension>]
    static member WithTicksPerFrame(record: SpriteSheet, value: float) : SpriteSheet = { record with TicksPerFrame = value }
    [<Extension>]
    static member WithDirectional(record: SpriteSheet, value: bool) : SpriteSheet = { record with Directional = value }
    [<Extension>]
    static member WithX(record: Tile, value: float) : Tile = { record with X = value }
    [<Extension>]
    static member WithY(record: Tile, value: float) : Tile = { record with Y = value }
    [<Extension>]
    static member WithType(record: Tile, value: string) : Tile = { record with Type = value }
    [<Extension>]
    static member WithBackground(record: Tile, value: string) : Tile = { record with Background = value }
    [<Extension>]
    static member WithOverlay(record: Tile, value: string | null) : Tile = { record with Overlay = Option.ofObj value }
    [<Extension>]
    static member WithObject(record: Tile, value: string | null) : Tile = { record with Object = Option.ofObj value }
    [<Extension>]
    static member WithCrop(record: Tile, value: Crop | null) : Tile = { record with Crop = Option.ofObj value }
    [<Extension>]
    static member WithItem(record: Tile, value: Item | null) : Tile = { record with Item = Option.ofObj value }
    [<Extension>]
    static member WithNode(record: Tile, value: TileNode | null) : Tile = { record with Node = Option.ofObj value }
    [<Extension>]
    static member WithMachine(record: Tile, value: TileMachine | null) : Tile = { record with Machine = Option.ofObj value }
    [<Extension>]
    static member WithLadderDown(record: Tile, value: Nullable<bool>) : Tile = { record with LadderDown = Option.ofNullable value }
    [<Extension>]
    static member WithCollision(record: Tile, value: bool) : Tile = { record with Collision = value }
    [<Extension>]
    static member WithCustomImage(record: Tile, value: string | null) : Tile = { record with CustomImage = Option.ofObj value }
    [<Extension>]
    static member WithVisuals(record: Tile, value: TileVisuals | null) : Tile = { record with Visuals = Option.ofObj value }
    [<Extension>]
    static member WithSoilState(record: Tile, value: string | null) : Tile = { record with SoilState = Option.ofObj value }
    [<Extension>]
    static member WithSoilMoisture(record: Tile, value: float) : Tile = { record with SoilMoisture = value }
    [<Extension>]
    static member WithSoilFertility(record: Tile, value: float) : Tile = { record with SoilFertility = value }
    [<Extension>]
    static member WithTypeId(record: TileMachine, value: string) : TileMachine = { record with TypeId = value }
    [<Extension>]
    static member WithProcessing(record: TileMachine, value: MachineProcessing | null) : TileMachine = { record with Processing = Option.ofObj value }
    [<Extension>]
    static member WithOutput(record: TileMachine, value: seq<RecipeIngredient> | null) : TileMachine = { record with Output = (match value with null -> None | items -> Some(List.ofSeq items)) }
    [<Extension>]
    static member WithTypeId(record: TileNode, value: string) : TileNode = { record with TypeId = value }
    [<Extension>]
    static member WithRemainingHealth(record: TileNode, value: float) : TileNode = { record with RemainingHealth = value }
    [<Extension>]
    static member WithDepletedOnDay(record: TileNode, value: Nullable<float>) : TileNode = { record with DepletedOnDay = Option.ofNullable value }
    [<Extension>]
    static member WithBackground(record: TileVisuals, value: VisualRef | null) : TileVisuals = { record with Background = Option.ofObj value }
    [<Extension>]
    static member WithOverlay(record: TileVisuals, value: VisualRef | null) : TileVisuals = { record with Overlay = Option.ofObj value }
    [<Extension>]
    static member WithObject(record: TileVisuals, value: VisualRef | null) : TileVisuals = { record with Object = Option.ofObj value }
    [<Extension>]
    static member WithDayStartMinute(record: TimeConfig, value: float) : TimeConfig = { record with DayStartMinute = value }
    [<Extension>]
    static member WithDayEndMinute(record: TimeConfig, value: float) : TimeConfig = { record with DayEndMinute = value }
    [<Extension>]
    static member WithMinutesPerRealSecond(record: TimeConfig, value: float) : TimeConfig = { record with MinutesPerRealSecond = value }
    [<Extension>]
    static member WithMinMinute(record: TimeOfDayCondition, value: float) : TimeOfDayCondition = { record with MinMinute = value }
    [<Extension>]
    static member WithMaxMinute(record: TimeOfDayCondition, value: float) : TimeOfDayCondition = { record with MaxMinute = value }
    [<Extension>]
    static member WithAssetId(record: VisualRef, value: string) : VisualRef = { record with AssetId = value }
    [<Extension>]
    static member WithAnimation(record: VisualRef, value: string | null) : VisualRef = { record with Animation = Option.ofObj value }
    [<Extension>]
    static member WithFrame(record: VisualRef, value: ArtFrame | null) : VisualRef = { record with Frame = Option.ofObj value }
    [<Extension>]
    static member WithWeatherIds(record: WeatherCondition, value: seq<string>) : WeatherCondition = { record with WeatherIds = List.ofSeq value }
    [<Extension>]
    static member WithTypes(record: WeatherConfig, value: seq<WeatherTypeDefinition>) : WeatherConfig = { record with Types = List.ofSeq value }
    [<Extension>]
    static member WithTable(record: WeatherConfig, value: ((string * (WeatherTableEntry list)) list)) : WeatherConfig = { record with Table = value }
    [<Extension>]
    static member WithTable(record: WeatherConfig, value: seq<KeyValuePair<string, (WeatherTableEntry list)>>) : WeatherConfig = { record with Table = [ for pair in value -> pair.Key, pair.Value ] }
    [<Extension>]
    static member WithWeatherId(record: WeatherTableEntry, value: string) : WeatherTableEntry = { record with WeatherId = value }
    [<Extension>]
    static member WithWeight(record: WeatherTableEntry, value: float) : WeatherTableEntry = { record with Weight = value }
    [<Extension>]
    static member WithId(record: WeatherTypeDefinition, value: string) : WeatherTypeDefinition = { record with Id = value }
    [<Extension>]
    static member WithName(record: WeatherTypeDefinition, value: string) : WeatherTypeDefinition = { record with Name = value }
    [<Extension>]
    static member WithWatersOutdoorSoil(record: WeatherTypeDefinition, value: bool) : WeatherTypeDefinition = { record with WatersOutdoorSoil = value }
    [<Extension>]
    static member WithCropDamageChance(record: WeatherTypeDefinition, value: float) : WeatherTypeDefinition = { record with CropDamageChance = value }
    [<Extension>]
    static member WithNpcsStayInside(record: WeatherTypeDefinition, value: bool) : WeatherTypeDefinition = { record with NpcsStayInside = value }
    [<Extension>]
    static member WithOverlay(record: WeatherTypeDefinition, value: string | null) : WeatherTypeDefinition = { record with Overlay = Option.ofObj value }
    [<Extension>]
    static member WithMinYear(record: YearRangeCondition, value: Nullable<float>) : YearRangeCondition = { record with MinYear = Option.ofNullable value }
    [<Extension>]
    static member WithMaxYear(record: YearRangeCondition, value: Nullable<float>) : YearRangeCondition = { record with MaxYear = Option.ofNullable value }
