namespace FarmEngine.Authoring.Net

open System
open System.Collections.Generic
open FarmEngine.Authoring
open FarmEngine.Schemas

/// JSON for the schema records from C#: the `SchemaJson` codecs by type, and text/UTF-8
/// conveniences. Writing uses the schema's member order; reading is the typed parse (no
/// migration) and throws `FormatException` with the first issue.
[<AbstractClass; Sealed>]
type RecordJson =
    // <generated by tools/codegen/record-json.py from SchemaJson.fs>
    static let codecs : Dictionary<Type, (obj -> Json) * (Path -> Json -> obj)> =
        let table = Dictionary<Type, (obj -> Json) * (Path -> Json -> obj)>()
        let add (encode: 'T -> Json) (decode: Path -> Json -> 'T) =
            table.[typeof<'T>] <- ((fun (value: obj) -> encode (unbox<'T> value)), (fun path json -> box (decode path json) |> nonNull))
        add SchemaJson.encodeActionDef SchemaJson.decodeActionDef
        add SchemaJson.encodeAnimalSpeciesDefinition SchemaJson.decodeAnimalSpeciesDefinition
        add SchemaJson.encodeAnimalState SchemaJson.decodeAnimalState
        add SchemaJson.encodeAnimationClip SchemaJson.decodeAnimationClip
        add SchemaJson.encodeArtFrame SchemaJson.decodeArtFrame
        add SchemaJson.encodeCalendarConfig SchemaJson.decodeCalendarConfig
        add SchemaJson.encodeCalendarFestival SchemaJson.decodeCalendarFestival
        add SchemaJson.encodeCalendarSeason SchemaJson.decodeCalendarSeason
        add SchemaJson.encodeContentPack SchemaJson.decodeContentPack
        add SchemaJson.encodeCrop SchemaJson.decodeCrop
        add SchemaJson.encodeCropDefinition SchemaJson.decodeCropDefinition
        add SchemaJson.encodeCropMultiTile SchemaJson.decodeCropMultiTile
        add SchemaJson.encodeCustomAsset SchemaJson.decodeCustomAsset
        add SchemaJson.encodeCustomCropDefinition SchemaJson.decodeCustomCropDefinition
        add SchemaJson.encodeDialogue SchemaJson.decodeDialogue
        add SchemaJson.encodeDialogueOption SchemaJson.decodeDialogueOption
        add SchemaJson.encodeEventOutcome SchemaJson.decodeEventOutcome
        add SchemaJson.encodeExportSettings SchemaJson.decodeExportSettings
        add SchemaJson.encodeExportWindow SchemaJson.decodeExportWindow
        add SchemaJson.encodeExportedGame SchemaJson.decodeExportedGame
        add SchemaJson.encodeFishTable SchemaJson.decodeFishTable
        add SchemaJson.encodeFishTableEntry SchemaJson.decodeFishTableEntry
        add SchemaJson.encodeGameContent SchemaJson.decodeGameContent
        add SchemaJson.encodeGameEvent SchemaJson.decodeGameEvent
        add SchemaJson.encodeGamePanel SchemaJson.decodeGamePanel
        add SchemaJson.encodeGamePanelEntry SchemaJson.decodeGamePanelEntry
        add SchemaJson.encodeGameProject SchemaJson.decodeGameProject
        add SchemaJson.encodeGiftTastes SchemaJson.decodeGiftTastes
        add SchemaJson.encodeGraphicsSettings SchemaJson.decodeGraphicsSettings
        add SchemaJson.encodeGridPoint SchemaJson.decodeGridPoint
        add SchemaJson.encodeInventorySlot SchemaJson.decodeInventorySlot
        add SchemaJson.encodeItem SchemaJson.decodeItem
        add SchemaJson.encodeMachineProcessing SchemaJson.decodeMachineProcessing
        add SchemaJson.encodeMachineTypeDefinition SchemaJson.decodeMachineTypeDefinition
        add SchemaJson.encodeMineBand SchemaJson.decodeMineBand
        add SchemaJson.encodeMineConfig SchemaJson.decodeMineConfig
        add SchemaJson.encodeMineRockWeight SchemaJson.decodeMineRockWeight
        add SchemaJson.encodeMinigameDef SchemaJson.decodeMinigameDef
        add SchemaJson.encodeMinigameResultTier SchemaJson.decodeMinigameResultTier
        add SchemaJson.encodeMovementConfig SchemaJson.decodeMovementConfig
        add SchemaJson.encodeNodeDrop SchemaJson.decodeNodeDrop
        add SchemaJson.encodeNodeTypeDefinition SchemaJson.decodeNodeTypeDefinition
        add SchemaJson.encodeNpc SchemaJson.decodeNpc
        add SchemaJson.encodeNpcBirthday SchemaJson.decodeNpcBirthday
        add SchemaJson.encodeNpcScheduleEntry SchemaJson.decodeNpcScheduleEntry
        add SchemaJson.encodeNpcSocialState SchemaJson.decodeNpcSocialState
        add SchemaJson.encodePackContent SchemaJson.decodePackContent
        add SchemaJson.encodePackDependency SchemaJson.decodePackDependency
        add SchemaJson.encodePackInstallation SchemaJson.decodePackInstallation
        add SchemaJson.encodePackManifest SchemaJson.decodePackManifest
        add SchemaJson.encodePackPermissions SchemaJson.decodePackPermissions
        add SchemaJson.encodePackPlayerStart SchemaJson.decodePackPlayerStart
        add SchemaJson.encodePackPlugin SchemaJson.decodePackPlugin
        add SchemaJson.encodePackStartItem SchemaJson.decodePackStartItem
        add SchemaJson.encodePlayer SchemaJson.decodePlayer
        add SchemaJson.encodeProjectSettings SchemaJson.decodeProjectSettings
        add SchemaJson.encodeQuest SchemaJson.decodeQuest
        add SchemaJson.encodeQuestObjective SchemaJson.decodeQuestObjective
        add SchemaJson.encodeQuestRewardItem SchemaJson.decodeQuestRewardItem
        add SchemaJson.encodeQuestRewards SchemaJson.decodeQuestRewards
        add SchemaJson.encodeRecipeDefinition SchemaJson.decodeRecipeDefinition
        add SchemaJson.encodeRecipeIngredient SchemaJson.decodeRecipeIngredient
        add SchemaJson.encodeRecipeSkillRequirement SchemaJson.decodeRecipeSkillRequirement
        add SchemaJson.encodeRecipeUnlock SchemaJson.decodeRecipeUnlock
        add SchemaJson.encodeRngState SchemaJson.decodeRngState
        add SchemaJson.encodeScene SchemaJson.decodeScene
        add SchemaJson.encodeSceneTransition SchemaJson.decodeSceneTransition
        add SchemaJson.encodeShopDefinition SchemaJson.decodeShopDefinition
        add SchemaJson.encodeShopStockEntry SchemaJson.decodeShopStockEntry
        add SchemaJson.encodeSkillState SchemaJson.decodeSkillState
        add SchemaJson.encodeSpriteSheet SchemaJson.decodeSpriteSheet
        add SchemaJson.encodeTile SchemaJson.decodeTile
        add SchemaJson.encodeTileMachine SchemaJson.decodeTileMachine
        add SchemaJson.encodeTileNode SchemaJson.decodeTileNode
        add SchemaJson.encodeTileVisuals SchemaJson.decodeTileVisuals
        add SchemaJson.encodeTimeConfig SchemaJson.decodeTimeConfig
        add SchemaJson.encodeVisualRef SchemaJson.decodeVisualRef
        add SchemaJson.encodeWeatherConfig SchemaJson.decodeWeatherConfig
        add SchemaJson.encodeWeatherTableEntry SchemaJson.decodeWeatherTableEntry
        add SchemaJson.encodeWeatherTypeDefinition SchemaJson.decodeWeatherTypeDefinition
        add SchemaJson.encodeEnterTileCondition SchemaJson.decodeEnterTileCondition
        add SchemaJson.encodeInteractTileCondition SchemaJson.decodeInteractTileCondition
        add SchemaJson.encodeHasItemCondition SchemaJson.decodeHasItemCondition
        add SchemaJson.encodeInventorySpaceCondition SchemaJson.decodeInventorySpaceCondition
        add SchemaJson.encodeFlagCondition SchemaJson.decodeFlagCondition
        add SchemaJson.encodeDayRangeCondition SchemaJson.decodeDayRangeCondition
        add SchemaJson.encodeSeasonCondition SchemaJson.decodeSeasonCondition
        add SchemaJson.encodeYearRangeCondition SchemaJson.decodeYearRangeCondition
        add SchemaJson.encodeTimeOfDayCondition SchemaJson.decodeTimeOfDayCondition
        add SchemaJson.encodeQuestStatusCondition SchemaJson.decodeQuestStatusCondition
        add SchemaJson.encodeFriendshipCondition SchemaJson.decodeFriendshipCondition
        add SchemaJson.encodeWeatherCondition SchemaJson.decodeWeatherCondition
        add SchemaJson.encodeFestivalIdCondition SchemaJson.decodeFestivalIdCondition
        add SchemaJson.encodeEventCondition SchemaJson.decodeEventCondition
        table

    static let keys : Dictionary<Type, Dictionary<string, string>> =
        let table = Dictionary<Type, Dictionary<string, string>>()
        let add (t: Type) (pairs: (string * string) list) =
            let fields = Dictionary<string, string>()
            for field, key in pairs do fields.[field] <- key
            table.[t] <- fields
        add typeof<ActionDef> [ "Id", "id"; "Name", "name"; "Description", "description"; "Conditions", "conditions"; "FailMessage", "failMessage"; "Outcomes", "outcomes"; "EnergyCost", "energyCost"; "Hotkey", "hotkey" ]
        add typeof<AnimalSpeciesDefinition> [ "Id", "id"; "Name", "name"; "Visual", "visual"; "PurchaseCost", "purchaseCost"; "FeedItemId", "feedItemId"; "ProductItemId", "productItemId"; "ProductIntervalDays", "productIntervalDays"; "DaysToAdult", "daysToAdult"; "Color", "color" ]
        add typeof<AnimalState> [ "Id", "id"; "SpeciesId", "speciesId"; "Name", "name"; "SceneId", "sceneId"; "X", "x"; "Y", "y"; "Mood", "mood"; "FedToday", "fedToday"; "PettedToday", "pettedToday"; "AgeDays", "ageDays"; "DaysSinceProduct", "daysSinceProduct"; "ProductReady", "productReady" ]
        add typeof<AnimationClip> [ "Name", "name"; "Loop", "loop"; "Frames", "frames" ]
        add typeof<ArtFrame> [ "AssetId", "assetId"; "X", "x"; "Y", "y"; "Width", "width"; "Height", "height"; "Ticks", "ticks" ]
        add typeof<CalendarConfig> [ "Seasons", "seasons"; "Festivals", "festivals" ]
        add typeof<CalendarFestival> [ "Id", "id"; "Name", "name"; "SeasonId", "seasonId"; "Day", "day" ]
        add typeof<CalendarSeason> [ "Id", "id"; "Name", "name"; "Days", "days" ]
        add typeof<ContentPack> [ "Manifest", "manifest"; "Content", "content"; "Plugins", "plugins" ]
        add typeof<Crop> [ "Type", "type"; "PlantedAt", "plantedAt"; "PlantedOnDay", "plantedOnDay"; "DaysGrown", "daysGrown"; "Withered", "withered"; "Stage", "stage"; "Watered", "watered"; "LastWateredDay", "lastWateredDay"; "Quality", "quality"; "Mutation", "mutation"; "IsMultiTileRoot", "isMultiTileRoot"; "MultiTileId", "multiTileId"; "HarvestCount", "harvestCount"; "DaysWithoutWater", "daysWithoutWater" ]
        add typeof<CropDefinition> [ "Id", "id"; "Name", "name"; "Visual", "visual"; "SeedCost", "seedCost"; "BaseHarvestValue", "baseHarvestValue"; "GrowthTime", "growthTime"; "GrowthDays", "growthDays"; "Stages", "stages"; "Seasons", "seasons"; "RegrowthTime", "regrowthTime"; "RegrowthDays", "regrowthDays"; "CanRegrow", "canRegrow"; "MultiTile", "multiTile"; "MutationChance", "mutationChance"; "YieldMin", "yieldMin"; "YieldMax", "yieldMax" ]
        add typeof<CropMultiTile> [ "Width", "width"; "Height", "height" ]
        add typeof<CustomAsset> [ "Id", "id"; "Name", "name"; "Type", "type"; "Width", "width"; "Height", "height"; "Animations", "animations"; "DataUrl", "dataUrl"; "TileType", "tileType"; "Sheet", "sheet" ]
        add typeof<CustomCropDefinition> [ "Id", "id"; "Name", "name"; "Visual", "visual"; "SeedCost", "seedCost"; "BaseHarvestValue", "baseHarvestValue"; "GrowthTime", "growthTime"; "GrowthDays", "growthDays"; "Stages", "stages"; "Seasons", "seasons"; "RegrowthTime", "regrowthTime"; "RegrowthDays", "regrowthDays"; "CanRegrow", "canRegrow"; "MultiTile", "multiTile"; "MutationChance", "mutationChance"; "YieldMin", "yieldMin"; "YieldMax", "yieldMax"; "CustomAsset", "customAsset" ]
        add typeof<Dialogue> [ "Id", "id"; "NpcId", "npcId"; "Text", "text"; "Options", "options" ]
        add typeof<DialogueOption> [ "Text", "text"; "NextDialogueId", "nextDialogueId"; "GiveItem", "giveItem"; "GiveItemQuantity", "giveItemQuantity"; "TakeMoney", "takeMoney"; "GiveMoney", "giveMoney"; "EventFlag", "eventFlag"; "RequiresItem", "requiresItem"; "RequiresFlag", "requiresFlag"; "OpenShopId", "openShopId"; "OfferQuestId", "offerQuestId"; "RequiresFriendship", "requiresFriendship"; "ActionId", "actionId" ]
        add typeof<EventOutcome> [ "Type", "type"; "Message", "message"; "ItemId", "itemId"; "ItemQuantity", "itemQuantity"; "Amount", "amount"; "Radius", "radius"; "FlagName", "flagName"; "QuestId", "questId"; "NpcId", "npcId"; "DialogueId", "dialogueId"; "TileX", "tileX"; "TileY", "tileY"; "NewTileType", "newTileType"; "SceneId", "sceneId"; "X", "x"; "Y", "y"; "SoundId", "soundId"; "ActionId", "actionId"; "MinigameId", "minigameId" ]
        add typeof<ExportSettings> [ "Title", "title"; "ExecutableName", "executableName"; "Version", "version"; "GameId", "gameId"; "Author", "author"; "Company", "company"; "IconAssetId", "icon"; "Window", "window"; "PixelScale", "pixelScale"; "Credits", "credits"; "Targets", "targets" ]
        add typeof<ExportWindow> [ "Width", "width"; "Height", "height"; "Fullscreen", "fullscreen" ]
        add typeof<ExportedGame> [ "SchemaVersion", "schemaVersion"; "Version", "version"; "Name", "name"; "Scenes", "scenes"; "Npcs", "npcs"; "Items", "items"; "Events", "events"; "Dialogues", "dialogues"; "Quests", "quests"; "StartSceneId", "startSceneId"; "CustomAssets", "customAssets"; "CustomCrops", "customCrops"; "PlayerCustomImage", "playerCustomImage"; "PlayerVisual", "playerVisual"; "Graphics", "graphics"; "GamePanels", "gamePanels"; "CurrentSeason", "currentSeason"; "CurrentDay", "currentDay"; "CurrentTimeMinutes", "currentTimeMinutes"; "CurrentYear", "currentYear"; "GameStartTime", "gameStartTime"; "Shops", "shops"; "NodeTypes", "nodeTypes"; "Settings", "settings"; "Recipes", "recipes"; "MachineTypes", "machineTypes"; "Weather", "weather"; "AnimalSpecies", "animalSpecies"; "Animals", "animals"; "FishTables", "fishTables"; "Mine", "mine"; "Actions", "actions"; "Minigames", "minigames"; "ContentPacks", "contentPacks"; "Player", "player"; "CurrentWeatherId", "currentWeatherId"; "SocialState", "socialState"; "MineDeepestFloor", "mineDeepestFloor"; "QuarantinedItems", "quarantinedItems" ]
        add typeof<FishTable> [ "Id", "id"; "Name", "name"; "Seasons", "seasons"; "SceneIds", "sceneIds"; "Entries", "entries"; "JunkChance", "junkChance"; "JunkItemId", "junkItemId" ]
        add typeof<FishTableEntry> [ "ItemId", "itemId"; "Weight", "weight"; "Difficulty", "difficulty" ]
        add typeof<GameContent> [ "ContentVersion", "contentVersion"; "Crops", "crops"; "Items", "items"; "Npcs", "npcs"; "Dialogues", "dialogues"; "Quests", "quests"; "Events", "events"; "Shops", "shops"; "NodeTypes", "nodeTypes"; "Settings", "settings"; "Recipes", "recipes"; "MachineTypes", "machineTypes"; "Weather", "weather"; "AnimalSpecies", "animalSpecies"; "FishTables", "fishTables"; "Mine", "mine"; "Actions", "actions"; "Minigames", "minigames"; "Scenes", "scenes"; "StartSceneId", "startSceneId" ]
        add typeof<GameEvent> [ "Id", "id"; "Name", "name"; "SceneId", "sceneId"; "Trigger", "trigger"; "Conditions", "conditions"; "Outcomes", "outcomes"; "Active", "active"; "Repeatable", "repeatable" ]
        add typeof<GamePanel> [ "Id", "id"; "Title", "title"; "VisibleFlag", "visibleFlag"; "Entries", "entries" ]
        add typeof<GamePanelEntry> [ "Label", "label"; "Kind", "kind"; "Value", "value" ]
        add typeof<GameProject> [ "SchemaVersion", "schemaVersion"; "Id", "id"; "Name", "name"; "Version", "version"; "Scenes", "scenes"; "Npcs", "npcs"; "Items", "items"; "Events", "events"; "Dialogues", "dialogues"; "Quests", "quests"; "Player", "player"; "EventFlags", "eventFlags"; "StartSceneId", "startSceneId"; "Mode", "mode"; "SelectedTileType", "selectedTileType"; "SelectedTileVisual", "selectedTileVisual"; "SelectedNpcId", "selectedNPCId"; "SelectedItemId", "selectedItemId"; "CurrentTime", "currentTime"; "CustomAssets", "customAssets"; "CustomCrops", "customCrops"; "PlayerCustomImage", "playerCustomImage"; "PlayerVisual", "playerVisual"; "Graphics", "graphics"; "GamePanels", "gamePanels"; "CurrentSeason", "currentSeason"; "CurrentDay", "currentDay"; "CurrentTimeMinutes", "currentTimeMinutes"; "CurrentYear", "currentYear"; "GameStartTime", "gameStartTime"; "Shops", "shops"; "NodeTypes", "nodeTypes"; "Settings", "settings"; "Recipes", "recipes"; "MachineTypes", "machineTypes"; "Weather", "weather"; "AnimalSpecies", "animalSpecies"; "Animals", "animals"; "FishTables", "fishTables"; "Mine", "mine"; "Actions", "actions"; "Minigames", "minigames"; "ContentPacks", "contentPacks"; "Export", "export"; "RngState", "rngState"; "CurrentWeatherId", "currentWeatherId"; "SocialState", "socialState"; "MineDeepestFloor", "mineDeepestFloor"; "QuarantinedItems", "quarantinedItems" ]
        add typeof<GiftTastes> [ "Loved", "loved"; "Liked", "liked"; "Disliked", "disliked"; "Hated", "hated" ]
        add typeof<GraphicsSettings> [ "PixelArt", "pixelArt" ]
        add typeof<GridPoint> [ "X", "x"; "Y", "y" ]
        add typeof<InventorySlot> [ "Item", "item"; "Quantity", "quantity" ]
        add typeof<Item> [ "Id", "id"; "Name", "name"; "Visual", "visual"; "Description", "description"; "Type", "type"; "Stackable", "stackable"; "MaxStack", "maxStack"; "Value", "value"; "CropType", "cropType"; "CustomImage", "customImage"; "ToolType", "toolType"; "ToolPower", "toolPower"; "ToolTier", "toolTier"; "Durability", "durability"; "MaxDurability", "maxDurability"; "UseActionId", "useActionId"; "ConsumeOnUse", "consumeOnUse" ]
        add typeof<MachineProcessing> [ "RecipeId", "recipeId"; "CompletesAtMinute", "completesAtMinute" ]
        add typeof<MachineTypeDefinition> [ "Id", "id"; "Name", "name"; "Visual", "visual"; "Description", "description"; "Color", "color"; "ItemId", "itemId"; "BlocksMovement", "blocksMovement"; "StationCategories", "stationCategories" ]
        add typeof<MineBand> [ "FromFloor", "fromFloor"; "ToFloor", "toFloor"; "Rocks", "rocks"; "Density", "density" ]
        add typeof<MineConfig> [ "Enabled", "enabled"; "EntranceSceneId", "entranceSceneId"; "EntranceX", "entranceX"; "EntranceY", "entranceY"; "Floors", "floors"; "FloorWidth", "floorWidth"; "FloorHeight", "floorHeight"; "Bands", "bands"; "LadderChance", "ladderChance"; "ElevatorEvery", "elevatorEvery" ]
        add typeof<MineRockWeight> [ "NodeTypeId", "nodeTypeId"; "Weight", "weight" ]
        add typeof<MinigameDef> [ "Id", "id"; "Name", "name"; "Kind", "kind"; "Config", "config"; "ResultTiers", "resultTiers" ]
        add typeof<MinigameResultTier> [ "MinScore", "minScore"; "Outcomes", "outcomes" ]
        add typeof<MovementConfig> [ "PlayerSpeed", "playerSpeed" ]
        add typeof<NodeDrop> [ "ItemId", "itemId"; "Min", "min"; "Max", "max"; "Weight", "weight" ]
        add typeof<NodeTypeDefinition> [ "Id", "id"; "Name", "name"; "Visual", "visual"; "Health", "health"; "RequiredTool", "requiredTool"; "RequiredToolTier", "requiredToolTier"; "Drops", "drops"; "RespawnDays", "respawnDays"; "Color", "color"; "BlocksMovement", "blocksMovement" ]
        add typeof<Npc> [ "Id", "id"; "Name", "name"; "Visual", "visual"; "X", "x"; "Y", "y"; "SceneId", "sceneId"; "Dialogue", "dialogue"; "CanMove", "canMove"; "MovePattern", "movePattern"; "WanderRadius", "wanderRadius"; "PatrolPoints", "patrolPoints"; "Schedule", "schedule"; "GiftTastes", "giftTastes"; "Birthday", "birthday"; "Appearance", "appearance"; "CustomImage", "customImage" ]
        add typeof<NpcBirthday> [ "Season", "season"; "Day", "day" ]
        add typeof<NpcScheduleEntry> [ "Minute", "minute"; "SceneId", "sceneId"; "X", "x"; "Y", "y" ]
        add typeof<NpcSocialState> [ "Friendship", "friendship"; "GiftsToday", "giftsToday"; "LastGiftDay", "lastGiftDay" ]
        add typeof<PackContent> [ "Crops", "crops"; "Items", "items"; "Recipes", "recipes"; "MachineTypes", "machineTypes"; "NodeTypes", "nodeTypes"; "AnimalSpecies", "animalSpecies"; "FishTables", "fishTables"; "WeatherTypes", "weatherTypes"; "Npcs", "npcs"; "Dialogues", "dialogues"; "Scenes", "scenes"; "Events", "events"; "Quests", "quests"; "Shops", "shops"; "Actions", "actions"; "Minigames", "minigames"; "PlayerStart", "playerStart"; "Strings", "strings" ]
        add typeof<PackDependency> [ "PackId", "packId"; "Version", "version" ]
        add typeof<PackInstallation> [ "Pack", "pack"; "Enabled", "enabled" ]
        add typeof<PackManifest> [ "Id", "id"; "Name", "name"; "Version", "version"; "Description", "description"; "Author", "author"; "EngineCompatibility", "engineCompatibility"; "Base", "base"; "Dependencies", "dependencies"; "Overrides", "overrides"; "Permissions", "permissions" ]
        add typeof<PackPermissions> [ "Hooks", "hooks"; "ContentInject", "contentInject"; "UiPanels", "uiPanels"; "Mutations", "mutations" ]
        add typeof<PackPlayerStart> [ "SceneId", "sceneId"; "X", "x"; "Y", "y"; "Money", "money"; "Inventory", "inventory" ]
        add typeof<PackPlugin> [ "Id", "id"; "Name", "name"; "Hooks", "hooks"; "Source", "source" ]
        add typeof<PackStartItem> [ "ItemId", "itemId"; "Quantity", "quantity" ]
        add typeof<Player> [ "X", "x"; "Y", "y"; "Direction", "direction"; "SceneId", "sceneId"; "Inventory", "inventory"; "MaxInventorySize", "maxInventorySize"; "Money", "money"; "Energy", "energy"; "MaxEnergy", "maxEnergy"; "Skills", "skills"; "ActiveQuests", "activeQuests"; "CompletedQuests", "completedQuests"; "EquippedTool", "equippedTool"; "PixelX", "pixelX"; "PixelY", "pixelY"; "TargetX", "targetX"; "TargetY", "targetY" ]
        add typeof<ProjectSettings> [ "Movement", "movement"; "EnergyEnabled", "energyEnabled"; "MaxEnergy", "maxEnergy"; "CollapseEnergyFraction", "collapseEnergyFraction"; "CollapseMoneyPenalty", "collapseMoneyPenalty"; "Time", "time"; "Calendar", "calendar"; "SkillsEnabled", "skillsEnabled"; "SkillLevelCurve", "skillLevelCurve"; "Locale", "locale"; "ShowMadeWithCredit", "showMadeWithCredit" ]
        add typeof<Quest> [ "Id", "id"; "Name", "name"; "Description", "description"; "Giver", "giver"; "Status", "status"; "Objectives", "objectives"; "Rewards", "rewards"; "Prerequisites", "prerequisites"; "AutoStart", "autoStart"; "Repeatable", "repeatable"; "AvailableSeasons", "availableSeasons"; "AvailableFromDay", "availableFromDay"; "AvailableToDay", "availableToDay" ]
        add typeof<QuestObjective> [ "Id", "id"; "Type", "type"; "Description", "description"; "TargetItemId", "targetItemId"; "TargetItemQuantity", "targetItemQuantity"; "TargetCropType", "targetCropType"; "TargetCropQuantity", "targetCropQuantity"; "TargetNpcId", "targetNPCId"; "TargetSceneId", "targetSceneId"; "Completed", "completed"; "Progress", "progress" ]
        add typeof<QuestRewardItem> [ "ItemId", "itemId"; "Quantity", "quantity" ]
        add typeof<QuestRewards> [ "Money", "money"; "Items", "items"; "Experience", "experience" ]
        add typeof<RecipeDefinition> [ "Id", "id"; "Name", "name"; "Inputs", "inputs"; "Outputs", "outputs"; "ProcessingMinutes", "processingMinutes"; "MachineTypeId", "machineTypeId"; "Category", "category"; "RequiresStationCategory", "requiresStationCategory"; "Unlock", "unlock" ]
        add typeof<RecipeIngredient> [ "ItemId", "itemId"; "Quantity", "quantity" ]
        add typeof<RecipeSkillRequirement> [ "Skill", "skill"; "Level", "level" ]
        add typeof<RecipeUnlock> [ "Skill", "skill"; "QuestId", "questId"; "Seasons", "seasons" ]
        add typeof<RngState> [ "Algorithm", "algorithm"; "S", "s" ]
        add typeof<Scene> [ "Id", "id"; "Name", "name"; "Width", "width"; "Height", "height"; "Tiles", "tiles"; "Transitions", "transitions"; "Npcs", "npcs"; "Events", "events" ]
        add typeof<SceneTransition> [ "FromX", "fromX"; "FromY", "fromY"; "ToSceneId", "toSceneId"; "ToX", "toX"; "ToY", "toY"; "Locked", "locked" ]
        add typeof<ShopDefinition> [ "Id", "id"; "Name", "name"; "Stock", "stock"; "SellPriceMultiplier", "sellPriceMultiplier"; "BuysItems", "buysItems"; "RepairsTools", "repairsTools"; "RepairCostPerPoint", "repairCostPerPoint" ]
        add typeof<ShopStockEntry> [ "ItemId", "itemId"; "Price", "price"; "Seasons", "seasons"; "DailyLimit", "dailyLimit" ]
        add typeof<SkillState> [ "Xp", "xp"; "Level", "level" ]
        add typeof<SpriteSheet> [ "FrameWidth", "frameWidth"; "FrameHeight", "frameHeight"; "Frames", "frames"; "TicksPerFrame", "ticksPerFrame"; "Directional", "directional" ]
        add typeof<Tile> [ "X", "x"; "Y", "y"; "Type", "type"; "Background", "background"; "Overlay", "overlay"; "Object", "object"; "Crop", "crop"; "Item", "item"; "Node", "node"; "Machine", "machine"; "LadderDown", "ladderDown"; "Collision", "collision"; "CustomImage", "customImage"; "Visuals", "visuals"; "SoilState", "soilState"; "SoilMoisture", "soilMoisture"; "SoilFertility", "soilFertility" ]
        add typeof<TileMachine> [ "TypeId", "typeId"; "Processing", "processing"; "Output", "output" ]
        add typeof<TileNode> [ "TypeId", "typeId"; "RemainingHealth", "remainingHealth"; "DepletedOnDay", "depletedOnDay" ]
        add typeof<TileVisuals> [ "Background", "background"; "Overlay", "overlay"; "Object", "object" ]
        add typeof<TimeConfig> [ "DayStartMinute", "dayStartMinute"; "DayEndMinute", "dayEndMinute"; "MinutesPerRealSecond", "minutesPerRealSecond" ]
        add typeof<VisualRef> [ "AssetId", "assetId"; "Animation", "animation"; "Frame", "frame" ]
        add typeof<WeatherConfig> [ "Types", "types"; "Table", "table" ]
        add typeof<WeatherTableEntry> [ "WeatherId", "weatherId"; "Weight", "weight" ]
        add typeof<WeatherTypeDefinition> [ "Id", "id"; "Name", "name"; "WatersOutdoorSoil", "watersOutdoorSoil"; "CropDamageChance", "cropDamageChance"; "NpcsStayInside", "npcsStayInside"; "Overlay", "overlay" ]
        add typeof<EnterTileCondition> [ "X", "x"; "Y", "y"; "X2", "x2"; "Y2", "y2" ]
        add typeof<InteractTileCondition> [ "X", "x"; "Y", "y"; "X2", "x2"; "Y2", "y2" ]
        add typeof<HasItemCondition> [ "ItemId", "itemId"; "Quantity", "quantity" ]
        add typeof<InventorySpaceCondition> [ "ItemId", "itemId"; "Quantity", "quantity" ]
        add typeof<FlagCondition> [ "Flag", "flag"; "Value", "value" ]
        add typeof<DayRangeCondition> [ "MinDay", "minDay"; "MaxDay", "maxDay" ]
        add typeof<SeasonCondition> [ "Seasons", "seasons" ]
        add typeof<YearRangeCondition> [ "MinYear", "minYear"; "MaxYear", "maxYear" ]
        add typeof<TimeOfDayCondition> [ "MinMinute", "minMinute"; "MaxMinute", "maxMinute" ]
        add typeof<QuestStatusCondition> [ "QuestId", "questId"; "Status", "status" ]
        add typeof<FriendshipCondition> [ "NpcId", "npcId"; "Min", "min" ]
        add typeof<WeatherCondition> [ "WeatherIds", "weatherIds" ]
        add typeof<FestivalIdCondition> [ "FestivalId", "festivalId" ]
        table
    // </generated>

    static member private Codec(t: Type) =
        match codecs.TryGetValue t with
        | true, codec -> codec
        | _ -> invalidArg "T" (sprintf "%s is not a schema record" t.Name)

    /// The JSON key of a record field (`SelectedNpcId` → `selectedNPCId`).
    static member JsonKey(t: Type, field: string) : string =
        match keys.TryGetValue t with
        | true, fields when fields.ContainsKey field -> fields.[field]
        | _ -> if field.Length = 0 then field else string (Char.ToLowerInvariant field.[0]) + field.Substring 1

    /// A record of runtime type `t` as a System.Text.Json node.
    static member ToNode(value: obj, t: Type) : System.Text.Json.Nodes.JsonNode =
        match JsonInterop.toNode (RecordJson.ToJson(value, t)) with
        | null -> System.Text.Json.Nodes.JsonObject() :> System.Text.Json.Nodes.JsonNode
        | node -> node

    /// The typed parse of a System.Text.Json node as runtime type `t`; throws `FormatException`
    /// with the first issue.
    static member FromNode(node: System.Text.Json.Nodes.JsonNode | null, t: Type) : obj =
        match RecordJson.TryFromJson(JsonInterop.ofNode node, t) with
        | Ok value -> value
        | Error issue -> raise (FormatException issue)

    /// Whether `t` is a schema record with a codec.
    static member IsRecord(t: Type) : bool = codecs.ContainsKey t

    /// A record as a JSON value.
    static member ToJson<'T>(value: 'T) : Json = (fst (RecordJson.Codec typeof<'T>)) (box value |> nonNull)

    /// A record of runtime type `t` as a JSON value.
    static member ToJson(value: obj, t: Type) : Json = (fst (RecordJson.Codec t)) value

    /// A record as compact JSON text.
    static member ToText<'T>(value: 'T) : string = Json.stringify (RecordJson.ToJson value)

    /// A record as indented JSON text.
    static member ToIndentedText<'T>(value: 'T) : string = Json.stringifyIndented (RecordJson.ToJson value)

    /// A record as compact UTF-8 JSON.
    static member ToUtf8<'T>(value: 'T) : byte[] = Bytes.utf8 (RecordJson.ToText value)

    /// A record as stable JSON (sorted keys): for comparisons and hashes.
    static member ToStableText<'T>(value: 'T) : string = Json.stableStringify (RecordJson.ToJson value)

    /// A record as a System.Text.Json node.
    static member ToNode<'T>(value: 'T) : System.Text.Json.Nodes.JsonNode =
        match JsonInterop.toNode (RecordJson.ToJson value) with
        | null -> System.Text.Json.Nodes.JsonObject() :> System.Text.Json.Nodes.JsonNode
        | node -> node

    /// The typed parse of a JSON value of runtime type `t`, or the first issue.
    static member TryFromJson(json: Json, t: Type) : Result<obj, string> =
        let decode = snd (RecordJson.Codec t)
        Decode.run decode json

    /// The typed parse of a JSON value; throws `FormatException` with the first issue.
    static member FromJson<'T>(json: Json) : 'T =
        match RecordJson.TryFromJson(json, typeof<'T>) with
        | Ok value -> unbox<'T> value
        | Error issue -> raise (FormatException issue)

    /// The typed parse of JSON text; throws `FormatException` for invalid JSON or the first issue.
    static member Parse<'T>(text: string) : 'T =
        match Json.parse text with
        | Ok json -> RecordJson.FromJson<'T> json
        | Error message -> raise (FormatException message)

    /// The typed parse of UTF-8 JSON.
    static member ParseUtf8<'T>(bytes: ReadOnlySpan<byte>) : 'T = RecordJson.Parse<'T>(System.Text.Encoding.UTF8.GetString bytes)

    /// The typed parse of a System.Text.Json node.
    static member FromNode<'T>(node: System.Text.Json.Nodes.JsonNode | null) : 'T = RecordJson.FromJson<'T>(JsonInterop.ofNode node)

    /// A deep copy through JSON (`JSON.parse(JSON.stringify(value))`).
    static member Clone<'T>(value: 'T) : 'T = RecordJson.FromJson<'T>(RecordJson.ToJson value)
