//! Parity of the save migrations with the TypeScript reference engine (`migrateGameState`).
//! Fixtures come from `fixtures/golden/saves` (generated by `tools/golden/generate.sh`); this is
//! the Rust side of the C# `GoldenParityTests.SaveMigrationMatchesTypeScript`.

use farm_cart::migrate_game_state;
use farm_sim::{hash_state, stable_stringify};
use serde_json::Value;
use std::path::PathBuf;

fn saves_dir() -> PathBuf {
    [env!("CARGO_MANIFEST_DIR"), "..", "..", "fixtures", "golden", "saves"].iter().collect()
}

#[test]
fn save_migrations_match_typescript() {
    let mut paths: Vec<PathBuf> = std::fs::read_dir(saves_dir())
        .expect("list saves")
        .map(|entry| entry.expect("directory entry").path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "json"))
        .collect();
    paths.sort();
    assert!(paths.len() >= 8, "expected the save fixtures, found {}", paths.len());

    let mut failures = Vec::new();
    for path in &paths {
        let name = path.file_stem().expect("stem").to_string_lossy().into_owned();
        let text = std::fs::read_to_string(path).expect("read fixture");
        let fixture: Value = serde_json::from_str(&text).expect("valid fixture JSON");
        let expected = &fixture["result"];
        let result = migrate_game_state(&fixture["input"]);

        if result.ok != expected["ok"].as_bool().expect("ok") {
            failures
                .push(format!("{name}: ok = {} (errors {:?}), TS says {}", result.ok, result.errors, expected["ok"]));
            continue;
        }
        if Some(result.from_version) != expected["fromVersion"].as_f64() {
            failures.push(format!("{name}: fromVersion {} vs TS {}", result.from_version, expected["fromVersion"]));
        }
        if let Some(migrated) = expected["migrated"].as_bool() {
            if result.migrated != migrated {
                failures.push(format!("{name}: migrated {} vs TS {migrated}", result.migrated));
            }
        }
        if !result.ok {
            let errors: Vec<&str> =
                expected["errors"].as_array().expect("errors").iter().filter_map(Value::as_str).collect();
            if result.errors != errors {
                failures.push(format!("{name}: errors {:?} vs TS {errors:?}", result.errors));
            }
            continue;
        }
        let data = result.data.expect("ok result has data");
        let stable = stable_stringify(&data);
        if stable != fixture["stable"].as_str().expect("stable") {
            failures.push(format!("{name}: stable JSON differs\nTS:   {}\nRust: {stable}", fixture["stable"]));
        }
        if Some(hash_state(&data).as_str()) != fixture["hash"].as_str() {
            failures.push(format!("{name}: hash {} vs TS {}", hash_state(&data), fixture["hash"]));
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n\n"));
}
