[package]
name = "farm-player"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
farm-cart = { path = "../farm-cart" }
farm-sim = { path = "../farm-sim" }
farm-runtime = { path = "../farm-runtime" }
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
