// Regenerates src/FarmEngine.Authoring.Net/RecordWith.fs from the built schema records:
//   dotnet build -c Release src/FarmEngine.Authoring && dotnet fsi tools/codegen/record-with.fsx
// With --check (after the same build) it writes nothing and exits 1 when RecordWith.fs is not
// what it would generate (tools/codegen/check.sh, CI).
#r "../../src/FarmEngine.Authoring/bin/Release/net10.0/FarmEngine.Authoring.dll"
open System
open Microsoft.FSharp.Reflection
let asm = typeof<FarmEngine.Schemas.GameProject>.Assembly
let records =
    asm.GetTypes()
    |> Array.filter (fun t -> t.Namespace = "FarmEngine.Schemas" && FSharpType.IsRecord t)
    |> Array.sortBy (fun t -> t.Name)
let isGen (d: Type) (t: Type) = t.IsGenericType && t.GetGenericTypeDefinition() = d
let rec fs (t: Type) : string =
    if t = typeof<string> then "string"
    elif t = typeof<float> then "float"
    elif t = typeof<int> then "int"
    elif t = typeof<bool> then "bool"
    elif t = typeof<uint32> then "uint32"
    elif isGen typedefof<option<_>> t then sprintf "(%s option)" (fs (t.GetGenericArguments().[0]))
    elif isGen typedefof<list<_>> t then sprintf "(%s list)" (fs (t.GetGenericArguments().[0]))
    elif FSharpType.IsTuple t then "(" + (FSharpType.GetTupleElements t |> Array.map fs |> String.concat " * ") + ")"
    elif t.Name = "Json" then "Json"
    else t.Name
let lines = ResizeArray<string>()
let add (s: string) = lines.Add s
add "namespace FarmEngine.Authoring.Net"
add ""
add "// Generated by tools/codegen/record-with.fsx from the schema records in Schema.fs. Do not edit."
add ""
add "open System"
add "open System.Collections.Generic"
add "open System.Runtime.CompilerServices"
add "open FarmEngine.Authoring"
add "open FarmEngine.Schemas"
add ""
add "/// `{ record with Field = value }` for C#, one `WithField` per record field: options take"
add "/// the value or null (value types: a `Nullable`), lists any sequence, ordered maps any"
add "/// key/value pairs. `Record.Default.WithA(a).WithB(b)` builds a record."
add "[<Extension; AbstractClass; Sealed>]"
add "type RecordWith ="
for t in records do
    for p in FSharpType.GetRecordFields t do
        if p.Name <> "Extra" then
            let ft = p.PropertyType
            let name = p.Name
            let emit (paramType: string) (convert: string) =
                add (sprintf "    [<Extension>]")
                add (sprintf "    static member With%s(record: %s, value: %s) : %s = { record with %s = %s }" name t.Name paramType t.Name name convert)
            if isGen typedefof<option<_>> ft then
                let inner = ft.GetGenericArguments().[0]
                if isGen typedefof<option<_>> inner then emit (fs ft) "value"
                elif inner.IsValueType then emit (sprintf "Nullable<%s>" (fs inner)) "Option.ofNullable value"
                elif isGen typedefof<list<_>> inner then
                    emit (sprintf "seq<%s> | null" (fs (inner.GetGenericArguments().[0]))) "(match value with null -> None | items -> Some(List.ofSeq items))"
                else emit (sprintf "%s | null" (fs inner)) "Option.ofObj value"
            elif isGen typedefof<list<_>> ft then
                let el = ft.GetGenericArguments().[0]
                if FSharpType.IsTuple el then
                    let parts = FSharpType.GetTupleElements el
                    emit (fs ft) "value"
                    emit (sprintf "seq<KeyValuePair<%s, %s>>" (fs parts.[0]) (fs parts.[1])) "[ for pair in value -> pair.Key, pair.Value ]"
                else emit (sprintf "seq<%s>" (fs el)) "List.ofSeq value"
            else emit (fs ft) "value"
let target = IO.Path.Combine(__SOURCE_DIRECTORY__, "..", "..", "src", "FarmEngine.Authoring.Net", "RecordWith.fs")
let generated = String.concat "\n" lines + "\n"
if fsi.CommandLineArgs |> Array.contains "--check" then
    // Line endings as checked out do not matter (a Windows checkout may have CRLF).
    if IO.File.ReadAllText(target).Replace("\r\n", "\n") <> generated then
        eprintfn "src/FarmEngine.Authoring.Net/RecordWith.fs is out of date: build src/FarmEngine.Authoring in Release and run dotnet fsi tools/codegen/record-with.fsx"
        exit 1
    printfn "src/FarmEngine.Authoring.Net/RecordWith.fs is current (%d records)" records.Length
else
    IO.File.WriteAllText(target, generated)
    printfn "%d lines" lines.Count
