//! Port of `BuiltinArt.cs`: the built-in pixel-art pack (sprite sheets + manifest generated by
//! `tools/art`, embedded from `assets/builtin-art/`). The renderer asks it for a sprite by
//! content id whenever a project binds no art of its own; creator art always wins. Unknown ids
//! fall back to generic sprites (a plant, a rock, a villager) so mod content still looks like
//! something. Sheets are image sources `builtin://<file>` that [`crate::ImageStore`] decodes
//! once.

use crate::num::{cs_max, round_half_even, to_int};
use crate::snapshot::SnapshotSprite;
use serde::{Deserialize, Serialize};
use std::borrow::Cow;
use std::collections::BTreeMap;
use std::sync::{Arc, OnceLock};

/// Scheme of sheet image sources understood by [`crate::ImageStore`].
pub const URL_SCHEME: &str = "builtin://";

const DIRECTION_ROWS: [&str; 4] = ["down", "left", "right", "up"];

const EMBEDDED_MANIFEST: &[u8] = include_bytes!("../../../assets/builtin-art/manifest.json");
const EMBEDDED_SHEETS: &[(&str, &[u8])] = &[
    ("tiles.png", include_bytes!("../../../assets/builtin-art/tiles.png")),
    ("objects.png", include_bytes!("../../../assets/builtin-art/objects.png")),
    ("characters.png", include_bytes!("../../../assets/builtin-art/characters.png")),
];

/// One sprite of the pack: a grid of `frames` × `rows` cells on a sheet.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct BuiltinArtEntry {
    pub name: String,
    /// Sheet file name inside the pack (`objects.png`).
    pub file: String,
    pub x: i32,
    pub y: i32,
    /// Cell width in sheet pixels.
    pub w: i32,
    /// Cell height in sheet pixels.
    pub h: i32,
    /// Columns: animation frames when `ticks_per_frame` is set, else look-alike variants picked by
    /// tile coordinate.
    pub frames: i32,
    /// Rows: the four facing directions (down, left, right, up) when `directional`.
    pub rows: i32,
    /// `bottom` (objects stand on the tile's bottom edge) or `top` (ground tiles).
    pub anchor: String,
    /// Tiles covered, `[width, height]`.
    pub footprint: Vec<i32>,
    pub directional: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ticks_per_frame: Option<i32>,
    /// Column shown while a directional sprite stands still.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idle_frame: Option<i32>,
    /// Crop sheets: number of growth-stage columns.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stages: Option<i32>,
    /// Machine sheets: the state each column shows (`idle`, `working`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub states: Option<Vec<String>>,
}

impl Default for BuiltinArtEntry {
    fn default() -> Self {
        Self {
            name: String::new(),
            file: String::new(),
            x: 0,
            y: 0,
            w: 0,
            h: 0,
            frames: 1,
            rows: 1,
            anchor: "bottom".to_owned(),
            footprint: vec![1, 1],
            directional: false,
            ticks_per_frame: None,
            idle_frame: None,
            stages: None,
            states: None,
        }
    }
}

impl BuiltinArtEntry {
    /// Frames animate over time (rather than being variants).
    pub fn animated(&self) -> bool {
        self.ticks_per_frame.is_some_and(|ticks| ticks > 0) && self.frames > 1
    }

    /// The frame an animation shows at `tick`.
    fn animation_column(&self, tick: f64) -> i32 {
        let ticks = f64::from(self.ticks_per_frame.unwrap_or(1));
        to_int((cs_max(0.0, tick) / ticks).floor() % f64::from(self.frames))
    }
}

/// A sheet image of the pack.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct BuiltinArtSheet {
    pub file: String,
    pub w: i32,
    pub h: i32,
}

/// The manifest written by `tools/art/build_art.py`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct BuiltinArtManifest {
    pub version: i32,
    pub tile_size: i32,
    pub palette: Vec<String>,
    pub sheets: Vec<BuiltinArtSheet>,
    pub entries: Vec<BuiltinArtEntry>,
}

impl Default for BuiltinArtManifest {
    fn default() -> Self {
        Self { version: 0, tile_size: 32, palette: Vec::new(), sheets: Vec::new(), entries: Vec::new() }
    }
}

#[derive(Debug)]
struct Sheet {
    url: Arc<str>,
    bytes: Cow<'static, [u8]>,
}

/// A pixel-art pack: the manifest plus its sheet bytes.
#[derive(Debug)]
pub struct BuiltinArt {
    manifest: BuiltinArtManifest,
    /// Entry index by name; later entries with the same name win.
    entries: BTreeMap<String, usize>,
    sheets: BTreeMap<String, Sheet>,
}

impl BuiltinArt {
    /// The pack embedded in this crate (parsed on first use).
    pub fn embedded() -> &'static BuiltinArt {
        static EMBEDDED: OnceLock<BuiltinArt> = OnceLock::new();
        EMBEDDED.get_or_init(|| {
            let sheets = EMBEDDED_SHEETS.iter().map(|(file, bytes)| ((*file).to_owned(), Cow::Borrowed(*bytes)));
            Self::with_sheets(EMBEDDED_MANIFEST, sheets).expect("the embedded art manifest is valid")
        })
    }

    /// Loads a pack from manifest JSON and its sheet files (tests, future external packs).
    pub fn load(manifest_json: &[u8], sheets: Vec<(String, Vec<u8>)>) -> Result<BuiltinArt, String> {
        Self::with_sheets(manifest_json, sheets.into_iter().map(|(file, bytes)| (file, Cow::Owned(bytes))))
    }

    fn with_sheets(
        manifest_json: &[u8],
        sheets: impl Iterator<Item = (String, Cow<'static, [u8]>)>,
    ) -> Result<BuiltinArt, String> {
        let manifest: BuiltinArtManifest =
            serde_json::from_slice(manifest_json).map_err(|e| format!("built-in art manifest: {e}"))?;
        let mut entries = BTreeMap::new();
        for (index, entry) in manifest.entries.iter().enumerate() {
            entries.insert(entry.name.clone(), index);
        }
        let sheets =
            sheets.map(|(file, bytes)| (file.clone(), Sheet { url: Arc::from(sheet_url(&file)), bytes })).collect();
        Ok(BuiltinArt { manifest, entries, sheets })
    }

    pub fn manifest(&self) -> &BuiltinArtManifest {
        &self.manifest
    }

    /// Native tile size of the pack in sheet pixels (32).
    pub fn tile_size(&self) -> i32 {
        if self.manifest.tile_size > 0 {
            self.manifest.tile_size
        } else {
            32
        }
    }

    /// Every entry by name.
    pub fn entries(&self) -> impl Iterator<Item = &BuiltinArtEntry> {
        self.entries.values().map(|&index| &self.manifest.entries[index])
    }

    pub fn find(&self, name: &str) -> Option<&BuiltinArtEntry> {
        self.entries.get(name).map(|&index| &self.manifest.entries[index])
    }

    /// Raw PNG bytes of a sheet file of this pack.
    pub fn sheet_bytes(&self, file: &str) -> Option<&[u8]> {
        self.sheets.get(file).map(|sheet| sheet.bytes.as_ref())
    }

    /// Raw PNG bytes of a `builtin://` source from the embedded pack.
    pub fn resolve_sheet(source: &str) -> Option<&'static [u8]> {
        Self::embedded().sheet_bytes(source.strip_prefix(URL_SCHEME)?)
    }

    fn url(&self, file: &str) -> Arc<str> {
        match self.sheets.get(file) {
            Some(sheet) => Arc::clone(&sheet.url),
            None => Arc::from(sheet_url(file)),
        }
    }

    /// Deterministic 32-bit mix of tile coordinates (variant selection; no random source).
    pub fn hash(x: i32, y: i32) -> u32 {
        let mut h = (x as u32).wrapping_mul(0x9E37_79B1) ^ (y as u32).wrapping_mul(0x85EB_CA77);
        h ^= h >> 15;
        h = h.wrapping_mul(0x2C1B_3C6D);
        h ^= h >> 12;
        h = h.wrapping_mul(0x297A_2D39);
        h ^ (h >> 15)
    }

    /// A sprite for column `frame`, row `row` of an entry (both clamped to the grid).
    pub fn sprite(&self, entry: &BuiltinArtEntry, frame: i32, row: i32) -> SnapshotSprite {
        let column = if entry.frames > 0 { frame.clamp(0, entry.frames - 1) } else { 0 };
        let line = if entry.rows > 0 { row.clamp(0, entry.rows - 1) } else { 0 };
        SnapshotSprite {
            image_url: self.url(&entry.file),
            frame_width: f64::from(entry.w),
            frame_height: f64::from(entry.h),
            source_x: Some(f64::from(entry.x) + f64::from(column) * f64::from(entry.w)),
            source_y: Some(f64::from(entry.y) + f64::from(line) * f64::from(entry.h)),
            frame: f64::from(column),
            row: f64::from(line),
        }
    }

    /// Variant column for a tile coordinate (the animation frame when the entry is animated).
    pub fn column(entry: &BuiltinArtEntry, x: i32, y: i32, tick: f64) -> i32 {
        if entry.frames <= 1 {
            0
        } else if entry.animated() {
            entry.animation_column(tick)
        } else {
            (Self::hash(x, y) % entry.frames as u32) as i32
        }
    }

    /// Ground tile for a tile type (`grass`, `soil`, `water`, …), seasonal when the pack has it.
    pub fn tile(
        &self,
        tile_type: Option<&str>,
        season: Option<&str>,
        x: i32,
        y: i32,
        tick: f64,
    ) -> Option<SnapshotSprite> {
        let tile_type = tile_type.filter(|t| !t.is_empty())?;
        let entry = season
            .and_then(|season| self.find(&format!("tile-{tile_type}-{season}")))
            .or_else(|| self.find(&format!("tile-{tile_type}")))?;
        Some(self.sprite(entry, Self::column(entry, x, y, tick), 0))
    }

    /// Tilled soil, wet or dry.
    pub fn soil(&self, watered: bool, x: i32, y: i32) -> Option<SnapshotSprite> {
        let entry = watered.then(|| self.find("tile-soil-watered")).flatten().or_else(|| self.find("tile-soil"))?;
        Some(self.sprite(entry, Self::column(entry, x, y, 0.0), 0))
    }

    /// Fertilizer speckles drawn over soil.
    pub fn fertilized_marker(&self) -> Option<SnapshotSprite> {
        self.find("tile-soil-fertilized").map(|entry| self.sprite(entry, 0, 0))
    }

    pub fn ladder(&self) -> Option<SnapshotSprite> {
        self.find("tile-ladder").map(|entry| self.sprite(entry, 0, 0))
    }

    /// "Output ready" bubble shown above machines.
    pub fn ready_marker(&self) -> Option<SnapshotSprite> {
        self.find("fx-ready").map(|entry| self.sprite(entry, 0, 0))
    }

    /// Crop art by content id and growth stage. `stage` is the engine's stage (0 ..= `stages` − 1);
    /// it is mapped onto the sheet's stage columns so 4-, 5- and 6-stage crops all grow through
    /// the whole sheet.
    pub fn crop(
        &self,
        crop_id: Option<&str>,
        stage: i32,
        stages: i32,
        withered: bool,
        mature: bool,
    ) -> Option<SnapshotSprite> {
        if withered {
            if let Some(dead) = self.find("crop-withered") {
                return Some(self.sprite(dead, 0, 0));
            }
        }
        let entry = crop_id.and_then(|id| self.find(&format!("crop-{id}"))).or_else(|| self.find("crop-generic"))?;
        let columns = entry.stages.unwrap_or(entry.frames);
        if mature {
            return Some(self.sprite(entry, columns - 1, 0));
        }
        let last_engine_stage = (stages - 1).max(1);
        let progress = f64::from(stage.clamp(0, last_engine_stage)) / f64::from(last_engine_stage);
        // C# Math.Round: half to even.
        let column = to_int(round_half_even(progress * f64::from(columns - 1)));
        Some(self.sprite(entry, column, 0))
    }

    /// Gathering node art by node type id (a generic rock when unknown).
    pub fn node(&self, type_id: Option<&str>, x: i32, y: i32) -> Option<SnapshotSprite> {
        let entry = self.node_entry(type_id)?;
        Some(self.sprite(entry, Self::column(entry, x, y, 0.0), 0))
    }

    /// Machine art by machine type id; the `working` column while working when the sheet has one.
    pub fn machine(&self, type_id: Option<&str>, working: bool) -> Option<SnapshotSprite> {
        let entry = self.machine_entry(type_id)?;
        let column = match (&entry.states, working) {
            (Some(states), true) => states.iter().position(|state| state == "working").map_or(0, |i| i as i32),
            _ => 0,
        };
        Some(self.sprite(entry, column, 0))
    }

    /// Dropped item art by item type (`seed`, `material`, …).
    pub fn item(&self, item_type: Option<&str>) -> Option<SnapshotSprite> {
        let entry = match item_type {
            Some("seed") => self.find("item-seed"),
            Some("material" | "tool" | "fertilizer") => self.find("item-material"),
            _ => None,
        }
        .or_else(|| self.find("item-generic"))?;
        Some(self.sprite(entry, 0, 0))
    }

    /// Animal art by species id (a chicken when unknown).
    pub fn animal(
        &self,
        species_id: Option<&str>,
        direction: Option<&str>,
        tick: f64,
        moving: bool,
    ) -> Option<SnapshotSprite> {
        self.actor(self.animal_entry(species_id), direction, tick, moving)
    }

    /// NPC art by `Npc.appearance` (a generic villager when unknown).
    pub fn npc(
        &self,
        appearance: Option<&str>,
        direction: Option<&str>,
        tick: f64,
        moving: bool,
    ) -> Option<SnapshotSprite> {
        self.actor(self.npc_entry(appearance), direction, tick, moving)
    }

    pub fn player(&self, direction: Option<&str>, tick: f64, moving: bool) -> Option<SnapshotSprite> {
        self.actor(self.find("char-player").or_else(|| self.find("npc-villager")), direction, tick, moving)
    }

    /// The entry a gathering node id resolves to: exact name, else a keyword guess, else a rock.
    pub fn node_entry(&self, type_id: Option<&str>) -> Option<&BuiltinArtEntry> {
        self.exact_or_guess(
            type_id,
            &[
                ("tree", "node-tree"),
                ("stump", "node-stump"),
                ("log", "node-stump"),
                ("weed", "node-weeds"),
                ("grass", "node-weeds"),
                ("bush", "node-weeds"),
                ("fiber", "node-weeds"),
                ("boulder", "node-boulder"),
                ("copper", "node-copper-ore"),
                ("iron", "node-iron-ore"),
                ("quartz", "node-quartz"),
                ("crystal", "node-quartz"),
                ("gem", "node-quartz"),
                ("ore", "node-copper-ore"),
                ("mine", "node-mine-rock"),
            ],
            "node-rock",
        )
    }

    pub fn machine_entry(&self, type_id: Option<&str>) -> Option<&BuiltinArtEntry> {
        self.exact_or_guess(
            type_id,
            &[
                ("furnace", "machine-furnace"),
                ("forge", "machine-furnace"),
                ("kiln", "machine-furnace"),
                ("smelt", "machine-furnace"),
                ("preserve", "machine-preserves"),
                ("jar", "machine-preserves"),
                ("keg", "machine-preserves"),
                ("kitchen", "machine-kitchen"),
                ("stove", "machine-kitchen"),
                ("oven", "machine-kitchen"),
                ("cook", "machine-kitchen"),
                ("bench", "machine-workbench"),
                ("work", "machine-workbench"),
                ("carpen", "machine-workbench"),
                ("altar", "machine-altar"),
                ("magic", "machine-altar"),
                ("enchant", "machine-altar"),
            ],
            "machine-generic",
        )
    }

    pub fn animal_entry(&self, species_id: Option<&str>) -> Option<&BuiltinArtEntry> {
        self.exact_or_guess(
            species_id,
            &[
                ("chicken", "animal-chicken"),
                ("hen", "animal-chicken"),
                ("duck", "animal-chicken"),
                ("bird", "animal-chicken"),
                ("cow", "animal-cow"),
                ("sheep", "animal-cow"),
                ("goat", "animal-cow"),
                ("pig", "animal-cow"),
                ("horse", "animal-cow"),
            ],
            "animal-chicken",
        )
    }

    pub fn npc_entry(&self, appearance: Option<&str>) -> Option<&BuiltinArtEntry> {
        if let Some(appearance) = appearance.filter(|a| !a.is_empty()) {
            if let Some(exact) = self.find(&format!("npc-{appearance}")).or_else(|| self.find(appearance)) {
                return Some(exact);
            }
        }
        let id = appearance.map(str::to_lowercase).unwrap_or_default();
        let rules = [
            ("farm", "npc-farmer"),
            ("elder", "npc-farmer"),
            ("merchant", "npc-merchant"),
            ("shop", "npc-merchant"),
            ("vendor", "npc-merchant"),
        ];
        self.find(guess(&id, &rules).unwrap_or("npc-villager")).or_else(|| self.find("npc-villager"))
    }

    fn exact_or_guess(
        &self,
        id: Option<&str>,
        rules: &[(&str, &'static str)],
        fallback: &str,
    ) -> Option<&BuiltinArtEntry> {
        if let Some(exact) = id.and_then(|id| self.find(id)) {
            return Some(exact);
        }
        let lower = id.map(str::to_lowercase).unwrap_or_default();
        self.find(guess(&lower, rules).unwrap_or(fallback)).or_else(|| self.find(fallback))
    }

    fn actor(
        &self,
        entry: Option<&BuiltinArtEntry>,
        direction: Option<&str>,
        tick: f64,
        moving: bool,
    ) -> Option<SnapshotSprite> {
        let entry = entry?;
        let row = if entry.directional {
            let direction = direction.unwrap_or("down");
            DIRECTION_ROWS.iter().position(|d| *d == direction).map_or(0, |i| i as i32)
        } else {
            0
        };
        let column = if entry.animated() && (moving || entry.idle_frame.is_none()) {
            entry.animation_column(tick)
        } else {
            entry.idle_frame.unwrap_or(0)
        };
        Some(self.sprite(entry, column, row))
    }
}

/// Image source for a sheet file (`builtin://objects.png`).
pub fn sheet_url(file: &str) -> String {
    format!("{URL_SCHEME}{file}")
}

fn guess(id: &str, rules: &[(&str, &'static str)]) -> Option<&'static str> {
    rules.iter().find(|(keyword, _)| id.contains(keyword)).map(|(_, entry)| *entry)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn art() -> &'static BuiltinArt {
        BuiltinArt::embedded()
    }

    #[test]
    fn manifest_loads_and_every_entry_lies_inside_its_sheet() {
        let art = art();
        assert_eq!(art.tile_size(), 32);
        assert_eq!(art.manifest().palette.len(), 48);
        for sheet in &art.manifest().sheets {
            let bytes = art.sheet_bytes(&sheet.file).expect("sheet bytes");
            let image = crate::images::decode_image(bytes).expect("sheet decodes");
            assert_eq!((image.width() as i32, image.height() as i32), (sheet.w, sheet.h), "{}", sheet.file);
        }
        for entry in art.entries() {
            let sheet = art.manifest().sheets.iter().find(|s| s.file == entry.file).expect("known sheet");
            assert!(entry.w > 0 && entry.h > 0 && entry.frames > 0 && entry.rows > 0, "{}", entry.name);
            assert!(entry.x + entry.w * entry.frames <= sheet.w, "{} overflows horizontally", entry.name);
            assert!(entry.y + entry.h * entry.rows <= sheet.h, "{} overflows vertically", entry.name);
            assert_eq!(entry.directional, entry.rows == 4, "{}", entry.name);
        }
        assert!(BuiltinArt::resolve_sheet("builtin://tiles.png").is_some());
        assert!(BuiltinArt::resolve_sheet("builtin://nope.png").is_none());
        assert!(BuiltinArt::resolve_sheet("data:tiles.png").is_none());
    }

    #[test]
    fn unknown_ids_fall_back_to_generic_sprites() {
        let art = art();
        let crop_name = |id: &str| {
            let sprite = art.crop(Some(id), 0, 4, false, false).unwrap();
            art.entries()
                .find(|e| {
                    sheet_url(&e.file) == *sprite.image_url
                        && Some(f64::from(e.x)) == sprite.source_x
                        && Some(f64::from(e.y)) == sprite.source_y
                })
                .unwrap()
                .name
                .clone()
        };
        assert_eq!(crop_name("mod-dragonfruit"), "crop-generic");
        assert_eq!(art.node_entry(Some("mod-strange-thing")).unwrap().name, "node-rock");
        assert_eq!(art.node_entry(Some("mod-oak-tree")).unwrap().name, "node-tree");
        assert_eq!(art.node_entry(Some("mod-bramble-bush")).unwrap().name, "node-weeds");
        assert_eq!(art.node_entry(Some("Mod-IRON-Vein")).unwrap().name, "node-iron-ore");
        assert_eq!(art.node_entry(None).unwrap().name, "node-rock");
        assert_eq!(art.machine_entry(Some("mod-quantum-box")).unwrap().name, "machine-generic");
        assert_eq!(art.machine_entry(Some("mod-blast-furnace")).unwrap().name, "machine-furnace");
        assert_eq!(art.animal_entry(Some("mod-axolotl")).unwrap().name, "animal-chicken");
        assert_eq!(art.animal_entry(Some("mod-sheep")).unwrap().name, "animal-cow");
        assert_eq!(art.npc_entry(Some("wizard")).unwrap().name, "npc-villager");
        assert_eq!(art.npc_entry(Some("")).unwrap().name, "npc-villager");
        assert_eq!(art.npc_entry(Some("shopkeeper")).unwrap().name, "npc-merchant");
        assert_eq!(art.npc_entry(Some("farmer")).unwrap().name, "npc-farmer");
        assert!(art.item(Some("mystery")).is_some());
        assert!(art.tile(Some("lava"), None, 0, 0, 0.0).is_none());
        assert!(art.tile(Some(""), None, 0, 0, 0.0).is_none());
    }

    #[test]
    fn walk_cycles_pick_frames_from_the_tick_and_idle_when_still() {
        let art = art();
        let entry = art.find("char-player").unwrap();
        assert!(entry.directional);
        assert_eq!(entry.frames, 4);
        let ticks = f64::from(entry.ticks_per_frame.unwrap());
        let idle = art.player(Some("left"), ticks * 3.0, false).unwrap();
        assert_eq!((idle.frame, idle.row), (f64::from(entry.idle_frame.unwrap_or(0)), 1.0));
        let walking = art.player(Some("up"), ticks * 3.0, true).unwrap();
        assert_eq!((walking.frame, walking.row), (3.0, 3.0));
        assert_eq!(art.player(Some("down"), ticks * 4.0, true).unwrap().frame, 0.0);
        assert_eq!(art.player(Some("sideways"), 0.0, false).unwrap().row, 0.0);
        assert_eq!(walking.source_x, Some(f64::from(entry.x + 3 * entry.w)));
        assert_eq!(walking.source_y, Some(f64::from(entry.y + 3 * entry.h)));
    }

    #[test]
    fn variants_come_from_the_tile_coordinate_and_water_from_the_tick() {
        let art = art();
        let grass = art.find("tile-grass").unwrap();
        assert!(grass.frames > 1);
        let mut columns: Vec<i32> = (0..40).map(|i| BuiltinArt::column(grass, i, i * 7, 0.0)).collect();
        columns.sort();
        columns.dedup();
        assert!(columns.len() > 1);
        assert_eq!(BuiltinArt::column(grass, 5, 9, 0.0), BuiltinArt::column(grass, 5, 9, 999.0));
        let water = art.find("tile-water").unwrap();
        assert!(water.animated());
        let ticks = f64::from(water.ticks_per_frame.unwrap());
        assert_eq!(BuiltinArt::column(water, 0, 0, 0.0), 0);
        assert_eq!(BuiltinArt::column(water, 0, 0, ticks), 1);
        assert_eq!(BuiltinArt::column(water, 0, 0, ticks * f64::from(water.frames)), 0);
        assert_eq!(BuiltinArt::column(water, 0, 0, -50.0), 0);
        // Seasonal grass exists and differs from the plain tile.
        let spring = art.tile(Some("grass"), Some("winter"), 1, 1, 0.0).unwrap();
        let plain = art.tile(Some("grass"), None, 1, 1, 0.0).unwrap();
        assert_ne!(spring.source_y, plain.source_y);
        // Negative coordinates hash like the C# (uint)int casts (two's complement).
        assert_eq!(BuiltinArt::hash(-1, 0), 0x53b5_4b41);
        assert_eq!(BuiltinArt::hash(3, 7), 0x45f1_286c);
    }

    #[test]
    fn crop_stages_map_onto_the_sheet_and_mature_shows_the_last_column() {
        let art = art();
        let wheat = art.find("crop-wheat").unwrap();
        assert_eq!(wheat.frames, 5);
        assert_eq!(art.crop(Some("wheat"), 0, 4, false, false).unwrap().frame, 0.0);
        assert_eq!(art.crop(Some("wheat"), 3, 4, false, false).unwrap().frame, 4.0);
        assert_eq!(art.crop(Some("wheat"), 1, 4, false, true).unwrap().frame, 4.0);
        // 1/3 × 4 = 1.33 → 1; 2/3 × 4 = 2.67 → 3.
        assert_eq!(art.crop(Some("wheat"), 1, 4, false, false).unwrap().frame, 1.0);
        assert_eq!(art.crop(Some("wheat"), 2, 4, false, false).unwrap().frame, 3.0);
        // Stage 1 of 3 on 5 columns is exactly column 2.
        assert_eq!(art.crop(Some("wheat"), 1, 3, false, false).unwrap().frame, 2.0);
        let withered = art.crop(Some("wheat"), 2, 4, true, false).unwrap();
        let dead = art.find("crop-withered").unwrap();
        assert_eq!(&*withered.image_url, sheet_url(&dead.file));
        assert_eq!(withered.source_x, Some(f64::from(dead.x)));
    }

    #[test]
    fn machines_show_their_working_column() {
        let art = art();
        let furnace = art.machine_entry(Some("furnace")).unwrap();
        let working = art.machine(Some("furnace"), true).unwrap();
        let idle = art.machine(Some("furnace"), false).unwrap();
        assert_eq!(idle.frame, 0.0);
        let expected = furnace.states.as_ref().and_then(|s| s.iter().position(|x| x == "working")).unwrap_or(0);
        assert_eq!(working.frame, expected as f64);
    }

    #[test]
    fn sprites_share_the_sheet_url() {
        let art = art();
        let a = art.tile(Some("grass"), None, 0, 0, 0.0).unwrap();
        let b = art.tile(Some("grass"), None, 3, 2, 0.0).unwrap();
        assert!(Arc::ptr_eq(&a.image_url, &b.image_url));
    }
}
