// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod farm_engine {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod cart {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum GameInfoOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct GameInfo<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for GameInfo<'a> {
  type Inner = GameInfo<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> GameInfo<'a> {
  pub const VT_TITLE: flatbuffers::VOffsetT = 4;
  pub const VT_VERSION: flatbuffers::VOffsetT = 6;
  pub const VT_GAME_ID: flatbuffers::VOffsetT = 8;
  pub const VT_AUTHOR: flatbuffers::VOffsetT = 10;
  pub const VT_COMPANY: flatbuffers::VOffsetT = 12;
  pub const VT_EXECUTABLE_NAME: flatbuffers::VOffsetT = 14;
  pub const VT_WINDOW_WIDTH: flatbuffers::VOffsetT = 16;
  pub const VT_WINDOW_HEIGHT: flatbuffers::VOffsetT = 18;
  pub const VT_FULLSCREEN: flatbuffers::VOffsetT = 20;
  pub const VT_PIXEL_SCALE: flatbuffers::VOffsetT = 22;
  pub const VT_CREDITS: flatbuffers::VOffsetT = 24;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    GameInfo { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args GameInfoArgs<'args>
  ) -> flatbuffers::WIPOffset<GameInfo<'bldr>> {
    let mut builder = GameInfoBuilder::new(_fbb);
    if let Some(x) = args.credits { builder.add_credits(x); }
    if let Some(x) = args.pixel_scale { builder.add_pixel_scale(x); }
    builder.add_window_height(args.window_height);
    builder.add_window_width(args.window_width);
    if let Some(x) = args.executable_name { builder.add_executable_name(x); }
    if let Some(x) = args.company { builder.add_company(x); }
    if let Some(x) = args.author { builder.add_author(x); }
    if let Some(x) = args.game_id { builder.add_game_id(x); }
    if let Some(x) = args.version { builder.add_version(x); }
    if let Some(x) = args.title { builder.add_title(x); }
    builder.add_fullscreen(args.fullscreen);
    builder.finish()
  }


  #[inline]
  pub fn title(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GameInfo::VT_TITLE, None).unwrap()}
  }
  #[inline]
  pub fn version(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GameInfo::VT_VERSION, None).unwrap()}
  }
  #[inline]
  pub fn game_id(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GameInfo::VT_GAME_ID, None).unwrap()}
  }
  #[inline]
  pub fn author(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GameInfo::VT_AUTHOR, None)}
  }
  #[inline]
  pub fn company(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GameInfo::VT_COMPANY, None)}
  }
  #[inline]
  pub fn executable_name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GameInfo::VT_EXECUTABLE_NAME, None)}
  }
  #[inline]
  pub fn window_width(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(GameInfo::VT_WINDOW_WIDTH, Some(1280)).unwrap()}
  }
  #[inline]
  pub fn window_height(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(GameInfo::VT_WINDOW_HEIGHT, Some(800)).unwrap()}
  }
  #[inline]
  pub fn fullscreen(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(GameInfo::VT_FULLSCREEN, Some(false)).unwrap()}
  }
  #[inline]
  pub fn pixel_scale(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GameInfo::VT_PIXEL_SCALE, None)}
  }
  #[inline]
  pub fn credits(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GameInfo::VT_CREDITS, None)}
  }
}

impl flatbuffers::Verifiable for GameInfo<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("title", Self::VT_TITLE, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("version", Self::VT_VERSION, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("game_id", Self::VT_GAME_ID, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("author", Self::VT_AUTHOR, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("company", Self::VT_COMPANY, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("executable_name", Self::VT_EXECUTABLE_NAME, false)?
     .visit_field::<u32>("window_width", Self::VT_WINDOW_WIDTH, false)?
     .visit_field::<u32>("window_height", Self::VT_WINDOW_HEIGHT, false)?
     .visit_field::<bool>("fullscreen", Self::VT_FULLSCREEN, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("pixel_scale", Self::VT_PIXEL_SCALE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("credits", Self::VT_CREDITS, false)?
     .finish();
    Ok(())
  }
}
pub struct GameInfoArgs<'a> {
    pub title: Option<flatbuffers::WIPOffset<&'a str>>,
    pub version: Option<flatbuffers::WIPOffset<&'a str>>,
    pub game_id: Option<flatbuffers::WIPOffset<&'a str>>,
    pub author: Option<flatbuffers::WIPOffset<&'a str>>,
    pub company: Option<flatbuffers::WIPOffset<&'a str>>,
    pub executable_name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub window_width: u32,
    pub window_height: u32,
    pub fullscreen: bool,
    pub pixel_scale: Option<flatbuffers::WIPOffset<&'a str>>,
    pub credits: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for GameInfoArgs<'a> {
  #[inline]
  fn default() -> Self {
    GameInfoArgs {
      title: None, // required field
      version: None, // required field
      game_id: None, // required field
      author: None,
      company: None,
      executable_name: None,
      window_width: 1280,
      window_height: 800,
      fullscreen: false,
      pixel_scale: None,
      credits: None,
    }
  }
}

pub struct GameInfoBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> GameInfoBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_title(&mut self, title: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GameInfo::VT_TITLE, title);
  }
  #[inline]
  pub fn add_version(&mut self, version: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GameInfo::VT_VERSION, version);
  }
  #[inline]
  pub fn add_game_id(&mut self, game_id: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GameInfo::VT_GAME_ID, game_id);
  }
  #[inline]
  pub fn add_author(&mut self, author: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GameInfo::VT_AUTHOR, author);
  }
  #[inline]
  pub fn add_company(&mut self, company: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GameInfo::VT_COMPANY, company);
  }
  #[inline]
  pub fn add_executable_name(&mut self, executable_name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GameInfo::VT_EXECUTABLE_NAME, executable_name);
  }
  #[inline]
  pub fn add_window_width(&mut self, window_width: u32) {
    self.fbb_.push_slot::<u32>(GameInfo::VT_WINDOW_WIDTH, window_width, 1280);
  }
  #[inline]
  pub fn add_window_height(&mut self, window_height: u32) {
    self.fbb_.push_slot::<u32>(GameInfo::VT_WINDOW_HEIGHT, window_height, 800);
  }
  #[inline]
  pub fn add_fullscreen(&mut self, fullscreen: bool) {
    self.fbb_.push_slot::<bool>(GameInfo::VT_FULLSCREEN, fullscreen, false);
  }
  #[inline]
  pub fn add_pixel_scale(&mut self, pixel_scale: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GameInfo::VT_PIXEL_SCALE, pixel_scale);
  }
  #[inline]
  pub fn add_credits(&mut self, credits: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GameInfo::VT_CREDITS, credits);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> GameInfoBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    GameInfoBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<GameInfo<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, GameInfo::VT_TITLE,"title");
    self.fbb_.required(o, GameInfo::VT_VERSION,"version");
    self.fbb_.required(o, GameInfo::VT_GAME_ID,"game_id");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for GameInfo<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("GameInfo");
      ds.field("title", &self.title());
      ds.field("version", &self.version());
      ds.field("game_id", &self.game_id());
      ds.field("author", &self.author());
      ds.field("company", &self.company());
      ds.field("executable_name", &self.executable_name());
      ds.field("window_width", &self.window_width());
      ds.field("window_height", &self.window_height());
      ds.field("fullscreen", &self.fullscreen());
      ds.field("pixel_scale", &self.pixel_scale());
      ds.field("credits", &self.credits());
      ds.finish()
  }
}
pub enum AssetOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Asset<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Asset<'a> {
  type Inner = Asset<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Asset<'a> {
  pub const VT_ID: flatbuffers::VOffsetT = 4;
  pub const VT_MIME: flatbuffers::VOffsetT = 6;
  pub const VT_DATA: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Asset { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args AssetArgs<'args>
  ) -> flatbuffers::WIPOffset<Asset<'bldr>> {
    let mut builder = AssetBuilder::new(_fbb);
    if let Some(x) = args.data { builder.add_data(x); }
    if let Some(x) = args.mime { builder.add_mime(x); }
    if let Some(x) = args.id { builder.add_id(x); }
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Asset::VT_ID, None).unwrap()}
  }
  #[inline]
  pub fn key_compare_less_than(&self, o: &Asset) -> bool {
    self.id() < o.id()
  }

  #[inline]
  pub fn key_compare_with_value(&self, val: & str) -> ::core::cmp::Ordering {
    let key = self.id();
    key.cmp(val)
  }
  #[inline]
  pub fn mime(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Asset::VT_MIME, None).unwrap()}
  }
  #[inline]
  pub fn data(&self) -> flatbuffers::Vector<'a, u8> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(Asset::VT_DATA, None).unwrap()}
  }
}

impl flatbuffers::Verifiable for Asset<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("id", Self::VT_ID, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("mime", Self::VT_MIME, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("data", Self::VT_DATA, true)?
     .finish();
    Ok(())
  }
}
pub struct AssetArgs<'a> {
    pub id: Option<flatbuffers::WIPOffset<&'a str>>,
    pub mime: Option<flatbuffers::WIPOffset<&'a str>>,
    pub data: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for AssetArgs<'a> {
  #[inline]
  fn default() -> Self {
    AssetArgs {
      id: None, // required field
      mime: None, // required field
      data: None, // required field
    }
  }
}

pub struct AssetBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> AssetBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_id(&mut self, id: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Asset::VT_ID, id);
  }
  #[inline]
  pub fn add_mime(&mut self, mime: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Asset::VT_MIME, mime);
  }
  #[inline]
  pub fn add_data(&mut self, data: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Asset::VT_DATA, data);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> AssetBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    AssetBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Asset<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Asset::VT_ID,"id");
    self.fbb_.required(o, Asset::VT_MIME,"mime");
    self.fbb_.required(o, Asset::VT_DATA,"data");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Asset<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Asset");
      ds.field("id", &self.id());
      ds.field("mime", &self.mime());
      ds.field("data", &self.data());
      ds.finish()
  }
}
pub enum CartridgeOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Cartridge<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Cartridge<'a> {
  type Inner = Cartridge<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Cartridge<'a> {
  pub const VT_CART_FORMAT: flatbuffers::VOffsetT = 4;
  pub const VT_PROJECT_SCHEMA_VERSION: flatbuffers::VOffsetT = 6;
  pub const VT_INFO: flatbuffers::VOffsetT = 8;
  pub const VT_CONTENT_JSON: flatbuffers::VOffsetT = 12;
  pub const VT_START_JSON: flatbuffers::VOffsetT = 14;
  pub const VT_PRESENTATION_JSON: flatbuffers::VOffsetT = 16;
  pub const VT_ASSETS: flatbuffers::VOffsetT = 18;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Cartridge { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args CartridgeArgs<'args>
  ) -> flatbuffers::WIPOffset<Cartridge<'bldr>> {
    let mut builder = CartridgeBuilder::new(_fbb);
    if let Some(x) = args.assets { builder.add_assets(x); }
    if let Some(x) = args.presentation_json { builder.add_presentation_json(x); }
    if let Some(x) = args.start_json { builder.add_start_json(x); }
    if let Some(x) = args.content_json { builder.add_content_json(x); }
    if let Some(x) = args.info { builder.add_info(x); }
    builder.add_project_schema_version(args.project_schema_version);
    builder.add_cart_format(args.cart_format);
    builder.finish()
  }


  #[inline]
  pub fn cart_format(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Cartridge::VT_CART_FORMAT, Some(0)).unwrap()}
  }
  #[inline]
  pub fn project_schema_version(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Cartridge::VT_PROJECT_SCHEMA_VERSION, Some(0)).unwrap()}
  }
  #[inline]
  pub fn info(&self) -> GameInfo<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<GameInfo>>(Cartridge::VT_INFO, None).unwrap()}
  }
  #[inline]
  pub fn content_json(&self) -> flatbuffers::Vector<'a, u8> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(Cartridge::VT_CONTENT_JSON, None).unwrap()}
  }
  #[inline]
  pub fn start_json(&self) -> flatbuffers::Vector<'a, u8> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(Cartridge::VT_START_JSON, None).unwrap()}
  }
  #[inline]
  pub fn presentation_json(&self) -> flatbuffers::Vector<'a, u8> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(Cartridge::VT_PRESENTATION_JSON, None).unwrap()}
  }
  #[inline]
  pub fn assets(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Asset<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Asset>>>>(Cartridge::VT_ASSETS, None)}
  }
}

impl flatbuffers::Verifiable for Cartridge<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u32>("cart_format", Self::VT_CART_FORMAT, false)?
     .visit_field::<u32>("project_schema_version", Self::VT_PROJECT_SCHEMA_VERSION, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<GameInfo>>("info", Self::VT_INFO, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("content_json", Self::VT_CONTENT_JSON, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("start_json", Self::VT_START_JSON, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("presentation_json", Self::VT_PRESENTATION_JSON, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Asset>>>>("assets", Self::VT_ASSETS, false)?
     .finish();
    Ok(())
  }
}
pub struct CartridgeArgs<'a> {
    pub cart_format: u32,
    pub project_schema_version: u32,
    pub info: Option<flatbuffers::WIPOffset<GameInfo<'a>>>,
    pub content_json: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub start_json: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub presentation_json: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub assets: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Asset<'a>>>>>,
}
impl<'a> Default for CartridgeArgs<'a> {
  #[inline]
  fn default() -> Self {
    CartridgeArgs {
      cart_format: 0,
      project_schema_version: 0,
      info: None, // required field
      content_json: None, // required field
      start_json: None, // required field
      presentation_json: None, // required field
      assets: None,
    }
  }
}

pub struct CartridgeBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> CartridgeBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_cart_format(&mut self, cart_format: u32) {
    self.fbb_.push_slot::<u32>(Cartridge::VT_CART_FORMAT, cart_format, 0);
  }
  #[inline]
  pub fn add_project_schema_version(&mut self, project_schema_version: u32) {
    self.fbb_.push_slot::<u32>(Cartridge::VT_PROJECT_SCHEMA_VERSION, project_schema_version, 0);
  }
  #[inline]
  pub fn add_info(&mut self, info: flatbuffers::WIPOffset<GameInfo<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<GameInfo>>(Cartridge::VT_INFO, info);
  }
  #[inline]
  pub fn add_content_json(&mut self, content_json: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Cartridge::VT_CONTENT_JSON, content_json);
  }
  #[inline]
  pub fn add_start_json(&mut self, start_json: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Cartridge::VT_START_JSON, start_json);
  }
  #[inline]
  pub fn add_presentation_json(&mut self, presentation_json: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Cartridge::VT_PRESENTATION_JSON, presentation_json);
  }
  #[inline]
  pub fn add_assets(&mut self, assets: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Asset<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Cartridge::VT_ASSETS, assets);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> CartridgeBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    CartridgeBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Cartridge<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Cartridge::VT_INFO,"info");
    self.fbb_.required(o, Cartridge::VT_CONTENT_JSON,"content_json");
    self.fbb_.required(o, Cartridge::VT_START_JSON,"start_json");
    self.fbb_.required(o, Cartridge::VT_PRESENTATION_JSON,"presentation_json");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Cartridge<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Cartridge");
      ds.field("cart_format", &self.cart_format());
      ds.field("project_schema_version", &self.project_schema_version());
      ds.field("info", &self.info());
      ds.field("content_json", &self.content_json());
      ds.field("start_json", &self.start_json());
      ds.field("presentation_json", &self.presentation_json());
      ds.field("assets", &self.assets());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Cartridge`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_cartridge_unchecked`.
pub fn root_as_cartridge(buf: &[u8]) -> Result<Cartridge, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Cartridge>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Cartridge` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_cartridge_unchecked`.
pub fn size_prefixed_root_as_cartridge(buf: &[u8]) -> Result<Cartridge, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Cartridge>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Cartridge` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_cartridge_unchecked`.
pub fn root_as_cartridge_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Cartridge<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Cartridge<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Cartridge` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_cartridge_unchecked`.
pub fn size_prefixed_root_as_cartridge_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Cartridge<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Cartridge<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Cartridge and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Cartridge`.
pub unsafe fn root_as_cartridge_unchecked(buf: &[u8]) -> Cartridge {
  flatbuffers::root_unchecked::<Cartridge>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Cartridge and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Cartridge`.
pub unsafe fn size_prefixed_root_as_cartridge_unchecked(buf: &[u8]) -> Cartridge {
  flatbuffers::size_prefixed_root_unchecked::<Cartridge>(buf)
}
pub const CARTRIDGE_IDENTIFIER: &str = "FGCT";

#[inline]
pub fn cartridge_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, CARTRIDGE_IDENTIFIER, false)
}

#[inline]
pub fn cartridge_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, CARTRIDGE_IDENTIFIER, true)
}

#[inline]
pub fn finish_cartridge_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<Cartridge<'a>>) {
  fbb.finish(root, Some(CARTRIDGE_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_cartridge_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<Cartridge<'a>>) {
  fbb.finish_size_prefixed(root, Some(CARTRIDGE_IDENTIFIER));
}
}  // pub mod Cart
}  // pub mod FarmEngine

