// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod farm_engine {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod save {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum SavePreviewOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SavePreview<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for SavePreview<'a> {
  type Inner = SavePreview<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> SavePreview<'a> {
  pub const VT_FARM_NAME: flatbuffers::VOffsetT = 4;
  pub const VT_DAY: flatbuffers::VOffsetT = 6;
  pub const VT_SEASON: flatbuffers::VOffsetT = 8;
  pub const VT_YEAR: flatbuffers::VOffsetT = 10;
  pub const VT_MONEY: flatbuffers::VOffsetT = 12;
  pub const VT_PLAY_SECONDS: flatbuffers::VOffsetT = 14;
  pub const VT_SAVED_AT: flatbuffers::VOffsetT = 16;
  pub const VT_THUMBNAIL_PNG: flatbuffers::VOffsetT = 18;
  pub const VT_DAY_OF_SEASON: flatbuffers::VOffsetT = 20;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    SavePreview { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SavePreviewArgs<'args>
  ) -> flatbuffers::WIPOffset<SavePreview<'bldr>> {
    let mut builder = SavePreviewBuilder::new(_fbb);
    builder.add_day_of_season(args.day_of_season);
    builder.add_saved_at(args.saved_at);
    builder.add_play_seconds(args.play_seconds);
    builder.add_money(args.money);
    builder.add_year(args.year);
    builder.add_day(args.day);
    if let Some(x) = args.thumbnail_png { builder.add_thumbnail_png(x); }
    if let Some(x) = args.season { builder.add_season(x); }
    if let Some(x) = args.farm_name { builder.add_farm_name(x); }
    builder.finish()
  }


  #[inline]
  pub fn farm_name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(SavePreview::VT_FARM_NAME, None)}
  }
  #[inline]
  pub fn day(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(SavePreview::VT_DAY, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn season(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(SavePreview::VT_SEASON, None)}
  }
  #[inline]
  pub fn year(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(SavePreview::VT_YEAR, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn money(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(SavePreview::VT_MONEY, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn play_seconds(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(SavePreview::VT_PLAY_SECONDS, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn saved_at(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(SavePreview::VT_SAVED_AT, Some(0)).unwrap()}
  }
  #[inline]
  pub fn thumbnail_png(&self) -> Option<flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(SavePreview::VT_THUMBNAIL_PNG, None)}
  }
  #[inline]
  pub fn day_of_season(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(SavePreview::VT_DAY_OF_SEASON, Some(0.0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for SavePreview<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("farm_name", Self::VT_FARM_NAME, false)?
     .visit_field::<f64>("day", Self::VT_DAY, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("season", Self::VT_SEASON, false)?
     .visit_field::<f64>("year", Self::VT_YEAR, false)?
     .visit_field::<f64>("money", Self::VT_MONEY, false)?
     .visit_field::<f64>("play_seconds", Self::VT_PLAY_SECONDS, false)?
     .visit_field::<i64>("saved_at", Self::VT_SAVED_AT, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("thumbnail_png", Self::VT_THUMBNAIL_PNG, false)?
     .visit_field::<f64>("day_of_season", Self::VT_DAY_OF_SEASON, false)?
     .finish();
    Ok(())
  }
}
pub struct SavePreviewArgs<'a> {
    pub farm_name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub day: f64,
    pub season: Option<flatbuffers::WIPOffset<&'a str>>,
    pub year: f64,
    pub money: f64,
    pub play_seconds: f64,
    pub saved_at: i64,
    pub thumbnail_png: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub day_of_season: f64,
}
impl<'a> Default for SavePreviewArgs<'a> {
  #[inline]
  fn default() -> Self {
    SavePreviewArgs {
      farm_name: None,
      day: 0.0,
      season: None,
      year: 0.0,
      money: 0.0,
      play_seconds: 0.0,
      saved_at: 0,
      thumbnail_png: None,
      day_of_season: 0.0,
    }
  }
}

pub struct SavePreviewBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> SavePreviewBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_farm_name(&mut self, farm_name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SavePreview::VT_FARM_NAME, farm_name);
  }
  #[inline]
  pub fn add_day(&mut self, day: f64) {
    self.fbb_.push_slot::<f64>(SavePreview::VT_DAY, day, 0.0);
  }
  #[inline]
  pub fn add_season(&mut self, season: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SavePreview::VT_SEASON, season);
  }
  #[inline]
  pub fn add_year(&mut self, year: f64) {
    self.fbb_.push_slot::<f64>(SavePreview::VT_YEAR, year, 0.0);
  }
  #[inline]
  pub fn add_money(&mut self, money: f64) {
    self.fbb_.push_slot::<f64>(SavePreview::VT_MONEY, money, 0.0);
  }
  #[inline]
  pub fn add_play_seconds(&mut self, play_seconds: f64) {
    self.fbb_.push_slot::<f64>(SavePreview::VT_PLAY_SECONDS, play_seconds, 0.0);
  }
  #[inline]
  pub fn add_saved_at(&mut self, saved_at: i64) {
    self.fbb_.push_slot::<i64>(SavePreview::VT_SAVED_AT, saved_at, 0);
  }
  #[inline]
  pub fn add_thumbnail_png(&mut self, thumbnail_png: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SavePreview::VT_THUMBNAIL_PNG, thumbnail_png);
  }
  #[inline]
  pub fn add_day_of_season(&mut self, day_of_season: f64) {
    self.fbb_.push_slot::<f64>(SavePreview::VT_DAY_OF_SEASON, day_of_season, 0.0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> SavePreviewBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SavePreviewBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<SavePreview<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for SavePreview<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("SavePreview");
      ds.field("farm_name", &self.farm_name());
      ds.field("day", &self.day());
      ds.field("season", &self.season());
      ds.field("year", &self.year());
      ds.field("money", &self.money());
      ds.field("play_seconds", &self.play_seconds());
      ds.field("saved_at", &self.saved_at());
      ds.field("thumbnail_png", &self.thumbnail_png());
      ds.field("day_of_season", &self.day_of_season());
      ds.finish()
  }
}
pub enum SaveFileOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SaveFile<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for SaveFile<'a> {
  type Inner = SaveFile<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> SaveFile<'a> {
  pub const VT_SAVE_FORMAT: flatbuffers::VOffsetT = 4;
  pub const VT_GAME_ID: flatbuffers::VOffsetT = 6;
  pub const VT_GAME_VERSION: flatbuffers::VOffsetT = 8;
  pub const VT_CART_HASH: flatbuffers::VOffsetT = 10;
  pub const VT_PREVIEW: flatbuffers::VOffsetT = 12;
  pub const VT_COMPRESSION: flatbuffers::VOffsetT = 14;
  pub const VT_STATE: flatbuffers::VOffsetT = 16;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    SaveFile { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SaveFileArgs<'args>
  ) -> flatbuffers::WIPOffset<SaveFile<'bldr>> {
    let mut builder = SaveFileBuilder::new(_fbb);
    if let Some(x) = args.state { builder.add_state(x); }
    if let Some(x) = args.preview { builder.add_preview(x); }
    if let Some(x) = args.cart_hash { builder.add_cart_hash(x); }
    if let Some(x) = args.game_version { builder.add_game_version(x); }
    if let Some(x) = args.game_id { builder.add_game_id(x); }
    builder.add_save_format(args.save_format);
    builder.add_compression(args.compression);
    builder.finish()
  }


  #[inline]
  pub fn save_format(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(SaveFile::VT_SAVE_FORMAT, Some(0)).unwrap()}
  }
  #[inline]
  pub fn game_id(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(SaveFile::VT_GAME_ID, None).unwrap()}
  }
  #[inline]
  pub fn game_version(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(SaveFile::VT_GAME_VERSION, None).unwrap()}
  }
  #[inline]
  pub fn cart_hash(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(SaveFile::VT_CART_HASH, None).unwrap()}
  }
  #[inline]
  pub fn preview(&self) -> Option<SavePreview<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<SavePreview>>(SaveFile::VT_PREVIEW, None)}
  }
  #[inline]
  pub fn compression(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(SaveFile::VT_COMPRESSION, Some(0)).unwrap()}
  }
  #[inline]
  pub fn state(&self) -> flatbuffers::Vector<'a, u8> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(SaveFile::VT_STATE, None).unwrap()}
  }
}

impl flatbuffers::Verifiable for SaveFile<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u32>("save_format", Self::VT_SAVE_FORMAT, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("game_id", Self::VT_GAME_ID, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("game_version", Self::VT_GAME_VERSION, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("cart_hash", Self::VT_CART_HASH, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<SavePreview>>("preview", Self::VT_PREVIEW, false)?
     .visit_field::<u8>("compression", Self::VT_COMPRESSION, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("state", Self::VT_STATE, true)?
     .finish();
    Ok(())
  }
}
pub struct SaveFileArgs<'a> {
    pub save_format: u32,
    pub game_id: Option<flatbuffers::WIPOffset<&'a str>>,
    pub game_version: Option<flatbuffers::WIPOffset<&'a str>>,
    pub cart_hash: Option<flatbuffers::WIPOffset<&'a str>>,
    pub preview: Option<flatbuffers::WIPOffset<SavePreview<'a>>>,
    pub compression: u8,
    pub state: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for SaveFileArgs<'a> {
  #[inline]
  fn default() -> Self {
    SaveFileArgs {
      save_format: 0,
      game_id: None, // required field
      game_version: None, // required field
      cart_hash: None, // required field
      preview: None,
      compression: 0,
      state: None, // required field
    }
  }
}

pub struct SaveFileBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> SaveFileBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_save_format(&mut self, save_format: u32) {
    self.fbb_.push_slot::<u32>(SaveFile::VT_SAVE_FORMAT, save_format, 0);
  }
  #[inline]
  pub fn add_game_id(&mut self, game_id: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SaveFile::VT_GAME_ID, game_id);
  }
  #[inline]
  pub fn add_game_version(&mut self, game_version: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SaveFile::VT_GAME_VERSION, game_version);
  }
  #[inline]
  pub fn add_cart_hash(&mut self, cart_hash: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SaveFile::VT_CART_HASH, cart_hash);
  }
  #[inline]
  pub fn add_preview(&mut self, preview: flatbuffers::WIPOffset<SavePreview<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<SavePreview>>(SaveFile::VT_PREVIEW, preview);
  }
  #[inline]
  pub fn add_compression(&mut self, compression: u8) {
    self.fbb_.push_slot::<u8>(SaveFile::VT_COMPRESSION, compression, 0);
  }
  #[inline]
  pub fn add_state(&mut self, state: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SaveFile::VT_STATE, state);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> SaveFileBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SaveFileBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<SaveFile<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, SaveFile::VT_GAME_ID,"game_id");
    self.fbb_.required(o, SaveFile::VT_GAME_VERSION,"game_version");
    self.fbb_.required(o, SaveFile::VT_CART_HASH,"cart_hash");
    self.fbb_.required(o, SaveFile::VT_STATE,"state");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for SaveFile<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("SaveFile");
      ds.field("save_format", &self.save_format());
      ds.field("game_id", &self.game_id());
      ds.field("game_version", &self.game_version());
      ds.field("cart_hash", &self.cart_hash());
      ds.field("preview", &self.preview());
      ds.field("compression", &self.compression());
      ds.field("state", &self.state());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `SaveFile`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_save_file_unchecked`.
pub fn root_as_save_file(buf: &[u8]) -> Result<SaveFile, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<SaveFile>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `SaveFile` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_save_file_unchecked`.
pub fn size_prefixed_root_as_save_file(buf: &[u8]) -> Result<SaveFile, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<SaveFile>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `SaveFile` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_save_file_unchecked`.
pub fn root_as_save_file_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<SaveFile<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<SaveFile<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `SaveFile` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_save_file_unchecked`.
pub fn size_prefixed_root_as_save_file_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<SaveFile<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<SaveFile<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a SaveFile and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `SaveFile`.
pub unsafe fn root_as_save_file_unchecked(buf: &[u8]) -> SaveFile {
  flatbuffers::root_unchecked::<SaveFile>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed SaveFile and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `SaveFile`.
pub unsafe fn size_prefixed_root_as_save_file_unchecked(buf: &[u8]) -> SaveFile {
  flatbuffers::size_prefixed_root_unchecked::<SaveFile>(buf)
}
pub const SAVE_FILE_IDENTIFIER: &str = "FGSV";

#[inline]
pub fn save_file_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, SAVE_FILE_IDENTIFIER, false)
}

#[inline]
pub fn save_file_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, SAVE_FILE_IDENTIFIER, true)
}

#[inline]
pub fn finish_save_file_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<SaveFile<'a>>) {
  fbb.finish(root, Some(SAVE_FILE_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_save_file_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<SaveFile<'a>>) {
  fbb.finish_size_prefixed(root, Some(SAVE_FILE_IDENTIFIER));
}
}  // pub mod Save
}  // pub mod FarmEngine

