//! Parity of the RNG, stable JSON and hash primitives with the TypeScript reference engine.
//! Fixtures come from `fixtures/golden` (generated by `tools/golden/generate.sh`).

use farm_sim::rng::{self, Rng};
use farm_sim::{hash_text, stable_json};
use serde_json::Value;
use std::path::PathBuf;

fn golden(relative: &str) -> Value {
    let path: PathBuf = [env!("CARGO_MANIFEST_DIR"), "..", "..", "fixtures", "golden", relative].iter().collect();
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_str(&sanitize_lone_surrogates(&text)).expect("valid golden JSON")
}

/// Marker that wraps a lone surrogate's four hex digits inside a parsed string (U+0001 cannot
/// otherwise appear in these fixtures).
const MARK: char = '\u{1}';

/// JavaScript strings may hold unpaired surrogates and the generator writes them as `\uD83D`
/// escapes, which serde_json rejects. Replace each lone escape with `\u0001XXXX\u0001` so the
/// document parses and [`utf16_units`] can restore the original code unit.
fn sanitize_lone_surrogates(text: &str) -> String {
    let bytes = text.as_bytes();
    let mut out = String::with_capacity(text.len());
    let mut i = 0;
    let hex4 = |at: usize| -> Option<u16> {
        if at + 6 <= bytes.len() && bytes[at] == b'\\' && bytes[at + 1] == b'u' {
            u16::from_str_radix(std::str::from_utf8(&bytes[at + 2..at + 6]).ok()?, 16).ok()
        } else {
            None
        }
    };
    while i < bytes.len() {
        if let Some(unit) = hex4(i) {
            let is_high = (0xD800..=0xDBFF).contains(&unit);
            let is_low = (0xDC00..=0xDFFF).contains(&unit);
            if is_high {
                if let Some(next) = hex4(i + 6) {
                    if (0xDC00..=0xDFFF).contains(&next) {
                        out.push_str(&text[i..i + 12]);
                        i += 12;
                        continue;
                    }
                }
            }
            if is_high || is_low {
                out.push_str(&format!("\\u0001{}\\u0001", &text[i + 2..i + 6]));
                i += 6;
                continue;
            }
        }
        // Copy one UTF-8 character.
        let ch = text[i..].chars().next().unwrap();
        out.push(ch);
        i += ch.len_utf8();
    }
    out
}

/// UTF-16 code units of a parsed fixture string, restoring lone surrogates from their markers.
fn utf16_units(s: &str) -> Vec<u16> {
    let mut out = Vec::new();
    let mut chars = s.chars().peekable();
    while let Some(c) = chars.next() {
        if c == MARK {
            let hex: String = chars.by_ref().take(4).collect();
            out.push(u16::from_str_radix(&hex, 16).expect("marker hex"));
            let closing = chars.next();
            assert_eq!(closing, Some(MARK));
            continue;
        }
        let mut buf = [0u16; 2];
        out.extend_from_slice(c.encode_utf16(&mut buf));
    }
    out
}

fn fnv_utf16(units: &[u16]) -> u32 {
    let mut hash: u32 = 0x811c9dc5;
    for &unit in units {
        hash ^= u32::from(unit);
        hash = hash.wrapping_mul(0x01000193);
    }
    hash
}

#[test]
fn rng_streams_match_typescript() {
    let fixture = golden("rng.json");
    for vector in fixture["hashStringToU32"].as_array().unwrap() {
        let input = vector["input"].as_str().unwrap();
        let expected = vector["value"].as_f64().unwrap() as u32;
        if input.contains(MARK) {
            // Lone surrogates: hash the restored UTF-16 units directly.
            assert_eq!(fnv_utf16(&utf16_units(input)), expected, "hashStringToU32({input:?}) (raw units)");
        } else {
            assert_eq!(rng::hash_string_to_u32(input), expected, "hashStringToU32({input:?})");
        }
    }

    for entry in fixture["seeds"].as_array().unwrap() {
        let seed = &entry["seed"];
        let label = seed.to_string();
        let initial = match seed {
            Value::String(s) => rng::create_rng_state(s),
            other => rng::create_rng_state_from_number(other.as_f64().unwrap()),
        };
        assert_eq!(
            stable_json::stringify(&initial),
            stable_json::stringify_value(&entry["initial"]),
            "seed {label} initial"
        );

        let mut s = initial.clone();
        for (index, expected) in entry["u32"].as_array().unwrap().iter().enumerate() {
            let (value, next) = rng::next_u32(&s);
            assert_eq!(f64::from(value), expected.as_f64().unwrap(), "seed {label} u32[{index}]");
            s = next;
        }
        assert_eq!(stable_json::stringify(&s), stable_json::stringify_value(&entry["u32End"]), "seed {label} u32End");

        let mut s = initial.clone();
        for expected in entry["float"].as_array().unwrap() {
            let (value, next) = rng::next_float(&s);
            assert_eq!(value, expected.as_f64().unwrap(), "seed {label} float");
            s = next;
        }
        let mut s = initial.clone();
        for expected in entry["intDie"].as_array().unwrap() {
            let (value, next) = rng::next_int(&s, 1.0, 6.0);
            assert_eq!(value, expected.as_f64().unwrap(), "seed {label} intDie");
            s = next;
        }
        let mut s = initial.clone();
        for expected in entry["intSigned"].as_array().unwrap() {
            let (value, next) = rng::next_int(&s, -5.0, 5.0);
            assert_eq!(value, expected.as_f64().unwrap(), "seed {label} intSigned");
            s = next;
        }

        let mut rng = Rng::new(initial);
        for table in entry["weighted"].as_array().unwrap() {
            let weights: Vec<f64> = table["weights"].as_array().unwrap().iter().map(|w| w.as_f64().unwrap()).collect();
            for pick in table["picks"].as_array().unwrap() {
                assert_eq!(rng.weighted(&weights) as f64, pick.as_f64().unwrap(), "seed {label} weighted");
            }
        }
        assert_eq!(
            stable_json::stringify(&rng.state),
            stable_json::stringify_value(&entry["rngAfterWeighted"]),
            "seed {label} after weighted"
        );
    }
}

fn contains_mark(value: &Value) -> bool {
    match value {
        Value::String(s) => s.contains(MARK),
        Value::Array(items) => items.iter().any(contains_mark),
        Value::Object(map) => map.iter().any(|(k, v)| k.contains(MARK) || contains_mark(v)),
        _ => false,
    }
}

fn is_undefined(value: &Value) -> bool {
    value.get("$js").and_then(Value::as_str) == Some("undefined")
}

/// Decode the generator's tagged encoding into what `JSON.stringify` would see: undefined object
/// members vanish, undefined array slots and non-finite numbers become null, and -0 stays a number.
fn decode_tagged(value: &Value) -> Value {
    match value {
        Value::Object(map) => {
            if map.len() == 1 {
                if let Some(tag) = map.get("$js").and_then(Value::as_str) {
                    return match tag {
                        "-0" => Value::Number(serde_json::Number::from_f64(-0.0).unwrap()),
                        _ => Value::Null,
                    };
                }
            }
            let mut out = serde_json::Map::new();
            for (k, v) in map {
                if is_undefined(v) {
                    continue;
                }
                out.insert(k.clone(), decode_tagged(v));
            }
            Value::Object(out)
        }
        Value::Array(items) => Value::Array(items.iter().map(decode_tagged).collect()),
        other => other.clone(),
    }
}

#[test]
fn stable_stringify_and_hash_match_typescript() {
    for entry in golden("hash.json").as_array().unwrap() {
        let name = entry["name"].as_str().unwrap();
        if contains_mark(&entry["input"]) {
            // Lone surrogates cannot live in a Rust String; no engine state contains one.
            continue;
        }
        if is_undefined(&entry["input"]) {
            continue;
        }
        let stable = stable_json::stringify_value(&decode_tagged(&entry["input"]));
        assert_eq!(entry["stable"].as_str().unwrap(), stable, "{name}: stable text");
        assert_eq!(entry["hash"].as_str().unwrap(), hash_text(&stable), "{name}: hash");
    }
}
