//! Parity of the data types, content assembly and state creation with the TypeScript reference
//! engine. Fixtures come from `fixtures/golden` (generated by `tools/golden/generate.sh`).
//!
//! The sharp tool is the stable-JSON round trip: a fixture's `project` deserialized into
//! `GameProject` and stringified again must be byte-identical (same keys, same omitted/null
//! fields, same numbers). When it differs, the first differing character is reported with 200
//! characters of context on each side.

use farm_sim::schema::{GameProject, GameState};
use farm_sim::{hash_state, stable_json, state};
use serde_json::Value;
use std::path::PathBuf;

fn golden_dir(relative: &str) -> PathBuf {
    [env!("CARGO_MANIFEST_DIR"), "..", "..", "fixtures", "golden", relative].iter().collect()
}

fn golden(relative: &str) -> Value {
    let path = golden_dir(relative);
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("parse {}: {e}", path.display()))
}

/// Fixture names (without `.json`) in a golden subfolder, in ordinal order.
fn fixture_names(folder: &str) -> Vec<String> {
    let dir = golden_dir(folder);
    let mut names: Vec<String> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("list {}: {e}", dir.display()))
        .map(|entry| entry.expect("directory entry").path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "json"))
        .map(|path| path.file_stem().expect("file stem").to_string_lossy().into_owned())
        .collect();
    names.sort();
    names
}

/// Port of the C# `AssertSameStable`: the first differing character with context on each side.
fn same_stable(what: &str, expected: &str, actual: &str) -> Result<(), String> {
    if expected == actual {
        return Ok(());
    }
    let expected_chars: Vec<char> = expected.chars().collect();
    let actual_chars: Vec<char> = actual.chars().collect();
    let mut at = 0;
    while at < expected_chars.len() && at < actual_chars.len() && expected_chars[at] == actual_chars[at] {
        at += 1;
    }
    let excerpt = |chars: &[char]| -> String {
        let from = at.saturating_sub(200);
        let to = (at + 200).min(chars.len());
        chars[from..to].iter().collect()
    };
    Err(format!(
        "{what}: stable JSON differs at char {at} (expected {} chars, got {}).\nTS:   …{}…\nRust: …{}…",
        expected_chars.len(),
        actual_chars.len(),
        excerpt(&expected_chars),
        excerpt(&actual_chars)
    ))
}

fn same_hash(what: &str, expected: &Value, actual: &str) -> Result<(), String> {
    let expected = expected.as_str().unwrap_or_default();
    if expected == actual {
        Ok(())
    } else {
        Err(format!("{what}: expected hash {expected}, got {actual}"))
    }
}

/// `project` deserialized into `GameProject`, after checking it round-trips exactly.
fn round_trip_project(name: &str, project: &Value) -> Result<GameProject, String> {
    let typed: GameProject =
        serde_json::from_value(project.clone()).map_err(|e| format!("{name}: deserialize project: {e}"))?;
    same_stable(
        &format!("{name} project round-trip"),
        &stable_json::stringify_value(project),
        &stable_json::stringify(&typed),
    )?;
    Ok(typed)
}

fn check_content_fixture(name: &str) -> Result<(), String> {
    let fixture = golden(&format!("content/{name}.json"));
    let project = round_trip_project(name, &fixture["project"])?;

    let content = state::create_content_from_project(&project);
    let stable = stable_json::stringify(&content);
    same_stable(&format!("{name} content"), fixture["stable"].as_str().unwrap_or_default(), &stable)?;
    same_hash(&format!("{name} contentHash"), &fixture["contentHash"], &hash_state(&content))?;

    let created = state::create_game_state(&project, Some(&format!("content:{name}")));
    same_hash(&format!("{name} stateHash"), &fixture["stateHash"], &hash_state(&created))
}

fn check_replay_fixture(name: &str) -> Result<(), String> {
    let fixture = golden(&format!("replays/{name}.json"));
    let project = round_trip_project(name, &fixture["project"])?;

    let content = state::create_content_from_project(&project);
    same_hash(&format!("{name} contentHash"), &fixture["contentHash"], &hash_state(&content))?;

    let seed = fixture["seed"].as_str();
    let created = state::create_game_state(&project, seed);
    same_hash(&format!("{name} createdHash"), &fixture["createdHash"], &hash_state(&created))
}

fn check_save_fixture(name: &str) -> Result<(), String> {
    let fixture = golden(&format!("saves/{name}.json"));
    if fixture["result"]["ok"] != Value::Bool(true) {
        return Ok(());
    }
    let data = &fixture["result"]["data"];
    let typed: GameState =
        serde_json::from_value(data.clone()).map_err(|e| format!("{name}: deserialize save: {e}"))?;
    let stable = stable_json::stringify(&typed);
    same_stable(&format!("{name} save round-trip"), &stable_json::stringify_value(data), &stable)?;
    same_stable(&format!("{name} save stable"), fixture["stable"].as_str().unwrap_or_default(), &stable)?;
    same_hash(&format!("{name} save hash"), &fixture["hash"], &hash_state(&typed))
}

/// Runs every fixture and reports all failures at once, so one broken type does not hide the
/// others.
fn check_all(folder: &str, check: fn(&str) -> Result<(), String>) {
    let names = fixture_names(folder);
    assert!(!names.is_empty(), "no fixtures under fixtures/golden/{folder}");
    let checked: Vec<&String> = names.iter().filter(|name| name.as_str() != "index").collect();
    let failures: Vec<String> = checked.iter().filter_map(|name| check(name).err()).collect();
    eprintln!(
        "checked {} {folder} fixtures: {}",
        checked.len(),
        checked.iter().map(|s| s.as_str()).collect::<Vec<_>>().join(", ")
    );
    assert!(
        failures.is_empty(),
        "{} of {} {folder} fixtures failed:\n\n{}",
        failures.len(),
        checked.len(),
        failures.join("\n\n")
    );
}

#[test]
fn content_assembly_matches_typescript() {
    check_all("content", check_content_fixture);
}

#[test]
fn replay_projects_content_and_created_state_match_typescript() {
    check_all("replays", check_replay_fixture);
}

#[test]
fn saves_round_trip_exactly() {
    check_all("saves", check_save_fixture);
}
