//! Port of the retired C# `PacksAndStateTests.cs`: parity of content-builtin,
//! packs and state with the TypeScript reference engine. The expected JSON was generated by
//! running the TS engine on the same input (`fixtures/projects/content-builtin.json`;
//! `fixtures/projects/packs-project.json` → `fixtures/projects/packs-project.ts-reference.json`) — never
//! hand-edited.
//!
//! Since v9 (docs/NUMERICS.md) the engine keeps numbers on integer grids, so a reference number
//! that is off its grid (a 0.15 chance, say) comes back as the nearest grid value: the
//! comparisons allow that difference (1e-3) and nothing else.

use farm_sim::schema::{GameContent, GameProject};
use farm_sim::{content_builtin, hash_state, packs, state};
use indexmap::IndexMap;
use serde::Serialize;
use serde_json::Value;
use std::path::PathBuf;
use std::sync::OnceLock;

fn fixture(name: &str) -> Value {
    let path: PathBuf = [env!("CARGO_MANIFEST_DIR"), "..", "..", "fixtures", "projects", name].iter().collect();
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_str(&text).expect("valid fixture JSON")
}

fn reference(key: &str) -> Value {
    static REFERENCE: OnceLock<Value> = OnceLock::new();
    REFERENCE.get_or_init(|| fixture("packs-project.ts-reference.json"))[key].clone()
}

fn load_project() -> GameProject {
    serde_json::from_value(fixture("packs-project.json")).expect("packs-project.json is a GameProject")
}

fn ts_base_content() -> GameContent {
    serde_json::from_value(reference("base")).expect("base is a GameContent")
}

/// Equal JSON trees, numbers up to the v9 grids.
fn differences(path: &str, expected: &Value, actual: &Value, out: &mut Vec<String>) {
    match (expected, actual) {
        (Value::Number(a), Value::Number(b)) => {
            let (a, b) = (a.as_f64().unwrap_or(f64::NAN), b.as_f64().unwrap_or(f64::NAN));
            if (a - b).abs() > 1e-3 {
                out.push(format!("{path}: TS {a}, Rust {b}"));
            }
        }
        (Value::Object(a), Value::Object(b)) => {
            for key in a.keys().chain(b.keys().filter(|key| !a.contains_key(*key))) {
                let child = format!("{path}.{key}");
                differences(&child, a.get(key).unwrap_or(&Value::Null), b.get(key).unwrap_or(&Value::Null), out);
            }
        }
        (Value::Array(a), Value::Array(b)) if a.len() == b.len() => {
            for (index, (x, y)) in a.iter().zip(b).enumerate() {
                differences(&format!("{path}.{index}"), x, y, out);
            }
        }
        _ if expected == actual => {}
        _ => out.push(format!("{path}: TS {expected}, Rust {actual}")),
    }
}

fn assert_same_within_grid(key: &str, expected: &Value, actual: &Value) {
    let mut out = Vec::new();
    differences("", expected, actual, &mut out);
    assert!(out.is_empty(), "{key}: differs from the TS reference beyond the v9 grids:\n  {}", out.join("\n  "));
}

fn assert_matches_reference<T: Serialize>(key: &str, actual: &T) {
    let mut actual = serde_json::to_value(actual).expect("engine types always serialize");
    // A new state is a v5 save; the reference was written by v8 (save version 4).
    if let Some(version) = actual.pointer_mut("/meta/saveVersion") {
        *version = Value::from(4);
    }
    // The clock's day of season (#23) is newer than the reference; loading derives it.
    if let Some(clock) = actual.pointer_mut("/clock").and_then(Value::as_object_mut) {
        clock.shift_remove("dayOfSeason");
    }
    assert_same_within_grid(key, &reference(key), &actual);
}

#[test]
fn built_in_content_matches_the_ts_definitions() {
    let expected = fixture("content-builtin.json");
    let mut actual: IndexMap<&str, Value> = IndexMap::new();
    let mut put = |key: &'static str, value: &dyn erased::Serialize| {
        actual.insert(key, value.to_value());
    };
    put("items", &content_builtin::create_default_items());
    put("machineTypes", &content_builtin::create_default_machine_types());
    put("recipes", &content_builtin::create_default_recipes());
    put("animals", &content_builtin::create_default_animal_species());
    put("fish", &content_builtin::create_default_fish_tables());
    put("mineNodes", &content_builtin::mine_node_types());
    put("bands", &content_builtin::create_default_mine_bands());
    put("nodes", &content_builtin::default_node_types());
    put("shop", &content_builtin::create_default_shop());
    put("crops", &content_builtin::crop_definitions());
    // The multipliers are thousandths in v9; the reference holds the factors.
    let factors = |milli: IndexMap<String, u32>| -> IndexMap<String, f64> {
        milli.into_iter().map(|(key, value)| (key, f64::from(value) / 1000.0)).collect()
    };
    put("quality", &factors(content_builtin::quality_multipliers()));
    put("mutation", &factors(content_builtin::mutation_multipliers()));
    put("days", &content_builtin::DAYS_PER_SEASON);
    put("seasons", &content_builtin::SEASON_ORDER);
    put("tools", &content_builtin::tool_definitions());
    assert_same_within_grid("content-builtin", &expected, &serde_json::to_value(&actual).expect("serializes"));
}

/// Minimal object-safe serialization so the built-in table above can mix value types.
mod erased {
    pub trait Serialize {
        fn to_value(&self) -> serde_json::Value;
    }

    impl<T: serde::Serialize> Serialize for T {
        fn to_value(&self) -> serde_json::Value {
            serde_json::to_value(self).expect("engine types always serialize")
        }
    }
}

#[test]
fn resolve_pack_order_loads_dependencies_first_and_reports_problems() {
    let project = load_project();
    assert_matches_reference("order", &packs::resolve_pack_order(&project.content_packs));
}

#[test]
fn namespace_pack_rewrites_ids_and_intra_pack_references() {
    let project = load_project();
    assert_matches_reference("namespacedA", &packs::namespace_pack(&project.content_packs[1].pack));
    assert_matches_reference("namespacedB", &packs::namespace_pack(&project.content_packs[0].pack));
}

#[test]
fn merge_packs_into_content_applies_overrides_and_reports_conflicts() {
    let project = load_project();
    assert_matches_reference("merged", &packs::merge_packs_into_content(&ts_base_content(), &project.content_packs));
}

#[test]
fn apply_locale_strings_uses_later_packs_and_falls_back_to_authored_text() {
    let project = load_project();
    let merged = packs::merge_packs_into_content(&ts_base_content(), &project.content_packs).content;
    assert_matches_reference("localized", &packs::apply_locale_strings(merged.clone(), &project.content_packs, "fr"));
    assert_eq!(packs::apply_locale_strings(merged.clone(), &project.content_packs, "xx"), merged);
    assert_eq!(packs::apply_locale_strings(merged.clone(), &project.content_packs, ""), merged);
    // The one-pass merge used at play time localizes the same way.
    for locale in ["fr", "xx", ""] {
        let localized = packs::apply_locale_strings(merged.clone(), &project.content_packs, locale);
        let one_pass = packs::merge_packs_into_content_localized(&ts_base_content(), &project.content_packs, locale);
        assert_eq!(one_pass.content, localized, "{locale}");
    }
}

#[test]
fn stamp_packs_lists_enabled_packs() {
    let project = load_project();
    assert_matches_reference("stamp", &packs::stamp_packs(&project.content_packs));
}

#[test]
fn create_game_state_matches_the_ts_shape() {
    let project = load_project();
    assert_matches_reference("stateSeeded", &state::create_game_state(&project, Some("seed-x")));
    assert_matches_reference("stateDefault", &state::create_game_state(&project, None));
}

#[test]
fn create_game_state_hashes_like_the_ts_reference_state() {
    let project = load_project();
    let mut reference: farm_sim::GameState = serde_json::from_value(reference("stateSeeded")).expect("a GameState");
    reference.meta.save_version = farm_sim::schema::save::CURRENT_SAVE_VERSION;
    // The reference predates the clock's day of season (#23): derive it as loading a save does.
    farm_sim::game_time::reconcile_clock(&project.settings.calendar, &mut reference.clock);
    assert_eq!(hash_state(&reference), hash_state(&state::create_game_state(&project, Some("seed-x"))));
}

#[test]
fn apply_state_to_project_matches_the_ts_projection() {
    let project = load_project();
    let created = state::create_game_state(&project, Some("seed-x"));
    assert_matches_reference("applied", &state::apply_state_to_project(&project, &created));
}

#[test]
fn create_content_from_project_matches_the_ts_content() {
    let project = load_project();
    assert_matches_reference("base", &state::create_base_content_from_project(&project));
    assert_matches_reference("content", &state::create_content_from_project(&project));
}
