//! Port of `tests/FarmEngine.Core.Tests/Core/PacksAndStateTests.cs`: parity of content-builtin,
//! packs and state with the TypeScript reference engine. The expected JSON was generated by
//! running the TS engine on the same input (`Fixtures/content-builtin.json`;
//! `Fixtures/packs-project.json` → `Fixtures/packs-project.ts-reference.json`) — never
//! hand-edited.

use farm_sim::schema::{GameContent, GameProject};
use farm_sim::{content_builtin, hash_state, packs, stable_json, state};
use indexmap::IndexMap;
use serde::Serialize;
use serde_json::Value;
use std::path::PathBuf;
use std::sync::OnceLock;

fn fixture(name: &str) -> Value {
    let path: PathBuf =
        [env!("CARGO_MANIFEST_DIR"), "..", "..", "tests", "FarmEngine.Core.Tests", "Fixtures", name].iter().collect();
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_str(&text).expect("valid fixture JSON")
}

fn reference(key: &str) -> Value {
    static REFERENCE: OnceLock<Value> = OnceLock::new();
    REFERENCE.get_or_init(|| fixture("packs-project.ts-reference.json"))[key].clone()
}

fn load_project() -> GameProject {
    serde_json::from_value(fixture("packs-project.json")).expect("packs-project.json is a GameProject")
}

fn ts_base_content() -> GameContent {
    serde_json::from_value(reference("base")).expect("base is a GameContent")
}

fn assert_matches_reference<T: Serialize>(key: &str, actual: &T) {
    let expected = stable_json::stringify_value(&reference(key));
    let actual = stable_json::stringify(actual);
    assert!(expected == actual, "{key}: stable JSON differs.\nTS:   {expected}\nRust: {actual}");
}

#[test]
fn built_in_content_matches_the_ts_definitions() {
    let expected = fixture("content-builtin.json");
    let mut actual: IndexMap<&str, Value> = IndexMap::new();
    let mut put = |key: &'static str, value: &dyn erased::Serialize| {
        actual.insert(key, value.to_value());
    };
    put("items", &content_builtin::create_default_items());
    put("machineTypes", &content_builtin::create_default_machine_types());
    put("recipes", &content_builtin::create_default_recipes());
    put("animals", &content_builtin::create_default_animal_species());
    put("fish", &content_builtin::create_default_fish_tables());
    put("mineNodes", &content_builtin::mine_node_types());
    put("bands", &content_builtin::create_default_mine_bands());
    put("nodes", &content_builtin::default_node_types());
    put("shop", &content_builtin::create_default_shop());
    put("crops", &content_builtin::crop_definitions());
    put("quality", &content_builtin::quality_multipliers());
    put("mutation", &content_builtin::mutation_multipliers());
    put("days", &content_builtin::DAYS_PER_SEASON);
    put("seasons", &content_builtin::SEASON_ORDER);
    put("tools", &content_builtin::tool_definitions());
    assert_eq!(stable_json::stringify_value(&expected), stable_json::stringify(&actual));
}

/// Minimal object-safe serialization so the built-in table above can mix value types.
mod erased {
    pub trait Serialize {
        fn to_value(&self) -> serde_json::Value;
    }

    impl<T: serde::Serialize> Serialize for T {
        fn to_value(&self) -> serde_json::Value {
            serde_json::to_value(self).expect("engine types always serialize")
        }
    }
}

#[test]
fn resolve_pack_order_loads_dependencies_first_and_reports_problems() {
    let project = load_project();
    assert_matches_reference("order", &packs::resolve_pack_order(&project.content_packs));
}

#[test]
fn namespace_pack_rewrites_ids_and_intra_pack_references() {
    let project = load_project();
    assert_matches_reference("namespacedA", &packs::namespace_pack(&project.content_packs[1].pack));
    assert_matches_reference("namespacedB", &packs::namespace_pack(&project.content_packs[0].pack));
}

#[test]
fn merge_packs_into_content_applies_overrides_and_reports_conflicts() {
    let project = load_project();
    assert_matches_reference("merged", &packs::merge_packs_into_content(&ts_base_content(), &project.content_packs));
}

#[test]
fn apply_locale_strings_uses_later_packs_and_falls_back_to_authored_text() {
    let project = load_project();
    let merged = packs::merge_packs_into_content(&ts_base_content(), &project.content_packs).content;
    assert_matches_reference("localized", &packs::apply_locale_strings(merged.clone(), &project.content_packs, "fr"));
    assert_eq!(packs::apply_locale_strings(merged.clone(), &project.content_packs, "xx"), merged);
    assert_eq!(packs::apply_locale_strings(merged.clone(), &project.content_packs, ""), merged);
}

#[test]
fn apply_pack_to_project_materializes_content_and_player_start() {
    let project = load_project();
    assert_matches_reference("applyA", &packs::apply_pack_to_project(&project, &project.content_packs[1].pack));
}

#[test]
fn stamp_packs_lists_enabled_packs() {
    let project = load_project();
    assert_matches_reference("stamp", &packs::stamp_packs(&project.content_packs));
}

#[test]
fn create_game_state_matches_the_ts_shape() {
    let project = load_project();
    assert_matches_reference("stateSeeded", &state::create_game_state(&project, Some("seed-x")));
    assert_matches_reference("stateDefault", &state::create_game_state(&project, None));
}

#[test]
fn create_game_state_hashes_like_the_ts_engine() {
    let project = load_project();
    assert_eq!(hash_state(&reference("stateSeeded")), hash_state(&state::create_game_state(&project, Some("seed-x"))));
}

#[test]
fn apply_state_to_project_matches_the_ts_projection() {
    let project = load_project();
    let created = state::create_game_state(&project, Some("seed-x"));
    assert_matches_reference("applied", &state::apply_state_to_project(&project, &created));
}

#[test]
fn create_content_from_project_matches_the_ts_content() {
    let project = load_project();
    assert_matches_reference("base", &state::create_base_content_from_project(&project));
    assert_matches_reference("content", &state::create_content_from_project(&project));
}
