using System.Text.Json;
using FarmEngine.Json;
using FarmEngine.Schemas;

namespace FarmEngine.Core.Tests.Core;

/// <summary>
/// C#-side parity tests for content-builtin.ts, packs.ts and state.ts. The
/// expected JSON was generated by running the TS reference engine on the same
/// input (Fixtures/content-builtin.json; Fixtures/packs-project.json →
/// Fixtures/packs-project.ts-reference.json) — never hand-edit those files.
/// </summary>
public class PacksAndStateTests
{
    private static string FixturePath(string name) => Path.Combine(AppContext.BaseDirectory, "Fixtures", name);

    private static readonly Lazy<JsonElement> Reference = new(() =>
        JsonDocument.Parse(File.ReadAllText(FixturePath("packs-project.ts-reference.json"))).RootElement);

    private static GameProject LoadProject() =>
        JsonDefaults.Deserialize<GameProject>(File.ReadAllText(FixturePath("packs-project.json")))!;

    private static JsonElement Ref(string key) => Reference.Value.GetProperty(key);

    private static void AssertMatchesReference<T>(string key, T actual) =>
        Assert.Equal(StableJson.Stringify(Ref(key)), StableJson.Stringify(actual));

    private static GameContent TsBaseContent() => Ref("base").Deserialize<GameContent>(JsonDefaults.Options)!;

    [Fact]
    public void BuiltInContentMatchesTheTsDefinitions()
    {
        var expected = JsonDocument.Parse(File.ReadAllText(FixturePath("content-builtin.json"))).RootElement;
        var actual = new OrderedDictionary<string, object>
        {
            ["items"] = ContentBuiltin.CreateDefaultItems(),
            ["machineTypes"] = ContentBuiltin.CreateDefaultMachineTypes(),
            ["recipes"] = ContentBuiltin.CreateDefaultRecipes(),
            ["animals"] = ContentBuiltin.CreateDefaultAnimalSpecies(),
            ["fish"] = ContentBuiltin.CreateDefaultFishTables(),
            ["mineNodes"] = ContentBuiltin.MineNodeTypes,
            ["bands"] = ContentBuiltin.CreateDefaultMineBands(),
            ["nodes"] = ContentBuiltin.DefaultNodeTypes,
            ["shop"] = ContentBuiltin.CreateDefaultShop(),
            ["crops"] = ContentBuiltin.CropDefinitions,
            ["quality"] = ContentBuiltin.QualityMultipliers,
            ["mutation"] = ContentBuiltin.MutationMultipliers,
            ["days"] = ContentBuiltin.DaysPerSeason,
            ["seasons"] = ContentBuiltin.SeasonOrder,
            ["tools"] = ContentBuiltin.ToolDefinitions,
        };
        Assert.Equal(StableJson.Stringify(expected), StableJson.Stringify(actual));
    }

    [Fact]
    public void ResolvePackOrderLoadsDependenciesFirstAndReportsProblems()
    {
        var project = LoadProject();
        AssertMatchesReference("order", Packs.ResolvePackOrder(project.ContentPacks));
    }

    [Fact]
    public void NamespacePackRewritesIdsAndIntraPackReferences()
    {
        var project = LoadProject();
        AssertMatchesReference("namespacedA", Packs.NamespacePack(project.ContentPacks[1].Pack));
        AssertMatchesReference("namespacedB", Packs.NamespacePack(project.ContentPacks[0].Pack));
    }

    [Fact]
    public void MergePacksIntoContentAppliesOverridesAndReportsConflicts()
    {
        var project = LoadProject();
        AssertMatchesReference("merged", Packs.MergePacksIntoContent(TsBaseContent(), project.ContentPacks));
    }

    [Fact]
    public void ApplyLocaleStringsUsesLaterPacksAndFallsBackToAuthoredText()
    {
        var project = LoadProject();
        var merged = Packs.MergePacksIntoContent(TsBaseContent(), project.ContentPacks).Content;
        AssertMatchesReference("localized", Packs.ApplyLocaleStrings(merged, project.ContentPacks, "fr"));
        Assert.Same(merged, Packs.ApplyLocaleStrings(merged, project.ContentPacks, "xx"));
        Assert.Same(merged, Packs.ApplyLocaleStrings(merged, project.ContentPacks, ""));
    }

    [Fact]
    public void ApplyPackToProjectMaterializesContentAndPlayerStart()
    {
        var project = LoadProject();
        AssertMatchesReference("applyA", Packs.ApplyPackToProject(project, project.ContentPacks[1].Pack));
    }

    [Fact]
    public void StampPacksListsEnabledPacks()
    {
        var project = LoadProject();
        AssertMatchesReference("stamp", Packs.StampPacks(project.ContentPacks));
    }

    [Fact]
    public void CreateGameStateMatchesTheTsShape()
    {
        var project = LoadProject();
        AssertMatchesReference("stateSeeded", EngineState.CreateGameState(project, seed: "seed-x"));
        AssertMatchesReference("stateDefault", EngineState.CreateGameState(project));
    }

    [Fact]
    public void CreateGameStateHashesLikeTheTsEngine()
    {
        var project = LoadProject();
        Assert.Equal(Hash.HashState(Ref("stateSeeded")), Hash.HashState(EngineState.CreateGameState(project, seed: "seed-x")));
    }

    [Fact]
    public void ApplyStateToProjectMatchesTheTsProjection()
    {
        var project = LoadProject();
        var state = EngineState.CreateGameState(project, seed: "seed-x");
        AssertMatchesReference("applied", EngineState.ApplyStateToProject(project, state));
    }

    [Fact]
    public void ReconcilePackItemsReturnsTheSameStateWhenNothingMoves()
    {
        var state = new GameState
        {
            Player = new PlayerState { Inventory = [new InventorySlot { Item = new Item { Id = "wheat" }, Quantity = 1 }] },
        };
        Assert.Same(state, Packs.ReconcilePackItems(state, new HashSet<string>()));
    }

    [Fact]
    public void CreateContentFromProjectMatchesTheTsContent()
    {
        var project = LoadProject();
        AssertMatchesReference("base", EngineState.CreateBaseContentFromProject(project));
        AssertMatchesReference("content", EngineState.CreateContentFromProject(project));
    }
}
